### ISSUE TITLE
There is no warning for user on Mobile when he doesn't verify his email yet

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1000]
# Precondition
Sign Up on Mobile App
The user doesn't verify his email yet

# Actual Result
When the user logged in on Mobile App, there's nothing to inform him to verify the email address as on the Web version
**Mobile**
https://user-images.githubusercontent.com/69950655/135795813-d3eadda3-3557-4880-a37b-b18cfa5cea78.mp4

**Web:**
![screenshot_109](https://user-images.githubusercontent.com/69950655/135795783-701cc35f-af2f-4d0e-955a-5977a2d932b6.png)

# Expected result
There should have a warning on Mobile about email verifying

# Environment

- Build version: 3.0.7
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- Production

**Comment by huynguyennovem** [comment]
As I checked, there is no design for this screen on mobile yet. So, this can be a feature that has not implemented. Pls confirm and change the label of this issue.

**Comment by tlle14** [comment]
This is an omission in the sign-up process. I think it's an issue. 
@BenoitTallandier Hi, could you please confirm that we should put this feature in the app?
If yes, we should ask our designer to have a design.

**Comment by BenoitTallandier** [comment]
Hi @tlle14 
Yes, we should have this warning. I'll create an US for that.

**Comment by tlle14** [comment]
Thanks, so I can close this issue and testing this feature after it is implemented
