### ISSUE TITLE
Create Workspace > The create workspace button is enabled for Free plan user

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1002]
# Precondition
The user is in Free Plan
![image](https://user-images.githubusercontent.com/69950655/135828121-36683180-07b2-4c49-8368-7b0caa2fd52a.png)

# Actual Result
On Mobile App, the user is able to create a workspace in Free Plan
While on the Web, it is forbidden.

**On Mobile**
https://user-images.githubusercontent.com/69950655/135826886-6bd59830-5fbb-4171-a5b9-05ca90fef001.mp4

**On Web**
![screenshot_110](https://user-images.githubusercontent.com/69950655/135826462-bdb13217-aaea-4647-9d6a-4b159269afef.png)

# Expected Result
It should avoid creating a workspace on Mobile when the user is in Free Plan

# Environment
- Build version: 3.0.7
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- Prod

**Comment by EvGen94** [comment]
@tlle14 This is weird, the create workspace button is enabled only for company owner and admin

**Comment by tlle14** [comment]
Hi @EvGen94 
On Web, a Free Plan Company cannot create another workspace. The button is still enabled, however, when the user clicks on it, it shows a pop-up as below. 
You can try to reproduce on production. On QA I don't see it works. 
![image](https://user-images.githubusercontent.com/69950655/144782391-579fb531-4950-4a46-9b96-10b3f2130d55.png)


Hi @RomaricMourgues kindly confirm if this feature is still applied? I don't see the restriction on QA environment.

**Comment by RomaricMourgues** [comment]
Yes it should be applied.

**Comment by tlle14** [comment]
Thank @RomaricMourgues for your confirmation.
Hi @EvGen94 if you have a plan to fix this ticket, please ask @BastiaanVanGaalen and @BenoitTallandier to choose a solution for this case.

**Comment by BenoitTallandier** [comment]
# TODO 
BTA : write the text for this issue
