### ISSUE TITLE
Message > The second reaction cannot display when the message is too short

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1006]
# Precondition
The message is short

# Actual Result
UserA react to the message by icon 1
UserB continue to react the message by icon 2
But Icon 2 doesn't display because the bubble chat is small.
https://user-images.githubusercontent.com/69950655/136143342-8d1d4270-996e-4942-be19-7a51dcaad934.mp4

# Expected Result
All the reacted icons should be displayed. It shouldn't depend on the size of the bubble chat.

# Environment 
- Build version: 3.0.8
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- Production

**Comment by huynguyennovem** [comment]
The bug:

![Screenshot_1637120615](https://user-images.githubusercontent.com/29337364/142155316-7f3245a6-1868-41d5-93b5-44956ad53bff.png)

**Comment by tlle14** [comment]
Thank @huynguyennovem 
The reactions are no more hidden.
