### ISSUE TITLE
Notification > It doesn't have push notification on iOS App/ OR Android App

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1007]
# Actual result
There is no push notification on iOS App

# Expected Result
There should have push notification on the ios app

# Environment
- Build version: 3.0.8 on Test Flight
- Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- Production server

**Comment by tlle14** [comment]
Thank @EvGen94 
I see notifications on iOS but it doesn't appear on Android App. (On production)
Could you please check?

**Comment by EvGen94** [comment]
Сhecked on several devices everywhere it works (android ios), I don't know what I can do

**Comment by tlle14** [comment]
I don't see the notification on both QA server and Production. 
@EvGen94 could you please check? We may need to ask @RomaricMourgues to help.

**Comment by tlle14** [comment]
I deleted the last comment. 
After reinstalling the app (again), the notification works. 
So retest pass!
