### ISSUE TITLE
The old data is still persist when logging in as a new user

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1008]
# Precondition
UserA logged in on ServerA

# Actual Result
When UserA logout, UserB uses the same device to log in on ServerB with UserB credential.
The app displays UserA's Company/Workspace for UserB 

https://user-images.githubusercontent.com/69950655/136188292-8b0c521e-58de-4cfb-9947-e66d50cdde5f.mp4

# Expected Result
The data should be cleared when user logout

# Environment

- Build version: 3.0.8
- Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA Server and Production Server

**Comment by huynguyennovem** [comment]
I can not re-procedure this bug. Pls confirm this.

https://user-images.githubusercontent.com/29337364/142558407-1e130ff3-d84e-4537-89bd-fdaf13356f29.mp4

**Comment by tlle14** [comment]
I usually encounter this issue on Android device when switching between QA server to production server. 
Could you please give it a try? @huynguyennovem

**Comment by tlle14** [comment]
Duplicate with https://github.com/linagora/Twake-Mobile/issues/985

**Comment by EvGen94** [comment]
Duplicate with #899
