### ISSUE TITLE
Channel > Channel icon is too large 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1010]
# Actual Result
Some icon of a channel has been out of the frame
![screenshot_113](https://user-images.githubusercontent.com/69950655/136344575-fc11335f-e32b-49e2-a412-c9cd0c9e0ca7.png)

# Expected Result
It should be able to automatically scale to fit the frame

# Environment
- Build version: 3.0.8
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment and Prod

**Comment by huynguyennovem** [comment]
Can not reproduce. Pls re-test this.

<img src="https://user-images.githubusercontent.com/29337364/142129636-415ffc38-1eea-4784-bb11-0a9289ffb63e.png" alt="Screenshot_1637119106" width="400"/>

**Comment by tlle14** [comment]
It seems only to happen on Samsung A51. 
I cannot reproduce on other phones.

**Comment by tlle14** [comment]
The issue happens only when the text size is large. 

https://user-images.githubusercontent.com/69950655/151326331-f1b11391-73c7-4b73-a5af-2d5c472f63b5.mp4
