### ISSUE TITLE
Server Setting > It doesn't display error message when inputting invalid server

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1012]
# Actual Result
When adding some characters after a valid server (example: `https://web.twake.appaaaaaaaaa`) then submit, it doesn't show an error message.
After clear the server textbox, the invalid server address displays as a placeholder

https://user-images.githubusercontent.com/69950655/136733285-7212e412-2d0e-4305-ae79-016da967f4f3.mp4

# Expected Result
It should be able to detect the invalid server and display an error message.
The invalid server shouldn't become placeholder

# Environment
Build version: 3.0.8 on App Store
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch

**Comment by huynguyennovem** [comment]
The error message is still shown, but it takes a long time to wait. Pls confirm it via my demo video:
https://github.com/linagora/Twake-Mobile/pull/1069#issue-1054808665

-> I only fix the wrong `placeholder` when it's an invalid server. 
-> Recommend to update design for this by adding loading UI when user waiting to connect/verifying..

**Comment by tlle14** [comment]
Thank Huy for the suggestion. 
1. The wrong placeholder => PASS
https://user-images.githubusercontent.com/69950655/143822792-161bb396-822d-4291-b168-1bfb27027761.mp4

2. About the connecting time, change it to be an improvement https://github.com/linagora/Twake-Mobile/issues/1115
