### ISSUE TITLE
[Story] I receive a magic link

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1022]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am not a Twake user 
And I don't have the application on my mobile installed
When I look to signup with a magic link
Then I open the link
And the mobile store opens on the Twake page,
And I click on "install"
And I click on "open"
And I see a page explaining that I can join the workspace
And I click on "join"
And I am redirected to the signup form (console)
Then I am redirected to Twake chat in the workspace related to the magic link
```

```gherkin
Given I am not a Twake user 
And I have the application on my mobile installed
When I look to signup with a magic link
Then I open the link, the mobile application turns on
And I see a page explaining that I can join the workspace
And I click on "join"
And I am redirected to the signup form (console)
Then I am redirected to Twake chat in the workspace related to the magic link
```

```gherkin
Given I am a Twake user 
And I am not logged 
And I have the mobile app installed
When I look to join a company with a magic link
Then I open the link, the mobile application turns on
And I see a page explaining that I can join the workspace
And I click on "join"
And I am redirected to the signup form (console)
And I click on "login"
Then I enter my credentials
Then I am redirected to Twake chat in the workspace related to the magic link
```

```gherkin
Given I am Twake user 
And I have the application installed on my mobile
And I am logged in
When I look to join the company with a magic link
Then I open it
And the mobile application turns on
And I see a page explaining that I can join the workspace
And I click on "join"
And I am redirected to the related workspace
```

```gherkin
Given I have the application installed on my mobile
When I look to join the company with a magic link
And the magic link is expired
Then I open it
And the mobile application turns on
And I see the error page
```
```gherkin
Given I don't have the application installed on my mobile
When I look to join the company with a magic link
And the magic link is expired
Then I open it
And the mobile store opens on the Twake page,
And I click on "install"
And I click on "open"
And the mobile application turns on
And I see the error page
```
## Flow

![magiklink drawio](https://user-images.githubusercontent.com/22451567/141955215-bd233fe6-7dd7-4c53-a62e-e725ef6f1229.png)

## Business case
- In every case I can have a page presenting what I will join. 
- If I am not connected on Twake, when I click on "join", I'm redirected to the console
- If I am using an expired link, the error page is shown to me. The button of this page redirect to the classical signup process
- If I don't have any other workspace, I can't close the `no-longuer-available` popup, I have to create my company to continue.
- If I have an other company or workspace, I can click on the button "close" in the popup `no-longuer-available` and `joinTheTeam` leading me to the default workspace I have.
- If I receive a link from an other server, I follow the story #1155 

## Criteria
- [ ] When I am connected and I use a valid magic link and I click on the "join" button, I am added to the related workspace and I am redirect to this workspace
- [ ] When I am not connected and I use a valid magic link and I click on the "join" button, I am redirected to the console signup page 
- [ ] When I use an expired link (someone regenerate it after sending it to me), I land on the error page
 
## UI UX Design
![13 Pro - 1](https://user-images.githubusercontent.com/22451567/138258603-0fe9ea4b-c8e7-4248-8729-574c854615ff.png)
![13 Pro - 2](https://user-images.githubusercontent.com/22451567/138258596-7171eacf-f901-4d84-8e77-84bb9a483d83.png)

**Comment by tlle14** [comment]
Hello @BenoitTallandier , please help me to confirm these things:
1. When a whole new user clicks on the magic link, does he need to be approved to the company? Or he click the link, sign up then can join both company and the corresponding workspace?
2. What is his role after joining (a member or a guest)? Since anyone has the link can join the app, I think it will affect to the subscription.

**Comment by tlle14** [comment]
Hi @BenoitTallandier @BastiaanVanGaalen 
I see on the error page, what is the behavior when clicking on "Create your company" button?
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/618c51e0cce8c7b4f3af19c9

**Comment by tlle14** [comment]
Hi @BenoitTallandier Thanks for your confirmation. About "Create your company" button on the error page, do you agree with the design? Will it open a browser and redirect to Console page?

**Comment by tlle14** [comment]
@BenoitTallandier hi, do you have any update on this?

**Comment by tlle14** [comment]
As Benoit's confirmation, there is a button "Create your company" on the error page.
When clicking on the button, it will redirect to Console page on the browser.
