### ISSUE TITLE
[Story] Manage magic link

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1023]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a user
When I look to invite someone in my workspace by link
And I click on "invite users"
Then I click on "Share"
And I send the popup "~share with" mobile popup
```

## Business case
When I click on "copy link", the link is copied in my clipboard and a little tooltip appears to confirm that I copied the link.

When I click on "Share", the mobile popup appears and I can share to a user the message "hey, join me on Twake : [TwakeLink]"

When I click on "generate a new link", I have a confirmation popup saying the previous won't be usable anymore. If I press yes, a new link will be generated. 

When I click "invite by email", I can enter emails in order to invite people. When I use the email invitation, I use the basic email invitation used on Twake. I don't send manually the email, Twake we'll do it for me.
![image](https://user-images.githubusercontent.com/22451567/140381958-6b710c6d-03a9-4cf4-9fb3-5276ce39a904.png)
 

## Criteria (Test case)
- [ ] When I click on "copy the link" and I past, I can see a link
- [ ] When I click on "Share" the mobile popup appears 
- [ ] When I click on "copy the link", I past it, I click on "generate a new link", I past it : links should be different
 
## UI UX Design
![dkeahjz drawio](https://user-images.githubusercontent.com/22451567/138260879-0f1eb814-aff5-4c96-aef2-ccbcff685dfa.png)

Here the design : https://zpl.io/2ZAqzgl

## Related

**Comment by tlle14** [comment]
Hi @BenoitTallandier , I don't see the detailed description for "share by email" (Enter an email in your mockup). Please confirm the design and the demo at https://github.com/linagora/Twake-Mobile/pull/1046#issuecomment-956299507

**Comment by BenoitTallandier** [comment]
Hi @tlle14 
My bad, the process was not described, and the design was driving you in the bad way. 
I can't build in detail the US today, but here the draft : https://github.com/linagora/Twake-Mobile/issues/1051

**Comment by tlle14** [comment]
Thank @BenoitTallandier. I hope you can finish the story as soon as possible. 
Besides, we should ask @BastiaanVanGaalen for updating the design of the invite by email function.

**Comment by huynguyennovem** [comment]
> Hi @tlle14 My bad, the process was not described, and the design was driving you in the bad way. I can't build in detail the US today, but here the draft : #1051

@BenoitTallandier As I see the current API for email invitation has no input params for `magic link`. Is it ready to support for magic link?

- API: 

```
Request:
{
    "invitations": [{
     "email": "some_email",
     "role": "moderator" | "member",
     "company_role": "member" | "guest"
    }, ...]
}

Response:
{
    "result": [
        {
            "email": "some_email",
            "status": "ok" | "error",
            "message": "some message"
        }, ...
  ],
}
```

**Comment by tlle14** [comment]
Hi @BenoitTallandier 
Could you please confirm these permission tables? Now I'm quite mixing up between Company Roles and Workspace Roles.

<google-sheets-html-origin>

Company | Workspace
-- | --
Owner | Admin/Moderator
Admin | Admin/Moderator
Member | Member
Guest | Guest


<google-sheets-html-origin>

  | Company Owner | Company Admin | Workspace Moderator | Workspace Admin | Company member | Guest
-- | -- | -- | -- | -- | -- | --
View link | Y | Y | Y | Y | Y | N
Share link | Y | Y | Y | Y | Y | N
Generate link | Y | Y | Y | Y | N | N
Click to join | Y | Y | - | - | Y | Y
After joining the workspace | Workspace Admin/Mod? | Workspace Admin/Mod? | - | - | Company Member | Guest



1. What is the difference between WORKSPACE ADMIN and WORKSPACE MODERATOR?
2. What is the difference between Workspace Admin and Company Admin? After joining the workspace, the Company Admin/Owner becomes Workspace Admin(Or Moderator?)?

**Comment by huynguyennovem** [comment]
FYI, it seems there is some rules that applied for `workspace` here when trying to generate link.
Because of I received this message from server:
> RESPONSE: {statusCode: 403, error: Forbidden, message: Only workspace members can perform this action}

Pls help to clarify this.

**Comment by RomaricMourgues** [comment]
Workspace admins and moderators are only one single thing: workspace moderator (new name to avoid confusion with company admins)
So you have:

- On the company scope
Company owner and company admin (from Twake Chat point of view this is the same)
Company member
Company guest

- On the workspace scope
Workspace moderator
Workspace member

- Some additional rules:
A company admin or owner always has the workspace moderator rights too
Company guests cannot be workspace moderators

So about your questions:
1. This is the same thing
2. Yes it becomes a workspace moderator (any workspace creator is moderator of the created workspace)

**Comment by RomaricMourgues** [comment]
@huynguyennovem if you could get me credentials of a user that have this error for me to debug ? :)
