### ISSUE TITLE
Direct > Displaying incorrect information when scroll to the first message of a direct chat

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1027]
# Precondition 
A direct chat has messaes already

# Actual Result
When scrolling up to see the first messages, it displays a default channel icon (as in the design) and the message "This is the first message of the channel"
![image](https://user-images.githubusercontent.com/69950655/138629485-0c7a48f1-5fc5-410e-9fe5-10506eff1cd3.png)

# Expected Result
It should display the user avatar and a message "This is the first message" as in the Web version
![image](https://user-images.githubusercontent.com/69950655/138629552-e626e211-0de0-410c-a8a8-f15d8a38ae30.png)

# Environment
- Build version: Android 3.0.9 - iOS 1.0.1(31) 
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 17- iOS 13.3.1 - 4.7 inch
- Production

**Comment by huynguyennovem** [comment]
There is no first message anymore. Instead of that, it loads all content message only as design: https://zpl.io/bzOR3v4

Pls confirm this.

https://user-images.githubusercontent.com/29337364/142374414-4cc06c13-7ce0-42d1-855e-1fc676ed92e3.mov

**Comment by tlle14** [comment]
hello @huynguyennovem 
The issue is about a direct message and it only applies for the direct chat that has chat history

**Comment by EvGen94** [comment]
@BastiaanVanGaalen please check it

**Comment by BastiaanVanGalen** [comment]
@EvGen94  I don't mind if we will be displaying the user avatar instead of a default channel icon for direct chats. In case of direct with multiple participants we have to display some previews. I will prepare the design for that.

**Comment by hantt12** [comment]
This is no longer the case because if there are messages, the avatar and "no messages" message won't be shown
