### ISSUE TITLE
Thread > Reply counter text and reactions cannot be displayed together in a small screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1028]
# Precondition
A thread has multiple reactions (about 7 reactions)

# Actual Result
On Android, it displays all reactions and hides the reply counter text 
https://user-images.githubusercontent.com/69950655/138631659-d7386e2c-d14f-47d7-9f0e-5ee5284637d4.mp4

On iOS, it doesn't display the new reaction and doesn't hide the reply counter text
![image](https://user-images.githubusercontent.com/69950655/138631564-402694f8-a61f-4c93-bef4-1bcbd3b818c6.png)

# Expected Result
When there have multiple reactions, it should display both all the reactions and the reply counter text. 
The reactions list should be displayed in another line.

# Environment
- Build version: Android 3.0.9 - iOS 1.0.1(31)
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 17- iOS 13.3.1 - 4.7 inch
- Production

**Comment by huynguyennovem** [comment]
This is expected UI as the design from here: https://zpl.io/Vky53MK.
Pls help to confirm this @tlle14 :)

**Comment by tlle14** [comment]
Hi @huynguyennovem the design didn't cover this case. 
Hi @BastiaanVanGaalen could you please provide the behavior in case there has a lot of reactions (>6 reactions). Should we display all of them or should open another screen for displaying reactions....?

**Comment by huynguyennovem** [comment]
I recommend the reactions can horizontal scrolling when they are too long. Pls watch the demo video: https://github.com/linagora/Twake-Mobile/pull/1074#issue-1055979184

**Comment by tlle14** [comment]
Retest pass! Thanks!

https://user-images.githubusercontent.com/69950655/143398723-e81131d8-bb17-425c-be3f-a7e360a71826.mp4
