### ISSUE TITLE
Feedback > Sometimes user cannot restart app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1029]
# Precondition
The app is closed (no background running) 
Leave the app unused for a quite long time (more than a day)

# Actual Result
When opening the app, it displays the splash screen and cannot move

# Expected Result
Please investigate this case since we cannot reproduce it frequently
Consider these causes:
- Internet connection stability
- Server availability (Production server)
- The app is in upgrading progress (I check the last update is 21 Oct, the issue happens on 25 Oct)

We should display a warning message for those problems. 
And should have a timeout for splash screen displaying?

# Environment
- Build version: Android 3.0.9 - iOS 1.0.1(31)
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 17- iOS 13.3.1 - 4.7 inch
- Production

**Comment by huynguyennovem** [comment]
- Update bug investigation:
I tried to simulate a no Internet connection case for this then it leads to this bug. 

```
SocketException: Failed host lookup: 'web.qa.twake.app' (OS Error: No address associated with hostname, errno = 7)
```
So, Precondition may be changed to: **No network connection/Server is down**

There is missing error handling for this case. Will handle this case ASAP.

**Comment by huynguyennovem** [comment]
Hi @BenoitTallandier, @BastiaanVanGaalen,
By there is no design for this case, I propose it will be like my mockup:

<img src="https://user-images.githubusercontent.com/29337364/155484866-e2ad0be9-6bc2-4d9f-88fe-aa262645988f.jpeg" width="360"/>

From this mockup:
- This screen will be shown when has no connection or server is down
- When user clicks on `Retry` button: Retry fetch all things again
- When user clicks on `Get back later` button: Quit app
- `Contact technical support`:  I prefer having this but currently we have two options, let's consider to select one:
    
    - We have `Customer support` menu from user settings, it will redirects to url: [https://go.crisp.chat/...](https://go.crisp.chat/...) but we're adding `user_email` as a parameter for current implementation. A good thing that we can ignore `user_email` in the url, then it will look like this:

        <img src="https://user-images.githubusercontent.com/29337364/155486205-65de549f-82b3-422f-8e8c-66def7607a98.png" width="360"/>

    - We also have a `Customer support` option when user signup failed ([design](https://zpl.io/bzOyrNX)) but it is depended on `Server Info` API. In case server is down, it will be impossible (Actually even when service is up, the current support url is `false`, not a url).

Pls give your opinion about this!

**Comment by BenoitTallandier** [comment]
Hi @huynguyennovem 
I love that. I would just remove the button "go back latter".
Let me create the design task for Dmitry and we are ready to go :)

**Comment by huynguyennovem** [comment]
After discuss again with @BenoitTallandier, I will skip this new screen for now by:
- New screen (above) may be used in specific stories later, but not now in this issue. 
- We prefer showing local/cached data when there is no network connection. But the offline mode is not really good at the moment, it may show loading indicator when offline, such as this picture:

<img src="https://user-images.githubusercontent.com/29337364/155695617-a6a6dad1-a7d4-44c1-a1d9-f97787dcfbf9.png" width="360"/>

We will try to improve offline mode later. But for now, we will fix to pass this issue first, in order to user can open the app instead of only see the splash screen.
