### ISSUE TITLE
Workspace > The invited email textbox cannot display in a small screensize

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1030]
# Precondition
Using a phone with a small screen size
Login as a Company Owner/ Admin

# Actual Result
Adding a member while creating a workspace, when the keyboard is opened, the email textbox cannot display 
https://user-images.githubusercontent.com/69950655/138661346-6815e021-aa65-48d1-8b68-cb5a6db83320.mp4

# Expected Result
The workspace name textbox should be slid up a little to display the email list

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
- QA Environment

**Comment by tlle14** [comment]
Hi @EvGen94 
Retest failed!
There is a too narrow area to display the email textbox. 
Please make a scroll for a whole screen

**Comment by EvGen94** [comment]
https://images.zenhubusercontent.com/309637937/79347f8f-a1d0-495d-a035-843d75f17ba6/bandicam_2021_11_30_18_00_30_171_trim.mp4
Made a full screen scrollable as asked

**Comment by tlle14** [comment]
Thanks,
Retest pass!

https://user-images.githubusercontent.com/69950655/146871787-9f23d796-c300-4751-893a-eac9333c4785.mp4
