### ISSUE TITLE
Group chat > Chat screen UI issues

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1039]
#1. The back button and the group name are not center-aligned
 => They should be center-aligned
![image](https://user-images.githubusercontent.com/69950655/138843559-57b2c30d-20c4-48ea-b30f-3346fd845814.png)

#2. The avatar of a group is not correct
The avatar of a group is displaying only 2 people, sometimes it's only one. It makes a group looks like a direct chat.
=> It should display at least 3 avatars as in the design. 
![image](https://user-images.githubusercontent.com/69950655/138840750-e4647a12-6be8-4cd9-b468-d842725bc9ef.png)

# Environment
- Build version: 1.0.1
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
After discussion here with @EvGen94: https://github.com/linagora/Twake-Mobile/pull/1078#issuecomment-972749987. 
I'm going to keep the display of avatars's group as 2 maximum. Pls see the demo here (https://github.com/linagora/Twake-Mobile/pull/1078#issuecomment-972763935) and confirm it @tlle14

**Comment by EvGen94** [comment]
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/6170422eb57d0fa132d10cd2
The new design is here, for this you can open a new ticket, Dima @BastiaanVanGaalen also asks that the avatar with photo always should be on top of the avatar with a text

**Comment by tlle14** [comment]
Thanks, retest pass! 
![image](https://user-images.githubusercontent.com/69950655/146725101-a691c0d5-224c-4bb0-bfaf-3c9f40f8c12a.png)
