### ISSUE TITLE
[Story] Invite user by email

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1051]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a user
When I look to invite someone by email
And I click on "invite users"
And I click on "Enter an email"
Then I have the popup asking for emails
Then I click on validate
```

## Business case
When I click "invite by email", I can enter emails in order to invite people. I use the basic email invitation used on Twake. I don't send manually the email, Twake we'll do it for me.
It should follow the web process
https://user-images.githubusercontent.com/22451567/140384190-ac11e998-257a-4c1b-8470-38948fa421c7.mov

## TODO 
Design

**Comment by tlle14** [comment]
@BenoitTallandier please confirm if we should validate emails in the list. 
As I see, Twake Web doesn't validate the emails, it skips the invalids.
And on Mobile, we are applying the validate emails function, but it only displays a red icon without any detailed errors.
