### ISSUE TITLE
Guest> It displays all workspace members for a Guest

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1054]
# Precondition
Login as a guest user 
The Guest is invited to a workspace and has not been added to a channel yet

# Actual Result
When open the create chat screen, it displays all workspace members in the Direct chats list
https://user-images.githubusercontent.com/69950655/140498182-d778b95d-d255-434d-b528-881406e98815.mp4

# Expected Result
It should display users in the same channel/group chat with a guest.
Please check the comment: https://github.com/linagora/Twake/issues/1083#issuecomment-866073156

# Need to confirm
Will it display people in the same group chat with a guest?
Is the guest able to create a group chat?

# Environment
- Build version: 3.0.8
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inches
iPhone 12 - iOS 15.0.2 - 6.1 inches
- QA environment

**Comment by tlle14** [comment]
Hi @BenoitTallandier Kindly check the "Need to confirm" section.

**Comment by BenoitTallandier** [comment]
1. If we can do it, it could be cool! If not, just show some intern people in the company
2. Guest is able to talk and create group chat with internal people.
