### ISSUE TITLE
Language selector feature

### ISSUE THREAD

**Issue by EvGen94** [linagora/Twake-Mobile#1083]
**Providing to user with the ability to change the language in the application** 

**Design links**
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/618be57a12ff5bb918e1c34a
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/6171145496fe0d94f4521ff5
![image.png](https://images.zenhubusercontent.com/607dfac6010943855d82cb82/b93df371-36db-43ea-a374-9c8bfadfd689)

![image.png](https://images.zenhubusercontent.com/607dfac6010943855d82cb82/755e2a34-6daa-4757-8803-bb03f2b2f718)

The following languages are currently available and translated using Weblate [english;spanish;russian;german;italian;finnish;french;]

By default, the device language is selected if it is in the list of translated languages, if the device language is not in the list of translated languages then English is selected, if the user made the choice of the language in the application settings from the available ones, then this language will always be selected and not the system language of the devices.

**Comment by tlle14** [comment]
Hello @EvGen94 
I see our supported language list is not the same as the list on Console. 
I think we should support the same languages in the system. 
@BenoitTallandier Hello, could you please confirm the supported language list in the app? 

Console: 
![screenshot_131](https://user-images.githubusercontent.com/69950655/143847792-fd896f5a-b5ea-43a6-aab8-0fdf42bae382.png)

**Comment by EvGen94** [comment]
Hello! @tlle14 
The list of translated languages in the mobile application depends on how many languages are translated through the Weblate https://hosted.weblate.org/projects/linagora/twake-mobile/ and it is in no way we can change language in console from mobile application there is no API for that. Languages are translated by contributors on each platform in their own way, regardless of each other, so they will be different if we do not hire special translators, by the way, you can translate Vietnamese in our application :)

**Comment by tlle14** [comment]
Thank @EvGen94 for your answer.
I will close this issue since the feature is implemented. 
By the way, the language list should be consistent between Web-Mobile-Console or not, we need a confirmation from the PO and BA. 
I will raise this issue in the test report.
