### ISSUE TITLE
Magic Link/Manage > There is no confirmation popup when regenerating the magic link

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1090]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1023

# Actual Result
When regenerating the magic link, it works without a popup confirmation
https://user-images.githubusercontent.com/69950655/142581594-d67d4da6-c6a7-4eeb-80c8-0f80eda55427.mp4

# Expected Result
When pressing the button "Generate the new link", it should have a confirmation pop-up acknowledging that the old link will be expired as described in the story.
![image](https://user-images.githubusercontent.com/69950655/142581718-1972dbc8-b4ea-4168-b132-a2b9ce4ace2d.png)

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
There is no UI for this dialog. @BastiaanVanGaalen pls help to design it.

**Comment by huynguyennovem** [comment]
Hi @BastiaanVanGaalen, I just add a confirmation dialog by myself, like this:
<img src="https://user-images.githubusercontent.com/29337364/154027333-0c91ece9-bbb9-4774-8c64-dd2d41c30ddf.png" width="360"/>

Is this ok?
