### ISSUE TITLE
Magic Link/Manage > Using different terms for the same object

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1093]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1023
- Design: https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/6170423d686d4793859f8f62

# Actual Result
On the app, we are using 3 different words to describe a link:
- Invitation link
- Magic link
- Sharable link

![image](https://user-images.githubusercontent.com/69950655/142597756-a5d99a63-cd78-49c7-ae0b-12931c85bc84.png)
![image](https://user-images.githubusercontent.com/69950655/142597848-86d42799-5684-4393-a409-977e591748bb.png)

# Expected Result
Should use only one word to describe the invitation link. And using the constant term with the web.

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by huynguyennovem** [comment]
@BastiaanVanGaalen pls help to update the design then I can fix this.

**Comment by BastiaanVanGalen** [comment]
@huynguyennovem Invite link
