### ISSUE TITLE
Guest > Sync failed when adding a new guest to the company 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1096]
# Precondition
- Creating a new Guest
- The new Guest does not belong to any workspace yet

# Actual Result
When the Guest login to Mobile App, it displays a failed sync screen
https://user-images.githubusercontent.com/69950655/142800448-141bed00-c729-47a4-a854-cfff684ba88d.mp4

# Expected Result
It shouldn't display only a failed screen without any reason. 
Please work with BA and the Designer to make a feature for this edge case. 

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

# Todo 
BA & Design welcome screen

**Comment by BenoitTallandier** [comment]
@EvGen94 when I log in as a guest being in no workspace, I have this message.
Do we have an error message somewhere saying "wait to be invited inside a workspace"? If not, I'll ask to Dima to work on it :)
