### ISSUE TITLE
Magic Link/Manage> Unable to generate a Magic Link for some workspaces

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1100]
# Precondition
The workspace is an old data

# Actual Result
When opening the "Invite to workspace" screen, the magic link field is empty
https://user-images.githubusercontent.com/69950655/142840715-7e3525d8-7070-496c-9082-2dcc53d1eaed.mp4

Log:
![image](https://user-images.githubusercontent.com/69950655/142842252-f24cdd01-f725-4edd-9961-29471ba27f74.png)

Response:
```{"statusCode":403,"error":"Forbidden","message":"Only workspace members can perform this action"}```

# Expected Result
Please investigate.
It may be a lacking case or incorrect test data since the workspace has been created a long time ago

# Environment
 - Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
FYI: 
- Account: cyan@yopmail.com
- Step by step: 
    - **Bug** in workspace: Go to company "Crayon Company" > workspace "0209 Workspace"
    - **Worked** in workspace: Go to company "Crayon Company" > workspace "Guest"
- Data sample:

```
{
    "id": "b265e610-0adf-11ec-830b-f13b25f75bc2",
    "company_id": "af76efe0-f59e-11eb-8210-0242ac120002",
    "name": "0209 Workspace",
    "logo": "",
    "default": false,
    "archived": false,
    "stats": {
        "created_at": 1630471642860,
        "total_members": 0
    },
    "role": "moderator"
},

 {
    "id": "fe07dd50-1aaf-11ec-96d9-038f6b2dbc07",
    "company_id": "af76efe0-f59e-11eb-8210-0242ac120002",
    "name": "Guest",
    "logo": "",
    "default": false,
    "archived": false,
    "stats": {
        "created_at": 1632210372515,
        "total_members": 1
    },
    "role": "moderator"
},
```

Note: It seems this bug is only occurs for workspaces that has "total_members" = 0

**Comment by huynguyennovem** [comment]
Retest with Account: [cyan@yopmail.com](mailto:cyan@yopmail.com) -> **Success** (Magic link is generated for both `0209 Workspace` and `Guest` workspace

https://user-images.githubusercontent.com/29337364/154003221-36cd1e3f-d6dd-4561-89bf-7ca3e2d6612a.mp4
