### ISSUE TITLE
Magic Link/Manage > Sharing the magic link via email has a meager content

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1101]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1023

# Actual Result
When sharing the link by email, it opens the composer with the subject is a magic link 
https://user-images.githubusercontent.com/69950655/142819942-9e09ab73-f1d1-4af0-81ed-6ceb7b266b9f.mp4

# Expected Result
Please design suitable sharing content, especially for sharing the magic link via email

# Environment
- Build version: 3.0.9
- Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by BenoitTallandier** [comment]
The email subject should be "Join me on Twake"
