### ISSUE TITLE
Invite by email > There is no acknowledgement email sending to the invitee when he is added to the workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1106]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1051
- UserA is a WORKSPACE MODERATOR (petit@yopmail.com)
- UserB is a COMPANY MEMBER created by the company owner. 
- ![image](https://user-images.githubusercontent.com/69950655/142968292-865be307-bf74-422b-a0e8-e6f49c05b8a5.png)
But hasn't been in the workspace yet
![image](https://user-images.githubusercontent.com/69950655/142968359-aedda79e-91bd-466e-9174-02538983e3f6.png)

# Actual Result
When UserA adds the UserB via "Invite by email", UserB doesn't have an acknowledgment email informed he is added to the workspace.

https://user-images.githubusercontent.com/69950655/142969578-6e397d2e-0a2d-48cb-833c-775f8f27bced.mp4

Note: the email in the video is the invite to Company email. 

# Expected Result
It should have an acknowledgement email when inviting the user to a workspace

# Environment

- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
This may relate to backend issue. Pls take a look on this @RomaricMourgues

**Comment by RomaricMourgues** [comment]
When someone is invited to a workspace but already in the company then no email is sent. It is not planned on our roadmap yet.

**Comment by tlle14** [comment]
Thank @RomaricMourgues for the confirmation. So this is not a valid issue.
