### ISSUE TITLE
Invite by email > Cannot process the invited by email when the number of user in company reaches limitation

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1109]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1051
- The current company is in a paid plan, the number of users in the Company reaches the limit (2 users)
![image](https://user-images.githubusercontent.com/69950655/143197042-b7124b2f-665a-4a67-8088-834ef3f50536.png)
![image](https://user-images.githubusercontent.com/69950655/143197117-dae07f8d-3ff0-4b5d-8b37-5563e6018d47.png)

# Actual Result
When invited by email on Mobile, it cannot process and doesn't give any error message
https://user-images.githubusercontent.com/69950655/143198645-0526e590-297b-4d55-9ceb-1118de0b1118.mp4

# Expected Result
It should show an error message when cannot invite more people by email when the company payment plan reaches the limit

# Environment

- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
This bug occurs on Twake web too. So I think it related to backend-side. 

https://user-images.githubusercontent.com/29337364/143574050-848f7317-0a14-4a7e-a911-ad2c72150b27.mp4

@romanesko @RomaricMourgues : Can you guys take a look on this?
