### ISSUE TITLE
Invite by email > UI issues

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1110]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1051
- Design: https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/617042424daa9ea2b4c314b2
Tapping on the button "Invite by email'
Verify Invite screen & success screen

# 1. [Both] The gray line is placed at the incorrect position
The gray line is sticking to the upper border of the email text field 
=> It should be placed at the lower border of the screen header (as in the design). And update the SUCCESS screen also
![image](https://user-images.githubusercontent.com/69950655/143373830-3681ab02-8621-415d-8ed7-3a220c4f273d.png)
 

# 2. [iOS] It has a white footer on the inviting screen
There is a white footer on the inviting screen, which doesn't appear on the design.
=> Please remove the unexpected element. And update the SUCCESS screen also. 
![image](https://user-images.githubusercontent.com/69950655/143374849-123ffa5b-eeb3-48e7-b2e7-3ec5e3d80083.png)

# 3. [Both] The success screen heading text has left alignment
=> It should be center-aligned as in the design
![image](https://user-images.githubusercontent.com/69950655/143397179-ab4f5c7b-397c-4527-b6da-830fba7e8c0c.png)

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
**4. [Both] Add bug fixes for top corner radius:**
- Current: No corner radius
- Expected: Have corner radius

<img width="444" alt="Screen Shot 2021-11-26 at 3 40 13 PM" src="https://user-images.githubusercontent.com/29337364/143551916-a02f8995-0e89-46a6-a5ce-59b5ec0e9405.png">

**Comment by tlle14** [comment]
Thank @huynguyennovem for the bug reporting #4

*Pass*
Issue #1, #3, #4: Retest pass!

*Fail*
Issue #2. I don't see the fix

**Comment by tlle14** [comment]
Issue #2 is passed! 
![image](https://user-images.githubusercontent.com/69950655/150895359-ec499266-238b-4a3d-97f7-8bf39a9faba8.png)
