### ISSUE TITLE
Language Selector > The language name is not capitalized in the list while displaying in some other languages

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1116]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1083
- Switching to Italian, Finnish, French

# Actual Result
Some language's name in the list is not capitalized in the selection list

**Italian:**
![image](https://user-images.githubusercontent.com/69950655/143843713-7a4c6bdc-76a1-4316-bf88-2ab1d2d11ec4.png)

**Finnish**
![image](https://user-images.githubusercontent.com/69950655/143843606-3af73d2a-6d9c-4134-841c-50075903e41b.png)

**French**
![image](https://user-images.githubusercontent.com/69950655/143843499-ff8d88b7-8445-4196-b7e4-6e5dcc86e4f1.png)

# Expected Result 
The Language's name should always be capitalized

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by EvGen94** [comment]
@tlle14  Done

**Comment by tlle14** [comment]
Thankssssss,
retest pass!!!!!

https://user-images.githubusercontent.com/69950655/151487293-00ac1748-15d9-46d4-bc1d-5e12854d7f1d.mp4
