### ISSUE TITLE
Translation > After being translated, the text broke the layout 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1123]
# Precondition
- May relate to: https://github.com/linagora/Twake-Mobile/issues/1083
- Switch to French

# Actual Result
The button name is too long that overflowing the menu sidebar
![image](https://user-images.githubusercontent.com/69950655/144007620-5752282c-3752-4ba4-af10-b8fb9861eefe.png)

# Expected Result
Please ask the content team to shorten the button name

# Environment
Build version: 3.0.9
Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
QA environment

**Comment by tlle14** [comment]
https://hosted.weblate.org/translate/linagora/twake-mobile/fr/?checksum=d064d21da52cb1de&sort_by=-priority,position
Please help to update the translation

**Comment by RomaricMourgues** [comment]
"Inviter dans cet espace" will be understandable with the icon

**Comment by tlle14** [comment]
Thank @RomaricMourgues 
I updated the translation text as your suggestion.

**Comment by tlle14** [comment]
Thanks, Retest pass!

https://user-images.githubusercontent.com/69950655/150768362-0f742b81-ede8-42f6-a98b-d3af393ea577.mp4
