### ISSUE TITLE
Translation > Sign In screen is not have the same language with the mobile app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1124]
# Precondition
- May relate to: https://github.com/linagora/Twake-Mobile/issues/1083
- The phone language is French. So the App language is French by default.

# Actual Result
When going to sign-in on the app, the Sign In screen is still English (the default language)
https://user-images.githubusercontent.com/69950655/144010550-d34b8d50-f494-457b-a3c0-9641fcf0a326.mp4

# Expected Result
- When opening the sign-in screen, the language on sign-in screen should be set to the language on App. In this case, it should be French.
- Please fix the same behavior when opening the privacy and terms screen

*This may be an improvement from the Console side. Please contact the team to solve the ticket.

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

## Todo
Find a way to set the language of the webview

**Comment by BenoitTallandier** [comment]
@tuanlc can we give the language in the url as parameter when we call the signin / signup page ?

**Comment by tuanlc** [comment]
Hey @BenoitTallandier 

It is possible to implement but for now, we don't support it yet. If you want, please create a request to SaaS Console:
https://gitlab.com/COMPANY_LINAGORA/software/saas/twake-console-web/-/issues

Please describe scenario, your expectation.

**Comment by BenoitTallandier** [comment]
Ok, I created it. It's here https://gitlab.com/COMPANY_LINAGORA/software/saas/twake-console-web/-/issues/161
