### ISSUE TITLE
Language selector > After logging in again, the app language always change to the Device language

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1126]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1083
- Setting Device language is French
- Setting the Account language is Italian

# Actual Result
After logging in again, the App language is set to the Device language
In this case, it changes from Italian to French

https://user-images.githubusercontent.com/69950655/144024480-d2038bdb-42a2-4139-a512-f4ae5168a6ac.mp4

# Expected Result
If the Account language is set, after re-logging in, the App language should always display in the configured Account language instead of the Device language

The Account configured language should be applied on Twake Web and Console

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by EvGen94** [comment]
@tlle14 Hi!
"The Account configured language should be applied on Twake Web and Console" now we can't do this because we don't have API for that, language in app is separated from Web, later it will be integrated but for now not 
About this bug, I fixed it now when you logout language settings are not lost

**Comment by tlle14** [comment]
Thank @EvGen94 
I will inform the language issue with other teams as an improvement

**Comment by tlle14** [comment]
Thanks,
Retest pass!

https://user-images.githubusercontent.com/69950655/146731413-1becaee8-0cad-4bf6-a18b-7ab31d39e1e8.mp4
