### ISSUE TITLE
[Chat screen] Screen is reloaded whenever user interacting with message

### ISSUE THREAD

**Issue by huynguyennovem** [linagora/Twake-Mobile#1132]
### Actual result:
Whenever user react/add message/delete message... to message, screen is reloaded.
This is clearly shown with message with file.

https://images.zenhubusercontent.com/309637937/a84a424b-25f3-40c7-9cc3-aada0dfdcae5/err.mov

### Expected Result:

User can interact with chat screen without seeing reload effect clearly.

### Environment:
Android + iOS

**Comment by tlle14** [comment]
Thanks, retest pass!

https://user-images.githubusercontent.com/69950655/150900249-d34a3ddc-07e8-4447-b2c3-ef453ebd6027.mp4
