### ISSUE TITLE
Thread > Some messages is lost while people is chatting in a thread

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1133]
# Precondition
- 3 people are chatting in a thread of a group chat
- The internet connection may not stable
# Actual Result
There always has a person who lost the message in the thread. 

- A person who lost messages
![image](https://user-images.githubusercontent.com/69950655/144581507-3e86389f-71c8-4378-9fff-0c5e127be653.png)

- Other participants
![image](https://user-images.githubusercontent.com/69950655/144581564-d81be81c-3ca4-43b8-b3fd-dd67680b30d5.png)
![image](https://user-images.githubusercontent.com/69950655/144581651-78b7b32a-b5f5-44f3-9e87-75a1c95e65d1.png)

# Expected Result
Please investigate. 
It should show all messages in a thread for all participants

# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
iPhone 7- iOS 13.3.1 - 4.7 inch
- Server: QA environment

**Comment by EvGen94** [comment]
Now should be ok
