### ISSUE TITLE
[Chat screen] Sender text color inside file is hard to see

### ISSUE THREAD

**Issue by huynguyennovem** [linagora/Twake-Mobile#1135]
### Actual result:
The color of sender text inside file block is hard to see

![image.png](https://images.zenhubusercontent.com/605175c4593ffb54122f0753/e4f6195c-e893-4ba2-b514-398c663492ce)

### Expected Result:
Change text color to darker color 

### Environment:
Android + iOS

**Comment by tlle14** [comment]
Thanks, 
Retest pass
![image](https://user-images.githubusercontent.com/69950655/150905728-6442e51d-2ce5-4048-ad28-ee3ad3fa35de.png)
