### ISSUE TITLE
Magic Link/Receive > It displays the link is invalid when the server is not set.

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1145]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1022
- The link is valid
- The App is installed
- The User is not logged in yet
- The server is the default (web.twake.app)

# Actual Result
When opening the Magic Link, which is from the QA server, it opens the App but displays an invalid link screen. 
https://user-images.githubusercontent.com/69950655/146339137-1be29c3c-5e5d-48ff-8cb8-7478898de7bc.mp4

# Expected Result
Please find the appropriate solution for this case. 
In fact, the link is not invalid. It is because we didn't configure the server address on Twake App to be the same as the server of Magic Link. That's why the link becomes invalid on the current App. 
But we cannot ask the user to configure the Server Address before she/he clicks the link.

# Environment
- Build version: 3.0.10
- Device:
iPhone XR - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hello @RomaricMourgues @huynguyennovem please check this issue.

**Comment by RomaricMourgues** [comment]
I can't do much, can you extract the server from the url ? @huynguyennovem

**Comment by huynguyennovem** [comment]
Hi @RomaricMourgues, @tlle14:
I think this is a complicated test case at the moment.
- Let's say I can extract the host/server from the url, and then change the current host of the application. But what happens after that?
-> We may need to force user to logout and login again with new host/server from url -> Is this a good behavior for users? And we also need to inform the user that the url they are clicking on corresponds to which host/server.

Anyway, we need a user story and design for this. So, need an idea from @BenoitTallandier for this.

**Comment by BenoitTallandier** [comment]
@huynguyennovem here the story : #1155 
Because it shouldn't happen often, we can build this simple version and improve it after :)

**Comment by tlle14** [comment]
hi @huynguyennovem 
Retest failed!

- When the user has already logged in, he isn't forced to log out. 

https://user-images.githubusercontent.com/69950655/151141374-edd7a26b-8138-48e3-a293-d7e7a5d2a844.mp4

- When the user is not logged in yet, tapping on the magic link of a different server, nothing happens. @BenoitTallandier could you please define the behavior for this case?

https://user-images.githubusercontent.com/69950655/151146205-5ee87be8-f701-4c2b-bfca-3092ccf58f59.mp4

**Comment by BenoitTallandier** [comment]
If the user is not Logged in :
- We set the server value required in the link (this shouldn't be shown to the user)
- We redirect the user to the login page.
