### ISSUE TITLE
Magic Link/Receive > There has no way for user to exit or cancel the invitation on screens.

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1146]
# Precondition 
- Story: https://github.com/linagora/Twake-Mobile/issues/1022
- Design:
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/618c51df62a648b3b5c48abf
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/618c51e0cce8c7b4f3af19c9

# Actual Result
The Join Workspace screen and Invalid Link screen don't have a button for users to cancel joining or exit when the link becomes invalid. 
To exit from those screens, the user need to restart the app. 
![image](https://user-images.githubusercontent.com/69950655/146352114-fc83ffe9-a844-4284-9871-5bc2d45810ad.png)
![image](https://user-images.githubusercontent.com/69950655/146352188-bc3a22a0-14b8-4468-bf2d-b000f953dfd0.png)

# Expected Result
It would be nice if those screens has a Cancel button or a Back button.

# Environment
- Build version: 3.0.10
- Device:
iPhone XR - iOS 14.4 - 6.46 inch
- QA environment

## TODO
BTA : having the desing

**Comment by tlle14** [comment]
Hi @BenoitTallandier please confirm if we should have this improvement. 
If yes, kindly describe the behavior of those new buttons. 
If not, we can close this ticket. 

Thanks!

**Comment by BenoitTallandier** [comment]
Yes, we'll have it. I updated the user story.
The design will be done. Here the [ticket](https://ci.linagora.com/linagora/lgs/design/-/issues/84)
