### ISSUE TITLE
Magic Link/Receive > It creates a company when creating account to join the workspace by Magic Link

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1148]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1022
- The user is not a member of Twake
- The Magic link is valid
- The App is installed already

# Actual result
When opening the magic link, if the user creates an account to join the workspace, it also creates a company for the new user
https://user-images.githubusercontent.com/69950655/146480528-1f4f9db3-99b5-4c91-a026-773198520ead.mp4

# Expected Result
It shouldn't create a company when the user creates an account via Magic Link

# Environment
- Build version: 3.0.10
- Device:
iPhone XR - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
This issue may from the implementation way on Mobile, or may be the backend issue. 
@huynguyennovem kindly confirm and assign to backend team if needed. Thank you.

**Comment by huynguyennovem** [comment]
https://user-images.githubusercontent.com/29337364/148159953-c0b68d7b-cddc-418d-86a7-76e457dece9e.mp4

Hi @tlle14, as I checked, the signup API hasn't worked in this case (although already added parameter `createAccountOnly: true`) 

Need help from BE team: cc @RomaricMourgues

**Comment by RomaricMourgues** [comment]
Hey, as I understand this is an issue from Console right ? I notice them

**Comment by RomaricMourgues** [comment]
Created here: https://gitlab.com/COMPANY_LINAGORA/software/saas/twake-console-account/-/issues/39

**Comment by RomaricMourgues** [comment]
On web we redirect the user to https://auth.twake.app/?invite=1 then when we click on signup we get to https://console.twake.app/signup?create_account_only=true but I don't know what parameter must be in the API call

**Comment by tuanlc** [comment]
Hello,

The `createAccountOnly` is request query but not  in the request body. Some thing like this:

 https://console.twake.app/signup?create_account_only=true

**Comment by RomaricMourgues** [comment]
Is it working also when using the /api/signup endpoint ?

**Comment by RomaricMourgues** [comment]
Great thanks ! @tlle14 you got your answer :)

**Comment by tuanlc** [comment]
> Created here: https://gitlab.com/COMPANY_LINAGORA/software/saas/twake-console-account/-/issues/39

Always my pleasure! Please close the ticket ;)

**Comment by huynguyennovem** [comment]
Hi @BenoitTallandier and @BastiaanVanGaalen:
Related to this issue, there will be a screen that notice user that they are not belong to any company on Web (let's watch my recorded video). **But there is no same screen/story on mobile currently.**
So, let's consider about this again pls. 
- Should we auto create a default Company for new user again? If not, pls help to create a corresponding story/design on mobile.


https://user-images.githubusercontent.com/29337364/153855337-455235e1-6fdc-453d-874b-9016e49bb7fa.mp4

**Comment by BenoitTallandier** [comment]
Hi @huynguyennovem You're right. We should have a page saying that I have to create a company. 
Here the user story : https://github.com/linagora/Twake-Mobile/issues/1276
