### ISSUE TITLE
Magic Link/Receive > It got error when the user of other company joins a workspace via Magic Link

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1149]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1022
- The App is installed
- The user has been logged in to Company A. The user doesn't join Company B
- The magic link is valid and belongs to a workspace of Company B

# Actual Result
When the user clicks on the Magic Link, it is able to join the workspace of Company B. However, the sidebar menu is still displaying Company A. 
After restarting the App, the sidebar has an error and keeps loading.

https://user-images.githubusercontent.com/69950655/146516308-63266aeb-6c78-4ad9-a67d-da9f93ed2d8b.mp4

# Expected Result
When joining a workspace of another company by Magic Link, the user should be added to the new company. 
The new company and workspace should be displayed on the sidebar menu

# Environment
- Build version: 3.0.10
- Device:
iPhone XR - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
As I checked, after joining, the user is not added to that company, but only added to the workspace (the Web got the same error). Could you pls double check on this?@RomaricMourgues, @romanesko

**Comment by RomaricMourgues** [comment]
Is it possible that there is some kind of company user number limitation happening ?

**Comment by tlle14** [comment]
No, it's not @RomaricMourgues 
Do you think a user cannot join 2 companies in a Free Plan?

In this case, the user is a newly created account who is in Free Plan (Company A).
Company B is an Annual Paid Account that has 100 members in limitation.
