### ISSUE TITLE
Magic Link/Receive > When clicking on "Create your company" on error screen, it redirects to the Sign In screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1151]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1022
- The App is installed
- The user is not a Twake member
- The link is revoked

# Actual Result
When clicking on the Magic Link, it opens the app and displays error screen
When tapping on "Create your company" button, it redirects to Sign In screen on the browser

# Expected Result
It should open Sign Up screen on the App instead

# Environment
- Build version: 3.0.10
- Device:
iPhone XR - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
Hi @tlle14, as the confirmation from [here](https://github.com/linagora/Twake-Mobile/issues/1022#issuecomment-977673434), in this case, it will redirect to Console page on the browser. Pls help to confirm again.

**Comment by tlle14** [comment]
Thank @huynguyennovem for pointing out the conflict. 
I assume the behavior like this:
- Precondition: The App is installed
- Behavior: Clicking on "Create a company" on the error page
+ If the user is logged in: Opening console page on the browser (as in the [comment](https://github.com/linagora/Twake-Mobile/issues/1022#issuecomment-977673434) )
+ If the user is not logged in: Opening Sign Up page on App

I still need the review from @BenoitTallandier.

**Comment by BenoitTallandier** [comment]
Hi @tlle14 
I agree with what you said. User should be redirected in the signup page. 👍

**Comment by tlle14** [comment]
Thanks, retest pass! 
- When the user is logged in, it redirects to the console page on the default browse34 
https://user-images.githubusercontent.com/69950655/151513312-870b4363-8cd6-4d03-8568-4c8c175aa6bd.mp4

- When the user has not logged in yet, it redirects to the Welcome screen on App. 
https://user-images.githubusercontent.com/69950655/151515131-5395a334-9bdf-475b-8c65-44d1efa32ffe.mp4

**Comment by tlle14** [comment]
May I ask for a back button or close button? 
- When the user is logged in, tapping on "Back" button will redirect to the previous screen
- When the user is not logged in, tapping on "Back" button will open the Welcome screen. 

For example: 
![image](https://user-images.githubusercontent.com/69950655/151516712-2ffa9903-d226-4ea0-a041-84df5a4c5a80.png)

@BenoitTallandier if you think it's okay, please create a new ticket.

**Comment by BenoitTallandier** [comment]
I agree on that for logged in user here the ticket : https://github.com/linagora/Twake-Mobile/issues/1252
