### ISSUE TITLE
Fallback to "text" fields instead of "block" field if "block" not defined.

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake-Mobile#1152]
For the next version we will continue to provide the "block" content with this format: 

```
{
  text: "hi **there**",
  blocks: [{type: twacode, elements: ["hi **there**"]}]
}
```

But in the next versions you must be able to fallback to the text field (that will be always defined) in case nothing is provided in the "blocks" field.

**Comment by tlle14** [comment]
Hello @RomaricMourgues is this an issue or a task?

**Comment by RomaricMourgues** [comment]
This is a task to make sure you are still inline with the API in the future.
