### ISSUE TITLE
[Story] Dark mode

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1153]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am not a Twake user 
When I want to change the theme of the mobile application
Then I open my settings
And I click on "Theme"
And I select the theme I want (Light, Dark, System)
```

## Flow

![Group 52](https://user-images.githubusercontent.com/22451567/146751630-31ceb038-5ab6-4b11-8c37-44f7e4d1a2ae.png)

## Business case
- The default theme is `System`.
- If mobile system can't provide the current theme, Twake use the light theme

## Criteria
- [ ] When I am in the dark theme, and I click on the button "light", then the interface becomes light.
- [ ] When I am in the light theme, and I click on the button "dark", then the interface becomes dark.
 
## UI UX Design
WIP : https://ci.linagora.com/linagora/lgs/design/-/issues/87

**Comment by tlle14** [comment]
The developer team is implementing this feature, but the Theme icon is not appropriate. 
Hello @BastiaanVanGaalen could you please provide the Theme icon? 

CC: @EvGen94

**Comment by BastiaanVanGaalen** [comment]
@tlle14 https://zpl.io/aXp1GlX
