### ISSUE TITLE
[Story] receive magic link from an other server

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1155]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a Twake user
And I host my own Twake instance on twake.benoit.best
And I configured the mobile app to work with this instance
When I want to join a workspace through a magic link that is hosted in an other instance (web.twake.app for ex)
Then I open the link
And I am logged out
And the application url configuration is set to the url from the link (web.twake.app in this case)
And I am follow the process as a disconnected user
```

## UI UX Design
![Group 58](https://user-images.githubusercontent.com/22451567/146778551-5c66569d-9a91-433a-a9c6-915e37b24cd8.png)

## Notes
This comes from #1145

**Comment by tlle14** [comment]
Thank @BenoitTallandier 
I think we should have a dialog informing the user he will be logout from this current account instead of forcing him to logout.

**Comment by BenoitTallandier** [comment]
@tlle14 
True, I update the story :)
