### ISSUE TITLE
Uploading> It is able to submit the message before the file is loaded

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1157]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1137
- File uploading version 1

# Actual Result 
When the file is not uploaded successfully, it is able to send a message. 
The sent message is empty.
https://user-images.githubusercontent.com/69950655/146892871-7fa1f067-5482-4df5-a00c-8ce20829cbbb.mp4

# Expected Result
The send button should be disabled when the file is in the progress of uploading

# Environment
- Build version: 3.0.10
- Device:
iPhone 11 Promax - iOS 14.4 - 6.06 inches
- QA environment and Prod

**Comment by huynguyennovem** [comment]
This bug will not occur on version 2. Pls w8 the next release or can watch the demo here:

https://user-images.githubusercontent.com/29337364/147558253-037826b5-7ec0-4136-884e-bd72b7a55bb5.mp4

**Comment by tlle14** [comment]
Thanks, but retest is failed.
When having an uploaded file, the send button is enabled. 
The next uploading file can be failed when it is able to submit while uploading.

https://user-images.githubusercontent.com/69950655/150944040-2c800524-e395-427e-b4b8-20fd011288a2.mp4
