### ISSUE TITLE
Change Server > How to change server configuration for Twake Mobile App 

### ISSUE THREAD

**Issue by anandang76** [linagora/Twake-Mobile#1174]
I have configure twake web application with my server. It's working fine and I am not using auth0 configure in Parameter.php.
How to connect my custom server to twake mobile app. Is it possible? and Is it work with playstore Twake mobile app?  I tried connecting with custom server login page, but its opening in browser but not coming back to flutter application.  Can you please thrown us some hints on the same?  Thanks

Thanks.

**Comment by tlle14** [comment]
Hi @anandang76 On Twake Mobile App, you can configure your own server by clicking on "Change Server". 
Then you can sign in with your custom server. 
Here is the demo:
https://user-images.githubusercontent.com/69950655/149266074-5e4ad451-a825-4443-b27f-0ed0aa156380.mp4

I hope this helps.

**Comment by anandang76** [comment]
Hi @tlle14, First of all thank you for reply,  I deployed Twake 2021.Q1.385 , it's working for fine, But when I connect my server url into change server in mobile application, It's not working application closed automatically.What I need to do for connect web url for mobile application?.

**Comment by anandang76** [comment]
@tlle14 No update?
