### ISSUE TITLE
[Story] Share files by Twake

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1178]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a user
When I look to share a file through Twake
Then I open my document from my mobile
And I click on "share"
And I choose Twake
And I select my company, workspace & channel
And I can add a message
And I click on "send"
```

## Business case
- If the user is not connected, a popup appears saying that the user is to be connected. Clicking on the "ok" button close this popup and the Twake sharing popup. The user comes back to the system sharing popup.
- The default company, workspace, (channel or user) is the one that I last visited on Twake 
- If I change the company where I want to send files, Workspace and channel are updated to workspace and channel in the new selected company
- If I change the workspace where I want to send files channel is updated to one in the new selected company and workspace
- The "to" field can be either a channel or a user inside the workspace
- The "to" field contains a search bar. This will be like the cmd+k of the web version. It will search inside workspace channels, direct discussions, and members of the company.
- When we send several files, each of them will be contained inside a message. The comment will be sent as the last message.
- If we send only images, the label is "Share X images"
- If we don't send only images, the label is "Share X files"
- If we have less than 8 companies, we don't see the "show all" button companies
- If we have less than 8 workspaces in the selected company, we don't see the "show all" button for workspace
- We can scroll horizontally company, workspace, and channel selector
- "TO" selector shows a maximum of 8 entities (direct or channel) 
- When I send files or images, the message input transforms itself into a loading. When it's sent, there is a check to indicate it's done.
- When a user shares a file, we save the location in order to propose when the user wants to share again.

## Flow
![Group 717 (1)](https://user-images.githubusercontent.com/22451567/153430693-b0c96792-1e7b-4689-a06c-ce49f28e570a.png)

## UI UX Design
https://www.figma.com/file/tBwdvsRmUqOKh1Wh6MeC03/Twake?node-id=4574%3A5109

## Related

**Comment by BastiaanVanGalen** [comment]
![IMAGE 2022-01-25 19:13:51](https://user-images.githubusercontent.com/76128935/151015072-246c95c2-4e86-4d2f-bd2f-9c53b1003db7.jpg)
![IMAGE 2022-01-25 19:13:50](https://user-images.githubusercontent.com/76128935/151015084-e086ecad-9482-452a-ac21-f0f47c0656c3.jpg)

@BenoitTallandier I have a question related to the selection of images and files for sharing. Its done natively. You designed 
some screens where you add file/image previews on a special intermediary screen. Are you sure it can be done from the standpoint of implementation? @EvGen94 can you clarify a bit cause i'm a bit confused about implementability of this part of the US.

**Comment by BenoitTallandier** [comment]
The selection is native, the second screen in which you select where you want to send a file is not native : 
On IOS : If you select a file you want to share inside a channel, you click on "share", then you select the application (telegram in that case), and after that you see second screen with the title "Sahre with" that is specific to telegram. If you try to share files inside Discord or wahtsapp, it's always a different screen.

**Comment by BastiaanVanGalen** [comment]
@BenoitTallandier Main screen is done, https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake%2Fdark?node-id=205%3A3546

Listing screens and general tidying up will come later today. Have a nice day.

**Comment by huynguyennovem** [comment]
Hi @BenoitTallandier, I have some comments:

1. > If the user is not connected, a popup appears saying that the user as to be connected. Clicking on the "ok" button close this popup and the Twake sharing popup. User come back to the system sharing popup.

We can not detect login status outside the app. So I suggest to handle this inside the app.
The flow may be like this:

```
S1. Select files to share outside
S2. Choose Twake app
S3. Twake app opened with not connected user (be in loading screen). A popup appears saying that the user as to be connected.
S4. Click "ok" button. Login screen opens then user does login steps.
S5. After logged in, the "Share to Twake" screen appears with selected files.
```

2. > "TO" selector show maximum 8 entity (direct or channel)

    Does it same to Company and Workspace selector?

3. When user click on "Share X files" row, the file list should be vertical list, IMO

4. There is no description about upload status for files, due to some files may heavy and need to wait a while time. So I recommend this:
After user clicked on Send button, open file uploading screen. It may similar to current file uploading screen in chat here: https://zpl.io/bAPvDmo
Need a design for this case, so pls help @BastiaanVanGalen 

cc: @EvGen94

**Comment by huynguyennovem** [comment]
1. 
If user logged in, he can get his companies/workspace/channel...
If user has not logged in, he is required to login first (login screen is here)

Then you will see the conflict from this design when user has not logged in (He still can see his company/workspace/channel..)
![Screen Shot 2022-02-09 at 9 25 15 AM](https://user-images.githubusercontent.com/29337364/153110177-3603fb08-9762-4846-a859-1c0240a6cdfb.png)

**Comment by BenoitTallandier** [comment]
@huynguyennovem I got your point. It's true, so if the user is not logged in, we need to design an empty page behind the error message. I'll ask to Dmitry :)

I updated the story according your feedback 2,3,4 :)

**Comment by BenoitTallandier** [comment]
Here is the new design https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake.new?node-id=620%3A47063
@EvGen94
