### ISSUE TITLE
Uploading file > It display an error message twice when fail to uploading a heavy file 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1186]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1137
- Design: https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/61c5bd417fac1eb9f2997cee
- A PDF file has a file size 156MB

# Actual Result
When uploading a heavy file, it doesn't succeed. On Uploading screen:
- There is no error icon (red icon) displaying for the failed uploading file
- When uploading another file, it again displays an error message twice to warn the failed file 

https://user-images.githubusercontent.com/69950655/149303337-2036ff4e-4ea3-45b7-8501-2dd43991e612.mp4

# Expected Result
- It should display the fail uploading icon as in the design 
- About the fail uploading dialog, it should persist longer in the uploading screen, until the user presses retry or cancel
![image](https://user-images.githubusercontent.com/69950655/149303749-32d1091e-3c08-49a0-a8c5-2ba02916db34.png)

# Environment
- Build version: 3.0.11
- Device:
iPhone 12 - 6.06 inches
- QA environment

**Comment by tlle14** [comment]
Hi @BenoitTallandier Could you please review and confirm the Expected Result?

**Comment by BenoitTallandier** [comment]
Hi @tlle14 
We do not limit file size. We can support any size. We limit only the global storage space of the company.
For other points, I agree. :)

**Comment by tlle14** [comment]
Thanks @BenoitTallandier 
But it seems I cannot upload a heavy file for some technical reason. 
Could you please confirm this case @huynguyennovem ?

**Comment by tlle14** [comment]
I retested and the heavy file is uploaded successfully. It seems to be a connection problem on my side. 
I also updated the Expected Result. 
![image](https://user-images.githubusercontent.com/69950655/149316673-1b796b9b-dcb8-49d3-9c1e-eaf4d0cf5bfd.png)

**Comment by huynguyennovem** [comment]
> About the fail uploading dialog, it should persist longer in the uploading screen, until the user presses retry or cancel

As the common behavior of a snackbar(popup) on mobile app, it should be auto dismiss after a time. So, I propose two options here:

1. Display a dialog instead of snackbar, it can be persistent in there until user interacts to dialog. (I don't like this very much)
2. Keep using snackbar but I will increase the time. So it will be there longer to user can click on Retry button.

**Comment by tlle14** [comment]
Thank @huynguyennovem 
@huynguyennovem @BenoitTallandier how about displaying retry button next to the failed uploading file?

**Comment by tlle14** [comment]
Hi @huynguyennovem 
Retest failed!
The snack bar is staying longer.
But when tapping on the "Retry" button, it displays another snack bar
=> it should retry uploading the file again
https://user-images.githubusercontent.com/69950655/151151595-af0f122c-0da1-4d63-bda0-a2974322fb9d.mp4

**Comment by huynguyennovem** [comment]
@tlle14 :
May be caused by the poor network, let's try with another files pls. 
And you should update the issue's title by you already can uploaded heavy file before

**Comment by tlle14** [comment]
I created a new issue about cannot try again to upload an attachment  on iOS App https://github.com/linagora/Twake-Mobile/issues/1242
