### ISSUE TITLE
Uploading file > The behavior of access permission is incorrect

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1195]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1137
- Refer to: https://developer.android.com/training/permissions/requesting

# 1. The App doesn't ask for access permission
- On íOS, it doesn't ask for access to Gallery, only ask for access to Camera. 
- On Android, it doesn't ask for access to Camera, only ask for access to Gallery

iOS:

https://user-images.githubusercontent.com/69950655/149617469-3554f3e7-c0a4-4dfb-ab41-5cebf2783a2f.mp4

Android: 

https://user-images.githubusercontent.com/69950655/149617480-9834c042-b556-4c1d-a013-9bd4a7bc143d.mp4

**Expected Result**
The App should ask for access permission to both option 
- Access to camera
- Access to Gallery
![image](https://user-images.githubusercontent.com/69950655/149615530-0979b789-a9a2-42be-9d79-78043d01f3c5.png)

# 2. If the user denied accessing to Camera/Gallery, the next time he taps on the button, it doesn't work without showing a rationale to the user.
- On iPhone, it only asks for permission 1 time. If the user denies access, the button doesn't respond when tapping on it.
- On Android, it works fine 

iOS:
https://user-images.githubusercontent.com/69950655/149617690-1b7e55e5-4000-4dcf-8e02-34472cf25948.mp4

Android:
https://user-images.githubusercontent.com/69950655/149617715-e61d4f6d-c802-41dc-bd2e-e3854ef5e5ee.mp4

**Expected Result:**
On iPhone, it should have a dialog to guide the user to change the app permission on Setting.

**Comment by huynguyennovem** [comment]
@tlle14 : Application only should ask user to grant permission once it's required by OS. So I would recommend the behavior like this:
- Android: Ask the access to Gallery permission, no need to ask Camera permission.
- iOS: Ask the access to Camera and Gallery permissions

**Comment by huynguyennovem** [comment]
About 2, agreed, it's a bug. I'll fix it ASAP

**Comment by tlle14** [comment]
Thanks, retest pass! 

1. Asking for access permission: **FAILED**
- Android: only asks for Gallery permission => OK
![image](https://user-images.githubusercontent.com/69950655/151284676-a18a29af-2bed-403c-97ec-3c815d55774c.png)

- iOS: only ask for camera permission => **Should ask for both camera and** 
![image](https://user-images.githubusercontent.com/69950655/151283616-e4b74c46-01f3-4e5b-97bf-a46bef4a7954.png)


2. Displaying the permission setting => PASSED

https://user-images.githubusercontent.com/69950655/151285529-4136eeda-b6e6-4b0c-8ca4-c844fe9cc843.mp4

**Comment by huynguyennovem** [comment]
> iOS: only ask for camera permission => Should ask for both camera and gallery access permission

The best practice: Should only ask user to grant permission when they're going to use the feature.  FYI: https://blog.prototypr.io/3-best-practices-for-in-app-permissions-dce7d36544a4

**Comment by tlle14** [comment]
> > iOS: only ask for camera permission => Should ask for both camera and gallery access permission
> 
> The best practice: Should only ask users to grant permission when they're going to use the feature. FYI: https://blog.prototypr.io/3-best-practices-for-in-app-permissions-dce7d36544a4
Hi @huynguyennovem , it doesn't ask permission to access the Gallery.
The upper screenshot describes the issue (maybe) that I cannot configure Gallery Access permission on iOS. 

https://user-images.githubusercontent.com/69950655/151488103-ac34a26c-395a-4899-90c1-afc3ae284bed.mp4
