### ISSUE TITLE
Message > The screen turns to gray when copying a message from another App

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1196]
# Actual Result 
When pasting a text from another app to Twake channel, the chatting screen on Twake turns to gray. 
The user cannot paste the text.
- note: The issue seems to happen on some phones and another iOS version. I cannot reproduce on iPhone 12 - iOS 15.1.1

https://user-images.githubusercontent.com/69950655/149617881-2a82f219-3b5f-43f1-b9bf-71d381ddc2c7.mp4

# Expected Result
Please investigate. It should be able to paste text from another app to Twake successfully. 

# Environment
- Build version: 3.0.11
- Device:
iPhone 11, iPhone SE 
- QA environment

**Comment by EvGen94** [comment]
It happens only when the app language is not english, app CupertinoLocalizations issue - fix in the new build

**Comment by tlle14** [comment]
Thanks, retest pass!

https://user-images.githubusercontent.com/69950655/150899521-0a61e5e1-0e53-483f-a140-496d359ef771.mp4
