### ISSUE TITLE
Magic Link/Manage > The setting button is disappear when the user has member role

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1197]
# Precondition
The user is a member 

# Actual Result 
With a member role, the setting button in the Magic Link screen disappears.
![image](https://user-images.githubusercontent.com/69950655/149618466-dc3ed3fd-c6ad-4457-90f9-7c9be354a182.png)

# Expected Result
As in the ticket #1098, the button should be disabled instead of disappear
https://github.com/linagora/Twake-Mobile/issues/1098#issuecomment-997769832

# Environment
- Build version: 3.0.11
- Device:
iPhone 12
- QA environment

**Comment by EvGen94** [comment]
Done

**Comment by tlle14** [comment]
Thanks, retest pass!
Dark mode:
![image](https://user-images.githubusercontent.com/69950655/150765588-75254d1e-c1d3-4bf1-b155-1dd6f31acdc4.png)

Light Mode:
![image](https://user-images.githubusercontent.com/69950655/150765681-bb9c3517-1690-489a-b68d-678dad622d74.png)
