### ISSUE TITLE
Translation > It brokes the layout when text size is large 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1198]
# Precondition 
- The App language is Russian or Italian
- The text size is large or extra-large (Setting on phone)
- 
# Actual Result
On the inviting workspace screen, the button name is hidden by a small size button
![image](https://user-images.githubusercontent.com/69950655/149618866-a13c3ddb-559f-4c27-b437-cb2b6558b46b.png)

On a menu sidebar, the text is overflowing on the sidebar
![image](https://user-images.githubusercontent.com/69950655/149618887-09fd0883-2d31-4c2d-b869-2f0de8a8dad2.png)

# Expected Result
- The text content should be shortened in the corresponding langue.
- The layout should responsive when the text size is increasing

# Environment
Build version: 3.0.11
Device:
Redmi Note9 - Android 10
QA environment

**Comment by EvGen94** [comment]
Done

**Comment by tlle14** [comment]
Hi @EvGen94 
It's almost done. 
The switch company button is still overflowing out.
![image](https://user-images.githubusercontent.com/69950655/150765221-2a7646c2-26e2-4357-872a-ec3365302f9b.png)
