### ISSUE TITLE
Uploading file > The add attachment button doesn't work when it reaches the maximum uploaded file 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1199]
# Precondition
- Story: #1137 
- On the Uploading screen, it has uploaded 10 files already

# Actual Result
When tapping on the "Add Attachment" button, it doesn't work. It also doesn't have a pop-up to notify the user that he/she has reached the maximum uploaded files. 

https://user-images.githubusercontent.com/69950655/149626065-6dd818fd-1dfa-4772-8e29-9c2c5e1b98a8.mp4

# Expected Result
When the uploaded file reaches the limit, it should show a warning pop-up for the user to let her/him know.

# Environment
- Build version: 3.0.11
- Device:
iPhone 12 - iOS 15.1.1
- QA environment

**Comment by huynguyennovem** [comment]
![Screenshot_1642589062](https://user-images.githubusercontent.com/29337364/150115371-e69c4cb1-6db9-49e6-94cf-e85596415e3f.png)

Hi @tlle14  and @BastiaanVanGaalen, I'm going to design the dialog like this, what do your think?

**Comment by tlle14** [comment]
Thanks, 
Retest pass!

https://user-images.githubusercontent.com/69950655/151287836-e499d872-5af4-485a-8620-7874673787f9.mp4
