### ISSUE TITLE
Channel list > It doesn't display a preview message on the channel list when having a new message 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1217]
# Actual result
There doesn't have a preview message on the channel list. 
It always displays "this channel is empty"

https://user-images.githubusercontent.com/69950655/150296095-42644042-89df-4f7b-ae1c-851d0bb679df.mp4

# Expected Result
When having a new message:
- It should display a preview message in the channel list
- The channel name should be bold 
- The new updated channel should jump on the top of the channel list
Design: https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/61b8b7355f95dc5e18a32a64

# Environment
- Build version: 3.0.11
- Device:
iPhone 12 - iOS 15.1.1
- QA environment

**Comment by EvGen94** [comment]
Will be fixed soon

**Comment by tlle14** [comment]
> Will be fixed soon

Hi @EvGen94 kindly notice the Expected Result. There're 3 points that should be fixed.

**Comment by tlle14** [comment]
Retest failed
Is this ticket moved by accident? @EvGen94 

https://user-images.githubusercontent.com/69950655/150763109-0631ed4c-8158-4d7c-ae9a-db2acf3a6ef1.mp4

**Comment by tlle14** [comment]
Hi @EvGen94 
It displays a preview message now. The channel/group/direct chat are also jumping to the top. 
But, when having a new action in the channel, the channel name isn't bold. 
=> It should be bold. 
And in the dark mode, all channel names should be light. It only becomes bold when having a new update.
