### ISSUE TITLE
Message > The font size of the message and in the chat textbox are diifferent

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1219]
# Actual Result
The font size of a text in the chat textbox is bigger than on the message. You can see the big difference when increasing the font size of the device.
![image](https://user-images.githubusercontent.com/69950655/150315697-3e503659-64bb-4a97-9e79-d0d90956abe7.png)

# Expected Result
They should have the same font size. 

# Environment
- Build version: 3.0.11
- Device:
iPhone 12 - iOS 15.1.1
- QA environment

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen could you please confirm if the expected result is correct?

**Comment by huynguyennovem** [comment]
This is already same as design: https://zpl.io/aNx5OJD
- The message tile size: 15px
- Chat textbox size: 17px

![Screen Shot 2022-02-15 at 1 22 59 PM](https://user-images.githubusercontent.com/29337364/154004364-79033cf9-5f42-4c5b-99c3-4f1ba6c7f571.png)

![Screen Shot 2022-02-15 at 1 22 52 PM](https://user-images.githubusercontent.com/29337364/154004419-a69d307d-97af-4da3-8c48-f45e9abe8cb1.png)
