### ISSUE TITLE
Message > Displaying an unknown message after sending a message in a channel 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1241]
# Actual Result
When sending a message in a channel/ a group chat, it displays an unknown message at the opposite.
Please see this below video for the details

https://user-images.githubusercontent.com/69950655/151107038-62bf90d3-d0e7-4120-a0da-8a0a165e3fad.mp4

# Expected Result
It shouldn't display an unknown message after submitting a message in a channel/group chat

# Environment
- Build version: 3.0.12
- Device:
Samsung Galaxy A51- Android 11
iPhone 12 - ios 15.1
- QA environment

**Comment by EvGen94** [comment]
It is fixed already
