### ISSUE TITLE
Update channel > The member list doesn't update after adding more members

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1246]
# Precondition
The channel is created

# Actual Result
When adding more members to the channel, the member list is not changed. It doesn't show the newly added members

https://user-images.githubusercontent.com/69950655/151490140-0290a2ff-37da-434c-8b73-0e455eae71fe.mp4

# Expected Result
The channel should show the newly updated member list. 

# Environment
- Build version: 3.0.12
- Device:
Samsung Galaxy A51- Android 11
iPhone 12 - ios 15.1
- QA environment

**Comment by EvGen94** [comment]
Checked, sent all the information to Romaric 
We need  to wait till next release

**Comment by EvGen94** [comment]
Added fix, while waiting for a fix on the backend, since the members field should be empty for channels, but should be populated for the direct channels
