### ISSUE TITLE
[Story] Swipe to access to thread

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake-Mobile#1253]
Ho @BenoitTallandier @EvGen94 

I would really like to change the way we answer to messages on the app, could we open the thread instead of putting it as "quote" when we swipe the message ?

Something like the following video (I swipe and the thread open)

https://user-images.githubusercontent.com/14353924/151943992-cc18e69f-9d1d-486b-8e94-8dbb730484cf.MP4

# Why we want to change
For now, our behavior is : we swipe the message and we can respond to it like whatsapp, telegram and messenger.
It's not relevant for Twake. In the bellow example, I responding to Simon message's. But there are other response to this message, so I'm adding a message without seeing all the newest message in the thread 

![IMG_4D84031A7D33-1](https://user-images.githubusercontent.com/22451567/152133560-110f1119-573c-40c0-b2ba-9f0bcc7dceef.jpeg)

# Business case
- As a user, when I swipe a message in a channel, it opens the thread of this message and the input auto focus
- If I swipe a message without a thread, I still open the empty thread

**Comment by BenoitTallandier** [comment]
That's a good idea. The swipe to respond is clearly not appropriate for our application.

**Comment by EvGen94** [comment]
@BastiaanVanGaalen  @RomaricMourgues I don't know what is better, but our bosses wanted this thing as it is, so I would first check with Diana because they wanted it exactly like in another app

**Comment by RomaricMourgues** [comment]
Benoit is your boss for user stories actually :p If Diana disagree she must talk with Benoit first ^^

**Comment by EvGen94** [comment]
@RomaricMourgues I just don't want to redo this in future, that's all :) but in general @BenoitTallandier as you see

**Comment by sherlockvn** [comment]
#1342

**Comment by RomaricMourgues** [comment]
Yeees ! 🎉

**Comment by romanesko** [comment]
I don't fully understand this feature. It only makes sense for a thread that hasn't had a single answer yet. Otherwise there is no point in replying to a thread without having seen the previous replies.

**Comment by RomaricMourgues** [comment]
It is about opening the thread view instead of showing the message we are answering to on top of input. With the previous version of mobile app when you answer you don't even see your message as it is inside the thread you did not open first.
