### ISSUE TITLE
I can't mention user by name only by usename

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake-Mobile#1306]
To reproduce:
   In any chat try to mention user by name if name and username don't have common letters

I want to be able to find user by any identifier: name, email or username

**Comment by huynguyennovem** [comment]
Add the test case for this bug:
- Condition: This bug happens when the saved name starts with uppercase characters while user typing lowercase characters to search

https://images.zenhubusercontent.com/309637937/cdaab187-72b8-45bd-9676-cfebd4d74992/1306_mention_api_bug___demostration.mp4

**Comment by huynguyennovem** [comment]
BTW, also fix overflow errors:

<img src="https://images.zenhubusercontent.com/605175c4593ffb54122f0753/e2c0fef9-e42b-4cd8-bddc-f4fdd09235b7" width="240"/>

<img src="https://images.zenhubusercontent.com/605175c4593ffb54122f0753/623f58f7-3730-449d-a0b3-dcdbeec4d172" width="240"/>

**Comment by hantt12** [comment]
Hi @EvGen94 what is username in Twake? I just know firstname, lastname and email

**Comment by EvGen94** [comment]
@hantt12 Hi!
Username is deprecated it is no longer in use
