### ISSUE TITLE
Pinned message > I don't see pinned message header if I re-open the channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1346]
When I pin a message in a channel, I can see the blue header with the pinned message. Now I close the channel, and I come back, the header is not shown again

# How to reproduce
1. Open a channel
2. Pin a message
3. Go to another channel
4. Come back to the previous channel
5. See the error

# Video

https://images.zenhubusercontent.com/309637937/53493d0d-7e4b-4528-8345-b54510e97b9f/pinnedmessage.mov

**Comment by EvGen94** [comment]
It works fine on Canary, we just need to wait an update of production

**Comment by BenoitTallandier** [comment]
My bad, I was testing on the production.
It is working on canary. I close this issue
