### ISSUE TITLE
[Story] No thread in direct chat

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1357]
In direct chat, the thread feature is replaced by a "response" feature.

# Business case
- As a user, when I talked to someone in a direct message, I can not create a thread.
- As a user, when I answer someone in a direct message, I can see, above my response the message sent. If I click on this message, I jump to the initial message.
- As a user, when I answer someone in a direct message, and this message was deleted, instead of this message, I can see "deleted message"
- When I swipe a message inside a direct channel, the text input is focused and I see the message that I swiped above my text input.

# Design

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake.new?node-id=406%3A26340

 - Redesign of the entire application
    Using a new color scheme from Dmitry
    Redesign message bubble 
    Redesign file view for different file types
 - Reply in direct chats

**Comment by BastiaanVanGalen** [comment]
@BenoitTallandier deleted message view:
-original deleted message + deleted message inside "reply bubble":
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake.new?node-id=1083%3A73287
