### ISSUE TITLE
Highlighted text and highlighted paragraph should be displayed differently

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#142]
# Precondition
Highlight text: (`)
Highlight paragraph: (```)

# Actual Result

A highlighted text and highlighted paragraph are displaying the same on Mobile

On Web:
![image](https://user-images.githubusercontent.com/69950655/103335724-730b1780-4aa8-11eb-8f88-ed9bf080beaf.png)

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/103335772-ae0d4b00-4aa8-11eb-9da6-00c16b42170f.png)

# Expected Result
Please discuss with our BA and PO if they should display differently

# Environment
Both Android and iOS

**Comment by bobs4462** [comment]
They should, actually there's something like 21-22 different twacode objects out there, and all of them requires a unique style. Will work on most used ones on the next release.

**Comment by tlle14** [comment]
> They should, actually there's something like 21-22 different twacode objects out there, and all of them requires a unique style. Will work on most used ones on the next release.

Please show me where to find all twacode objects.

**Comment by bobs4462** [comment]
Appending the docs for future use
https://www.notion.so/Twacode-a7ac6a19be214837b20035e12914293a#5081ab548cf94065bc0e9006d88233fb

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
However, could you please make it more contrasting and modern as on the web?

**Mobile:**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2f25fc8d-73c0-4e36-b7d6-557ca1cd5fe7)

**Web:**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d055e16f-4978-453b-ab07-f1fc852b2a82)

**Comment by bobs4462** [comment]
@BastiaanVanGaalen Can you suggest a visual look for this type of twacode elements?

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Would you be so kind to clarify what methods can we implement with text like cut/copy/paste/bold/italics/underline.
@tlle14  Highlight seems like making it look higher in contrast, should we use "boldness" for this purposes since coloured text interferes with clickable text....i don't think it's a proper way of presenting the same coloured text for highlight and at the same time for links in a message

**Comment by bobs4462** [comment]
The text can be formatted with classical markdown styles i.e.
Bold - **\*\*BOLD\*\***
Underline - \_\_UNDERLINE\_\_
Italic - _\_ITALIC_\_
StrikeThrough - ~~\~\~STRIKETHROUGH\~\~~~
Inline code - text with `code` inlined
Code snippets:
```
print("HELLO WORLD")
```
Quotes: 
> This is quote


Also:

Mentions - @username 
Channels - #channel
Urls - https://www.rfc.com

That's all for now. But the list will be extended in near future.

**Comment by bobs4462** [comment]
Btw, you can play around with those styles in twake web to see how it renders there

**Comment by bobs4462** [comment]
@BastiaanVanGaalen any progress on this one? We should also take into account the fact that those formatting styles can appear in both user's messages and others' messages, both of which have distinct background/foreground colors.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 
Please, Sir: https://zpl.io/Vk1z5pW

**Comment by BastiaanVanGaalen** [comment]
For now, the task with formatting cannot be dealt with. We must focus all our efforts on stabilising MVP version.
Some time in future I will design UI related to formatting including custom keys for mobile keyboard so users are able
to format easily with quick shortcuts.

For now leave it as it is.
