### ISSUE TITLE
Add "Delete account" button to pass the AppStore release verification

### ISSUE THREAD

**Issue by shepilov** [linagora/Twake-Mobile#1500]
- Add the button as on the following screenshot
- This button should lead to the "Console" app https://staging-console.twake.app/profile?company-code=c6590da6-9158-4222-a664-c181554775fa, where "company-code" is the company identifier

<img width="837" alt="image" src="https://user-images.githubusercontent.com/14924963/200348429-2e6b0f69-af81-47e4-93e6-bbe8314ecad7.png">

**Comment by chibenwa** [comment]
Hi @shepilov 
Could you give quick rationnals in comments on why this issue is no longer needed?
