### ISSUE TITLE
UI > the chat textbox 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#226]
# Actual Result
1. The chat textbox is too small 
2. The borderline is too bold

![image](https://user-images.githubusercontent.com/69950655/105484233-960e9d00-5cdd-11eb-8c7f-7ff1521788d0.png)

# Expected Result
It should conform to the design 

![image](https://user-images.githubusercontent.com/69950655/105484632-34026780-5cde-11eb-9b80-dde87f6c1077.png)

# Environment
Android app
Build version: twake-2-2-0

**Comment by bobs4462** [comment]
@BastiaanVanGaalen can you suggest some adjustments to current design?

**Comment by PokoinikRWS** [comment]
4 string is enough to common user.

We check it with Growth Team @dsankova

**Comment by RockinPaul** [comment]
The task isn't actual anymore due to the upcoming redesign.

**Comment by tlle14** [comment]
I agree to @RockinPaul
