### ISSUE TITLE
Add twacode image to markdown image conversion on proxy layer

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#228]
As we decided to adopt markdown as main format for storing message strings, we need to start migration toward it already.
Currently basic styles (bold, italic) are encoded in message string, so no issue there, but images are only present in twacode. We need to grab those images on proxy from twacode and insert them into markdown string before returning it the client.

**Comment by bobs4462** [comment]
https://pub.dev/packages/flutter_markdown - here's the documentation regarding the library used for markdown parsing

**Comment by romanesko** [comment]
@bobs4462  We are decided not to include the images inside of the message, aren't we?

**Comment by bobs4462** [comment]
We are moving away from markdown to stick with modified block based twacode, so I'm closing this issue, because it's not relevant anymore.
