### ISSUE TITLE
Improve application load icons

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#231]
There's a tool for icon generation at https://appicon.co/
There's a suggestion, that we should use it to generate better looking icons for mobile application.
Here's some example icons for both iOS and Android
[https://app.zenhub.com/files/309637937/bfd59aff-48bf-4923-b4d4-075865c59c6b/download](https://app.zenhub.com/files/309637937/bfd59aff-48bf-4923-b4d4-075865c59c6b/download)
[https://app.zenhub.com/files/309637937/014b46c2-21ed-4c50-bd83-be9d2d701c14/download](https://app.zenhub.com/files/309637937/014b46c2-21ed-4c50-bd83-be9d2d701c14/download)

**Comment by bobs4462** [comment]
@RockinPaul Do we have any plans on this one? Or should we move it to the icebox?

**Comment by RockinPaul** [comment]
@bobs4462 no plans currently. It's better to even close it I suppose.
