### ISSUE TITLE
Show all existing members when initiating a direct chat

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#241]
When initiating a direct chat all existing members are to be displayed sorted by recent activity:
https://zpl.io/VO6myv1

**Comment by RockinPaul** [comment]
@BastiaanVanGaalen 
Conflicting issues:
https://app.zenhub.com/workspaces/twakemobile-5fa5101d98879700119ccea9/issues/twakeapp/mobile/191 - I've just removed this 4 days ago.

**Comment by RockinPaul** [comment]
It's currently impossible due to the original API limitations.

**Comment by bobs4462** [comment]
@BastiaanVanGaalen we are currently showing all members with the ability to search through them, but we cannot sort them by recent activity, as there's currently no way keep last activity of all the users in sync with mobile app in real time. 
Please close this issue, if there's nothing else to be done.
