### ISSUE TITLE
Recent activity tracking

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#242]
Display last seen time In chat detail view:

https://zpl.io/awNmpkd

**Comment by romanesko** [comment]
done

**Comment by tlle14** [comment]
Cannot test

**Comment by tlle14** [comment]
@BastiaanVanGaalen Hi, could you please add me to the Zeplin project so I can retest and close this issue?

**Comment by BastiaanVanGaalen** [comment]
@tlle14 provide me with your email address, please.

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen please add my linagora email: tlle@linagora.com
Thank you

**Comment by bobs4462** [comment]
Recent activities for all the user's cannot be synced with the app in a real time for now, and will require a tremendous amount of work in future, so let's close  this one, before we create a user story for the entire feature.
