### ISSUE TITLE
Direct chat creation flow update

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#244]
1. Change title of the main view for "New direct chat"
2. Remove "Create" button in right corner of a tool bar
3. Remove radio buttons on cells
4. Upon tapping on the found member there should be an auto-transition to chat view

**Comment by tlle14** [comment]
Thanks, 
I can see the change
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/b51332ef-e025-4b30-a0e6-74c702c9fc7c)

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen 
I reopen this issue to confirm about search member function. 
When I inputted a keyword, how does the search work?

**Comment by bobs4462** [comment]
@BastiaanVanGaalen ping

**Comment by RockinPaul** [comment]
@BastiaanVanGaalen and @tlle14 by the way It will work exactly the same with the available API. It was discussed with @romanesko 
This issue should be closed since the comment to re-open it had nothing to do with the task description itself.

**Comment by tlle14** [comment]
Okay @RockinPaul I should close this one
