### ISSUE TITLE
Channel > Chatbox is aligned to the top in an empty channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#251]
# Precondition
A new channel/ direct chat

# Actual Result 
When the channel/direct chat is empty, the chatbox and the text `No messages yet` are aligned to the top
![image](https://user-images.githubusercontent.com/69950655/106695334-f3bfb500-660c-11eb-88b7-4ac1031961fa.png)

# Expected Result
The chatbox should display on the bottom
The text should be in the center.

# Environment
iOS/Android device
Build version: twake.2.2.2

**Comment by RockinPaul** [comment]
Unable to reproduce anymore. Possibly fixed during other tasks implementation.

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/ca2d853b-e7de-4c5f-a649-8d504237485d)
