### ISSUE TITLE
Ability to send photos and files in a chat

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#259]
https://zpl.io/VKO6DxR

Photo preview in a chat
File preview in a chat
Change the following icons:
- message sending
- emoji sending
- file sending

**Comment by bobs4462** [comment]
@RomaricMourgues Hello, you previously mentioned that you are working on new Messaging API, do you have any plans regarding attachments?

**Comment by bobs4462** [comment]
@RomaricMourgues ping :)

**Comment by RomaricMourgues** [comment]
Unfortunately this is still early work:
https://www.notion.so/twake/New-Public-developer-APIs-WIP-d557318c47d747ffaee3cb2244e94572

I am following this documentation:
https://api.slack.com/reference/block-kit/blocks#file
https://api.slack.com/block-kit/building#stack_of_blocks

So basically it will be closed to what we had with Twacode, but with more markdown and less nested components.

**Comment by bobs4462** [comment]
**STEP №1** Make request to get file identifier in drive (without uploading the file itself)
```
POST https://chat.twake.app/ajax/driveupload/preprocess
BODY {"workspace_id":"ac6c84e0-1dcc-11eb-82c8-0242ac120004","name":"147522.jpg","extension":"jpg"}
RESPONSE {identifier: ac6c84e0-1dcc-11eb-82c8-0242ac1200041616486113b413c34a7b5b89507b8ddc90cc2bb924e731d65d}
```
**STEP №2** Use the provided identifier to actually upload the file using multipart form data

```
POST: https://chat.twake.app/ajax/driveupload/upload,
BODY: 
{
		"resumableChunkNumber": "1",
		"resumableChunkSize": "50000000",
		"resumableCurrentChunkSize": "724953",
		"resumableTotalSize": "724953",
		"resumableType": "image/jpeg",
		"resumableIdentifier": "ac6c84e0-1dcc-11eb-82c8-0242ac1200041616486113b413c34a7b5b89507b8ddc90cc2bb924e731d65d",
		"resumableFilename": "147522.jpg",
		"resumableRelativePath": "147522.jpg",
		"resumableTotalChunks": "1",
		"object": "{\"id\":null,\"front_id\":\"04a23318-318d-2744-e158-09b5abf62e69\",\"is_directory\":false,\"name\":\"147522.jpg\",\"parent_id\":null,\"workspace_id\":\"ac6c84e0-1dcc-11eb-82c8-0242ac120004\",\"detached\":true}"
                  ...AND THE FILE ITSELF AS OCTET STREAM
}

RESPONE {
  "data": {
    "object": {
      "id": "1a69bf50-8bad-11eb-aa2d-0242ac120002",
      "front_id": "04a23318-318d-2744-e158-09b5abf62e69",
      "workspace_id": "ac6c84e0-1dcc-11eb-82c8-0242ac120004",
      "parent_id": "detached",
      "detached": true,
      "trash": false,
      "is_directory": false,
      "creator": null,
      "name": "147522.jpg",
      "description": "",
      "last_user": null,
      "size": 724953,
      "added": 1616486115,
      "modified": 1616486115,
      "last_modification_token": "1616486115-e12ff066318727ee862276e540bf57ad",
      "extension": "jpg",
      "cache": [],
      "preview_link": "https://storage.gra.cloud.ovh.net/v1/AUTH_16f746ba29904ed99fc4e6a01d9b1a1a/twake.public/public/uploads/previews/ac6c84e0-1dcc-11eb-82c8-0242ac120004/1a725516-8bad-11eb-839e-0242ac120002.png",
      "copy_of": null,
      "shared": false,
      "url": null,
      "opening_rate": 0,
      "has_preview": true,
      "preview_has_been_generated": true,
      "default_web_app_id": null,
      "acces_info": null,
      "application_id": null,
      "external_storage": false,
      "hidden_data": [],
      "tags": null,
      "attachments": [],
      "versions": [
        {
          "id": "1a725516-8bad-11eb-839e-0242ac120002",
          "name": "147522.jpg",
          "file_id": "1a69bf50-8bad-11eb-aa2d-0242ac120002",
          "added": 1616486115,
          "size": 724953,
          "creator": null,
          "data": {
            "upload_mode": "chunk",
            "identifier": "ac6c84e0-1dcc-11eb-82c8-0242ac1200041616486113b413c34a7b5b89507b8ddc90cc2bb924e731d65d",
            "nb_chunk": "1"
          }
        }
      ]
    }
  },
  "_cookies": []
}
```

And I have a few questions @RomaricMourgues. 
**1.** Is the **object** field in formdata when sending the file in step №2 obligatory? If yes, what is the **frontid**, is it possible to upload directory, what is **detached**? Also can **resumableFilename** be different from **resumableRelativePath**?

**2.** How can we access the file knowing it's identifier?

**3.** Is uploading non-image files is the same as the image ones?

**4.** Should we use twacode structure to embed images into messages?

**Comment by RomaricMourgues** [comment]
1. 
-> The object field is mandatory bur frontid is not.
-> You can upload a directory but you must do the work yourself to create directories and set the parent ids on each child fields upload.
-> detached means the file is not in the Twake drive (so no parent folder defined)
-> I think you can set whatever you want in the resumableFilename and resumableRelativePath, the file name must be defined in the preprocess part

2. You can call this route: POST https://web.twake.app/ajax/drive/v2/find
```
{"options":{"element_id":"a089b0f8-8b2c-11eb-9c64-0242ac120003","workspace_id":"f339d54a-e833-11ea-92c3-0242ac120004","public_access_token":null}}
```

3. Yes it is the same

4. Partially, it looks like this, a "files" field with twacode in it (I know, very ugly right now)
![Uploading Screenshot 2021-03-23 at 12.11.39.png…]()

**Comment by bobs4462** [comment]
@RomaricMourgues when we make a request to
`/ajax/drive/v2/find/`

We only get a preview link (if one is generated). But how to get a download link?

**Comment by RomaricMourgues** [comment]
`/ajax/drive/download?workspace_id=481a1a78-4747-11e9-8710-0242ac120005&element_id=d4e6a2c0-6f6b-11eb-8a9f-0242ac110003&download=1`

**Comment by tlle14** [comment]
Hi @bobs4462 
The feature is undone. I cannot select to upload a file or a photo on iOS, which is related to this issue https://github.com/linagora/Twake-Mobile/issues/561

About the design, it is changed. @BastiaanVanGaalen could you please confirm which one should be used? 
[the new](https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/60922e4b763f0608f0004ae0) or [the old](https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/dashboard?seid=601abf8647db888afd2517ab)

**Comment by BastiaanVanGaalen** [comment]
@tlle14 We have a photo upload flow here: https://zpl.io/VDgmqNJ
The is the single one and has always been)

**Comment by bobs4462** [comment]
Ok, let's wait for the backend part, and reimplement this feature in a more smart way
