### ISSUE TITLE
Create Channel > The old data stay in the creation form after creating a private channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#281]
# Precondition
Creating a private channel

# Actual Result
When reopen the creation form to create another channel, it displays the old data:
- channel type is private
- the number of added member
https://images.zenhubusercontent.com/309637937/b9d6a262-d0a0-41b1-bc44-edfb06d08f21/video8dc0bf3d_1641_4ca3_a7a5_c6c752dc0318video.mp4

# Expected Result
After created a private channel successfully, the creation form should be cleared.

# Environment
Both iOS and Android App
Build version: twake.2.2.7

**Comment by tlle14** [comment]
Hello team, the same issue when creating a new workspace on version 2.2.7
Could you please fix it? @bobs4462

**Comment by tlle14** [comment]
Hi @RockinPaul 
Retest failed when creating a private channel. The data about channel type (private) and added members are staying on the form
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/8a53382e-b393-49db-9d36-8940ef4beaa7)

**Comment by tlle14** [comment]
Hi @RockinPaul 
Retest failed! When reopen the create channel form, add participant search form still displays old selected data. 

Could you please check this video? 
https://images.zenhubusercontent.com/309637937/aa7e666f-4018-403a-869b-8337b1ff2c44/videoda92417b_ee06_49f9_9b9d_16ef6598b747video.mp4

**Comment by manhduc-nguyen** [comment]
@tlle14 please retest, I think this bug no longer exists.

**Comment by tlle14** [comment]
Thank @manhduc-nguyen 
Retest pass!
https://images.zenhubusercontent.com/309637937/8e0f1c5a-92bf-450e-a4f9-ec1cdeb26e38/video182ed67a_15a3_4f9f_b1c0_cf37405e0192video__1_.mp4

**Comment by tlle14** [comment]
I have to reopen this issue because: the member counter stays after close the channel creation form
https://images.zenhubusercontent.com/309637937/b0ad37bd-e3eb-44a2-85e7-94fa026c01a2/videof9654806_0d9a_4234_949b_6fedbc4591c7video.mp4

**Comment by tlle14** [comment]
Retest pass!
Thank @manhduc-nguyen 
https://images.zenhubusercontent.com/309637937/2da78ecc-ab66-4ede-969a-a053dafafdf6/videod03cafe3_b038_429c_96bd_b97a87c91484video.mp4
