### ISSUE TITLE
Create Workspace > Cannot add member successfully when creating a workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#283]
# Actual result
UserA  invites UserB while creating a workspace
But UserB isn't actually invited after the workspace is created

**Creating a workspace on mobile:**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/adb23101-1941-498c-8e4b-2b61bec55ebb)

**On Web after created a workspace**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/4ca841b3-bb1f-4418-abbd-10d5b85f3a41)

# Expected Result
A member should be able to be added to the new workspace while creating

# Environment
Both Android and iOS app
Build version: twake.2.2.7

**Comment by manhduc-nguyen** [comment]
@tlle14 can you re check this please? its not happening anymore.

**Comment by tlle14** [comment]
I agree with you @manhduc-nguyen 
The issue is no longer existing
