### ISSUE TITLE
Create Workspace > It would be better if user can search and add member to invite

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#285]
# Actual Result
When creating a workspace, the user has to manually input the member's email.
![A19D35E3-D01F-4623-854E-4101F665F0CC.jpg](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9f1ffa21-7942-49b7-9c4c-b7d72d346309)

# Expected Result
It should:
- Be able to search and add Twake member to the new workspace by email
- Be able to add a guest to the workspace by email
- Email text field should be validated
As on Twake Web. 

# Environment
Both Android and iOS App
Build version: twake.2.2.7

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen,
Please review and check if we should update Zeplin design. 
Thanks!

**Comment by bobs4462** [comment]
I don't think that this issue has a solution right now, because backend doesn't support it yet, so we'll return to it in further iterations.
