### ISSUE TITLE
Create Workspace > Member counter is incorrect

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#286]
# Actual Result
1. The member counter is counted when there has a blank line
https://images.zenhubusercontent.com/309637937/f17887ef-a4b1-4984-acce-85c0561dcbfd/rpreplay_final1613996371.mp4

# Expected Result
The invited collaborators number shouldn't count the empty line. 

# Environment
Both iOS and Android App
Build version: twake.2.2.7

**Comment by manhduc-nguyen** [comment]
@tlle14 sr I think the video is broken. Can u re upload pls?

**Comment by tlle14** [comment]
I don't see this bug existing anymore. 
I should close it.

**Comment by tlle14** [comment]
Sorry @manhduc-nguyen 
I can reproduce the issue. Please see the attached video

https://user-images.githubusercontent.com/69950655/115201640-c10f5e00-a11f-11eb-8662-2f2cfb7e690b.mp4

**Comment by tlle14** [comment]
Hi @manhduc-nguyen 
Retest failed!
The row that is not added to the list still be counted. 

https://images.zenhubusercontent.com/309637937/e4dc63c1-2f89-47fd-9d21-eb36976d97bc/rpreplay_final1619161072.mp4

This issue might relate to https://github.com/linagora/Twake-Mobile/issues/474

**Comment by tlle14** [comment]
Thank @manhduc-nguyen 
Retest pass!
https://images.zenhubusercontent.com/309637937/bb7e4878-abff-4170-8ed7-24bb9f3d7d4a/rpreplay_final1620211515.mp4
