### ISSUE TITLE
Notification > When the app is open, there's no notification for mentioned or replies in another channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#288]
# Precondition
The App is openning. 
There're ChannelA and ChannelB
The logged in user is in ChannelA

# Actual Result
While user is in ChannelA, he is mentioned in ChannelB, but there's no notification for the message in ChannelB.

# Expected Result
There should have a push notification for the message, even while the app is openning. 

# Environment
Android App
Build version: twake.2.2.7

**Comment by tlle14** [comment]
Hi @bobs4462 
I saw the push notification in the foreground running, but a new message in the private channel doesn't have a push notification. 
Please check.

**Comment by bobs4462** [comment]
@tlle14 I checked it again, if you can receive mentions (or thread based) notifications in public channels, you should be able to get the same notifications in private and direct channels

**Comment by tlle14** [comment]
Hi @bobs4462 I retested this issue and here is the result:

**Context:** The user is in a different channel. The new messages is posted in another private channel.
**Result:** 
1. When having a new message in the related thread, the notification comes late (after 2 mins)
2. When mentioning the user, no notification.

It seems the push notification is not stable. I don't think it works normally.

**Comment by tlle14** [comment]
Hi @bobs4462 I can see the notification on Android only. 
The case is not passed on iOS App.

**Comment by tlle14** [comment]
Work for android
