### ISSUE TITLE
Proxy integration as subset fo core

### ISSUE THREAD

**Issue by romanesko** [linagora/Twake-Mobile#297]

**Comment by bobs4462** [comment]
I can confirm that now we can use the same host url as for the web version.

Available servers:
https://chat.twake.app - for old users
https://beta.twake.app - for new users
https://web.qa.twake.app - for QA only

**Comment by tlle14** [comment]
Hi @bobs4462 
Please explain what is the new user in this context?

**Comment by bobs4462** [comment]
it's those who have registered their account after 9th of January 2021 from beta.twake.app domain.
![image](https://user-images.githubusercontent.com/31780624/114859166-0b789e00-9df3-11eb-997a-54d8239593ef.png)

**Comment by tlle14** [comment]
Thank @bobs4462 
But it's complicated with users. 
On production, next time, we won't have too many servers like this, am I correct?

**Comment by bobs4462** [comment]
Well, I think chat.twake.app and beta.twake.app will be merged together I think, so we should have just one production SaaS server.

**Comment by tlle14** [comment]
I feel relieved to know that. Thank @bobs4462 
I should close this issue
