### ISSUE TITLE
Notification > No badge icon counter on iOS

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#315]
# Actual Result
On iOS, there's no message counter on the badge icon

# Expected Result
It should have the badge icon counter for the badge icon on ios

# Environment
iOS app only
Build version: 2.2.9

**Comment by RomaricMourgues** [comment]
Thanks for the notification @bobs4462 , it is fixed for next release.
For now we always set the badge value to one if there is notifications.
**We do not remove this badge value** you must do it in the mobile app if everything is read.

**Comment by bobs4462** [comment]
@tlle14, is this one fixed?

**Comment by tlle14** [comment]
I can close this issue since the badge counter seems to stay forever
