### ISSUE TITLE
Server connection > Sometimes it's hard to paste the link from clipboard

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#317]
# Precondition
The server link is copied to the clipboard

# Actual Result
On the server connection screen, clear the textbox then try to paste a link from the clipboard, `sometimes` it doesn't work. 
https://user-images.githubusercontent.com/69950655/109806418-44035480-7c57-11eb-87b3-53ca5a3db7cf.mp4

# Expected Result
Please investigate. 
It should be easier to paste a link from the clipboard

# Environment
iOS App
Build version: 2.2.9

**Comment by RockinPaul** [comment]
@tlle14  Unable to reproduce. It could be fixed during the Server Connection page logic rework. Please, check again.

**Comment by tlle14** [comment]
I should close this one.
