### ISSUE TITLE
Edit channel > It doesn't allow to update the channel privacy

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#320]
# Actual Result
There's no place for the user to update the channel privacy
![image](https://user-images.githubusercontent.com/69950655/109942203-8d5ead00-7d06-11eb-99a8-253f90bb38cb.png)

# Expected Result
The user (Admin/creator) should be able to update the channel privacy. 
And yes, follow this rule: https://github.com/Twake/Twake/issues/512 

# Environment
Both Android and iOS app
Build version: 2.2.9

**Comment by romanesko** [comment]
No they should not. If channel was created private — it stays private for all the time. And vice versa.
All the owner can do — is to change name and icon (and the members set) or delete the channel and make the new one.
Thank you.

**Comment by tlle14** [comment]
@romanesko I don't understand why the mobile app shouldn't be able to change the channel privacy, while we can on the web app? 
I logged this issue based on the story of the web app: https://github.com/Twake/Twake/issues/512
Let BA and PO decide this feature on Mobile. 
I will close this issue when they said no change to privacy.

**Comment by PokoinikRWS** [comment]
@BenoitTallandier , please describe what a reason to change privecy ?

I will very disappointed in a service if my messages from private channel will be public in future...
Less negative if someone hide my conversation from public channel to private...

**Comment by RomaricMourgues** [comment]
The current right system for channels was built over studying Teams, Slack, Mattermost or even Messenger. And was validated with BA and POs, then developed 3 month ago.

We cannot change business rules every two months if we want to built the same product together... We lost a lot of time always going back to questions discussed months ago.

Anyway :) Reasons for changing to public:

- Human error, channel was created private but should be public
- Change of opinion, for instance CoTech channel could have been changed to public multiple time (ask Alexey)
- You can find angry users for slack here (and also a proof that we will never please everyone by the way :) ): https://twitter.com/SlackHQ/status/835541575144992769

**Comment by PokoinikRWS** [comment]
Romaric, so I've to speak with BA first. We lose our reputation in privacy if someone can make private channels visible to publick by administrator will...

**Comment by romanesko** [comment]
In case of human error — user can delete and create channel right )
Slack team also reasonably denied this request: «We don't allow converting private channels to public channels for privacy reasons»

**Comment by bobs4462** [comment]
@romanesko Should we wait for this issue to be resolved on business level?

**Comment by romanesko** [comment]
Done for backend part, waiting for changes in app

**Comment by bobs4462** [comment]
Not relevant anymore, as the channel edition is being reworked
