### ISSUE TITLE
Create Channel > Creating a private channel doesn't success at first

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#326]
# Actual Result
Creating a private channel, adding 4 members to the channel, then tap the "Create" button => It shows an error message for creation failed
After that, rename the channel then tap the "Create" button, the channel is created successfully
https://images.zenhubusercontent.com/309637937/fa5e4895-fa46-4deb-b693-da7d750e24af/video388428ab_7b0f_4625_9d7d_030f7d846d1bvideo.mp4

# Expected Result
The creation should be successful at the first time

# Environment
Android App
Build version: 2.2.9-1

**Comment by tlle14** [comment]
Hi @RockinPaul 
The private channel has been created without the inputted description. 
Please check this issue. 
https://images.zenhubusercontent.com/309637937/fc224ba0-c5b1-4166-a60a-e0e7efddef27/video9b57f488_585c_4dd7_babc_ceca8e8cf7a2video.mp4

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Greetings, my dear friend! Channel description (assumed, it was created some time ago) can only be viewed on channel editing screen.

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen @RockinPaul 
Sorry, I uploaded incorrect evidence. We have 2 issues here:

# 1. After created a channel, the description is not saved. The user doesn't see it in the description field when open the edit channel screen.
=> After a channel is created, the channel description should expose on the edit channel screen 
https://images.zenhubusercontent.com/309637937/dfb41904-97a5-48d3-a95d-f5efa7448c32/rpreplay_final1616555216.mp4

# 2. Still cannot create a channel on the first try. It shows the error message. User can create a channel for the second time click the "create" button
=> The channel should be created if all inputted data is valid.
https://images.zenhubusercontent.com/309637937/141b67c6-39d9-436c-a966-1bb4cc62fbb0/rpreplay_final1616556610.mp4

**Comment by RockinPaul** [comment]
Hello @tlle14 !

This issue was reproduced again due to unexpected backend changes and the overall instability of our API. As for the morning of March 26, it should work fine even on the previous build.

**Comment by tlle14** [comment]
@RomaricMourgues could you please take a look? This is a backend current issue.

**Comment by RomaricMourgues** [comment]
The QA will be updated soon, we added a new feature: default channels, it caused the bug on channel creation.

**Comment by tlle14** [comment]
On the build 2.2.9-5, a private channel is able to be created at the first try. 
But the channel description is not saved when creating on mobile.
So retest failed!

@RomaricMourgues

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass!
https://images.zenhubusercontent.com/309637937/8689292c-d4af-4dc5-84ed-03c3f8a9e992/videobadb0e70_9dbe_46a1_bb6c_457ed8ba2ff2video.mp4
