### ISSUE TITLE
Search member function isn't working correctly

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#338]
# Actual Result
The search function returns unmatching results
https://user-images.githubusercontent.com/69950655/110589402-f2078500-81a8-11eb-9c1c-c7e9316bfdd1.mp4

# Expected Result
Please rework the search function when creating channel/ create direct/ edit channel:
- The result should match the keyword by email/ first name/ last name
- If not, it should return a message: no results found

# Environment
Android App
Build version: 2.2.9-1

**Comment by RockinPaul** [comment]
Hi @tlle14 ,

The search API implementation has an issue: https://github.com/linagora/Twake/issues/1070

So I propose to close this one for now because:
1) I can't resolve it from a client-side.
2) It has nothing to do with the current search logic implemented in the mobile application.

**Comment by tlle14** [comment]
Sure @RockinPaul 
Thank you ;)
