### ISSUE TITLE
Elements in the channel list looks like disordered

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#339]
# Actual Result
When we have multiple data types, the channel list looks like a mess. Let's see:
- Channel icon vs. no icon
- Private channel icon (lock icon)  vs. public channel icon (no icon)
- Timestamp vs no timestamp 
![image](https://user-images.githubusercontent.com/69950655/110593717-82949400-81ae-11eb-8df6-9ebb21386bbe.png)

# Expected Result
We need advice from our UX designer. 

Here what I suggest:
- Lock icon should display right after the channel name. 
In case the channel name is too long, it should display `channel name is too ... <lock_icon>`
- About timestamp, the way it displaying is decided in this ticket. 
https://github.com/Twake/Mobile/issues/311#issuecomment-793616025
- Timestamp should display in the same line with the channel name and the lock icon

# Environment
Android App
Build version: 2.2.9-1

**Comment by BastiaanVanGaalen** [comment]
@tlle14 as for messy channel list it was completely overhauled and re-engineered in a new version of UI.

 We agreed with @romanesko about default gradient fills for channels thumbnail avatars in case user failed to upload one.
@romanesko When can we expect for this feature to be implemented? =)

- channel privacy icon and timestamp display are also handled in a new UI. You can follow the link to appreciate the new
UI architecture: https://zpl.io/V1RoBeE

**Comment by RockinPaul** [comment]
Partially fixed, regarding UX advice for better representation of the current version. However, as mentioned above, we will completely redesign this page - so the task isn't actual anymore.

**Comment by tlle14** [comment]
okay, thạnks @BastiaanVanGaalen @RockinPaul
