### ISSUE TITLE
Delete channel > When the user doesn't have a delete permission, the delete button should be hidden or disabled

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#347]
# Precondition
Refer to the story: https://github.com/Twake/Twake/issues/512

# Actual Result
When deleting a channel that the user doesn't have permission, it cannot delete the channel, also doesn't have any message. 
https://images.zenhubusercontent.com/309637937/d4e4c54a-5aae-4270-9c46-d1065e650176/rpreplay_final1615453329.mp4

# Expected Result
For the user doesn't have permission, the delete button shouldn't be displayed, or it should be disabled

# Environment
Android App 
Build version: 2.2.9-2

**Comment by RockinPaul** [comment]
Hey @tlle14 !

Currently, any user who has Editing permission is able to delete a channel. So the issue will be solved by restriction of access to channel editing flow for users without EDIT_CHANNEL permission.
That means we no longer need to manage delete button behavior because it will be automatically unreachable for users without appropriate permission.

**Comment by tlle14** [comment]
Hi @RockinPaul Let me ask @RomaricMourgues if he missed some fields in the API. The edit permission is defined clearly on the Web story like this:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/0576c147-29cc-4130-8e13-000e811f475a)

@RomaricMourgues @bobs4462 could you please confirm?

**Comment by RomaricMourgues** [comment]
I confirm the image is correct, only admin and creators have access to update privacy and delete channel options.

**Comment by tlle14** [comment]
The story tells that:
- The admin, the channel creator have *full* EDIT_CHANNEL permission
- The other member has *partial* EDIT_CHANNEL permission, not including Delete and update privacy. 
- The Guest doesn't have EDIT_CHANNEL permission.

@RockinPaul

**Comment by tlle14** [comment]
Thank @bobs4462 @RockinPaul 
Retest pass!


- When Admin creates a channel:
+ Delete button is enabled on the Admin account
+ Delete button is hidden on a normal user account

- When a normal user creates a channel:
+ Delete button is enabled on the Creator account, Admin Account
+ Delete button is hidden on another normal account
