### ISSUE TITLE
Incorrect App icon on iOS device

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#348]
# Actual Result
On iOS device, the app icon has black border
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e49b0dbc-cd2f-4cde-8ccf-e1b63e6704dc)

# Expected Result
The app icon should display correctly

# Environment
iOS App
Build version: 2.2.9-2

**Comment by RockinPaul** [comment]
@BastiaanVanGaalen could you please check if we have something to do with this? And should it be fixed?

**Comment by tlle14** [comment]
Hello @BastiaanVanGaalen Could you please take a look at this issue?
The app icon on iOS should be the same as the one on Android, with no black border.
![image](https://user-images.githubusercontent.com/69950655/117952724-a192dc00-b33f-11eb-8036-d2e7b5952f42.png)

**Comment by BastiaanVanGaalen** [comment]
[Archive.zip](https://github.com/linagora/Twake-Mobile/files/6465515/Archive.zip)
@RockinPaul I prepared the icon pack in all  required sizes and scales for iOS and Android.  Please, let me know if smth won;t play out as expected.

**Comment by BastiaanVanGaalen** [comment]
[Archive.zip](https://github.com/linagora/Twake-Mobile/files/6465897/Archive.zip)
@RockinPaul

**Comment by BastiaanVanGaalen** [comment]
[https://app.zenhub.com/files/309637937/8a4dd245-665b-47b6-84e9-663e70df5c08/download](https://app.zenhub.com/files/309637937/8a4dd245-665b-47b6-84e9-663e70df5c08/download)

@bobs4462 @EvGen94 Guys, i attached the archive with new icon, please, update it, thank you.
