### ISSUE TITLE
Cannot create a direct group on the Mobile app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#350]
# Actual Result
When creating a direct chat, select a member then it redirects to the direct chat of a person immediately. The user cannot select multiple members to create a direct chat. 

# Expected Result
The user should be able to create a group chat

# Environment
Both android and ios app
Build version: 2.2.9-2

**Comment by bobs4462** [comment]
@RockinPaul I thought this one has been fixed already

**Comment by RockinPaul** [comment]
@bobs4462  no, since we decided (believing that we've been granted to decide) that directs are for the one-to-one conversations only. If the required condition is possible in API - I can fix that.

**Comment by bobs4462** [comment]
@BenoitTallandier Hello, do we need to implement direct chats with multiple members in mobile app? For now direct chats can only be created with one user only. @BastiaanVanGaalen your opinion here also will be valuable.

**Comment by BenoitTallandier** [comment]
Yes, we have to implement direct discussion with 2 or more people inside.
Sometimes, users don't want to create a specific channel for temporary discussion. So they will use direct chat for that.

**Comment by BastiaanVanGaalen** [comment]
Ok i will create the UI flow allowing users to create a group chat/quick discussion chat instead of creating a channel

we might as well offer different set of options such as:
- auto-destroy such chats after n-days(user will specify a span manually) so not to clutter your channel list
- groups can be converted into a channel if necessary

**Comment by BenoitTallandier** [comment]
For the auto-destroy, I’m not a big fan.
User can hide direct discussion, so if they don’t want to see anymore the discussion in there sidebar.


I totally agree with your idea of conversion. It could be useful in some case :)

Benoît Tallandier
***@***.***
(+33)6 06 49 36 81

**Comment by bobs4462** [comment]
@BastiaanVanGaalen what is the final decision on this?

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 @EvGen94 
Group chat creation flow: https://zpl.io/VOE1RgQ

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 @EvGen94 UI has been updated, now you can only multiple-select other participants without opportunity to set a group chat name or image.https://zpl.io/VOE1RgQ

**Comment by bobs4462** [comment]
@BastiaanVanGaalen can you confirm that we can close this issue, as we are definitely removing this feature from Twake (from web including)

**Comment by tlle14** [comment]
This issue should be closed since the feature is removed

**Comment by EvGen94** [comment]
@BastiaanVanGaalen @tlle14 @BenoitTallandier 
After several discussions on this issue, it was decided to implement this flow of creating the direct group chat on the Mobile app

**Comment by tlle14** [comment]
Now we can create a group chat on Mobile. I will close this issue.
