### ISSUE TITLE
Display user mentions in messages on listing of all chats and in chat details screens 

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#355]

**Comment by bobs4462** [comment]
@BastiaanVanGaalen close this one if not relevant anymore, or expand it into user story, you can contact @EvGen94, as he worked on user mentions recently

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Have we implemented this functionality?

**Comment by bobs4462** [comment]
We have mention functionality, i.e we can user @ symbol to trigger the displays of user list when composing the message. But the title of this issue is pretty confusing, so we may not have the functionality you meant

**Comment by bobs4462** [comment]
@BastiaanVanGaalen ping
