### ISSUE TITLE
New message notification inside an open chat

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#356]

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Are we done with this functionality? When we are inside the chat flow of some channel and we receive a new message in another channel the notification should show up so user can tap on it and be redirected into a corresponding channel with auto-scroll to the message contained in notification?

**Comment by bobs4462** [comment]
Well, it's also pretty complicated, because we cannot test out for the reasons of very unstable notification functionality on backend. Leave it for now
