### ISSUE TITLE
Design workspace deletion flow in the app

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#357]

**Comment by BastiaanVanGaalen** [comment]
I will take on this task next in the context of another task:  "workspace options" where owners will be able to adjust workspace settings and to invite new members.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 
https://zpl.io/aMx4yXN

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen 
I don't see where to delete the workspace in the design. 
Could you please check again?
