### ISSUE TITLE
Create workspace > The last row of invited member isn't counted

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#358]
# Precondition
Creating a workspace

# Actual Result
The last member on the list isn't invited. 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9e6eccba-8db0-4e2e-a67d-2041ba591cdc)

While the last member is counted if the user added a blank row on the list
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/79f8cafc-02a5-41d7-9f90-f076a4d13767)

# Expected Result
The last member on the list should be counted.

# Environment
Both Android and iOS app
Build version: 2.2.9-2

**Comment by manhduc-nguyen** [comment]
@tlle14 as confirmed, only when pressing plus on the left should add to the list is common behavior, so I will only fix to avoid adding blank row

**Comment by tlle14** [comment]
Hi @manhduc-nguyen 
Retest failed!

- It's pass when avoid adding an empty row to the list 
- However, the row that is not added to the list still be counted. 

https://images.zenhubusercontent.com/309637937/e4dc63c1-2f89-47fd-9d21-eb36976d97bc/rpreplay_final1619161072.mp4

**Comment by tlle14** [comment]
Hi @manhduc-nguyen 
Retest pass!
The blank row cannot be added to the list.
