### ISSUE TITLE
Create Channel > The emoji keyboard cannot display on the small screensize

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#359]
# Actual Result
When selecting a channel icon, the emoji keyboard cannot display on a small screen
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/897be466-78cd-4dd0-8124-9ee49d2c3803)

# Expected Result
The emoji keyboard should be able to display normally

# Environment
iOS App
Build version: 2.2.9-2

**Comment by manhduc-nguyen** [comment]
@tlle14 is this ip7?

**Comment by tlle14** [comment]
Yes, it is.

**Comment by EvGen94** [comment]
Done

**Comment by bobs4462** [comment]
@tlle14 please test

**Comment by tlle14** [comment]
Welcome @etchevef :) 
Hi @bobs4462 is this fix in the newest build? 
If it already is, I cannot test because the app on ip7 crashes every time I open it. 
If it's not, I will retest in the next build. I saw the crash issue is ready to be retested next release.

**Comment by bobs4462** [comment]
Hi @tlle14, yes, it's in the new build, we are working on publishing it right now, should be available by the end of the day :)

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass!
https://images.zenhubusercontent.com/309637937/0b45dd08-d25e-47f0-afd2-94bc5536643d/rpreplay_final1619150761.mp4
