### ISSUE TITLE
When scroll to see chat history, it automatically jump to the latest message after the chat is loaded

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#361]
# Actual result
After chat history is loaded, it back to the latest message position

https://user-images.githubusercontent.com/69950655/111122976-5eb3c280-85a1-11eb-8390-e4bebf2837ae.mp4

# Expected Result
After chat history is loaded, it should stay at the date 

# Environment
Both ios and android app
Build version: 2.2.9-2

**Comment by bobs4462** [comment]
@manhduc-nguyen I can see that jump to latest message has been fixed, but now it jumps to other places, also when sending the message, the list scrolls up to the older messages instead of showing the newly sent message

**Comment by tlle14** [comment]
Thankk @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/f3c580ca-4486-4c70-aa6d-c5ca3b744502/rpreplay_final1619165051.mp4

**Comment by tlle14** [comment]
Hi @bobs4462 The issue happens again on 3.0.2. 
Please take a look

**Comment by tlle14** [comment]
Retest pass!
Thank @EvGen94 
https://images.zenhubusercontent.com/309637937/1c2e5fc4-3f5e-486d-b79e-5a48e32370d8/rpreplay_final1626163298.mp4
