### ISSUE TITLE
Create channel > Error message displays when creating a new direct chat

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#368]
# Actual Result
The first time taps on the `Create` button, the direct chat cannot be created. An error message for creating failed.
The direct chat is able to be created after the second tap.
https://user-images.githubusercontent.com/69950655/111445616-272e4d00-873e-11eb-9d0b-6a2962e1a983.mp4

# Expected Result
1. The direct chat should be created at the first tap
2. After created a direct chat, it should be on the top of a direct list 

# Environment
Both ios and android app
Build version: 2.2.9-3

**Comment by bobs4462** [comment]
> 2. After created a direct chat, it should be on the top of a direct list 

@tlle14 I'm afraid on web it doesn't jump to top either, and it's not doable right now, because directs are sorted based on their last_activity field, which is set to zero on newly created directs (which means that last activity happened 50+ years ago :D)

We can ask @RomaricMourgues if it's possible to set last_activity field to direct_creation date by default.

**Comment by RomaricMourgues** [comment]
There is two scenarios:
- For a newly created direct channel yes the last_activity should be set to creation date.
- For a direct channel already created but that was hidden I will not update the create date.
Doesn't it seems good for you ? :)

**Comment by bobs4462** [comment]
Yes, I think this solution is perfectly suitable :)

**Comment by RockinPaul** [comment]
Hi @tlle14 ,

The same reasons as for #326: unexpected backend changes and the overall instability of our API. As for the morning of March 26, it should work fine even on the previous build.
Regarding the order of freshly created directs: it should be fixed on the next backend update and has nothing to do with mobile client right now.

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass!
