### ISSUE TITLE
Notification > There's no notification on the iOS App

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#370]
# Actual Result
When sending a message to the direct chat or mentioned on the channel...., the user on iOS cannot receive the push notification.

# Expected Result
Push notification should work on iOS

# Environment
- OS: iOS App
- Build version: 2.2.9-3

**Comment by bobs4462** [comment]
Do you mean when the app is foreground, or in background?

**Comment by tlle14** [comment]
In the background running @bobs4462

**Comment by bobs4462** [comment]
Foreground notifications was added to iOS, you should get build update soon. Please write me if you catch any other abnormal behavior.

**Comment by tlle14** [comment]
I can see notifications on iOS app. Retest pass!
Thank @bobs4462
