### ISSUE TITLE
The chat screen reloads after sent an emoji message

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#372]
# Actual Result
Sent an emoji message makes the chat screen reload after 1-2 seconds
https://user-images.githubusercontent.com/69950655/111455126-feab5080-8747-11eb-808d-a2be3a573bc4.mp4

# Expected Result
The screen shouldn't reload after the emoji message is sent

# Environment
- OS: both ios and android app
- build version: 2.2.9-3

**Comment by tlle14** [comment]
Hi @bob, now the keyboard flickers instead of the chat screen, after sending an emoji 
https://images.zenhubusercontent.com/309637937/2aa82318-b078-40df-97d8-6c19211d84e8/video5ffc7dfd_6b29_47a9_b04b_4b9dc97b5d39video.mp4

**Comment by bobs4462** [comment]
Should be fixed now

**Comment by tlle14** [comment]
The issue is no longer existing.
