### ISSUE TITLE
Create Workspace > After created, the new workspace doesn't display on the member's workspace list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#375]
# Precondition
UserA is an Administrator
UserB is a Company Owner 

# Actual Result
When UserA creates WorkspaceA, invites UserB. 
On UserB's Workspace list, WorkspaceA doesn't display.

![image](https://user-images.githubusercontent.com/69950655/112268939-4c750b00-8caa-11eb-8c54-b0782ac3259d.png)
![image](https://user-images.githubusercontent.com/69950655/112269005-657dbc00-8caa-11eb-965a-29d7495c9efe.png)

After UserB creates another workspace, WorkspaceA will appear in the list.
https://user-images.githubusercontent.com/69950655/112269585-2308af00-8cab-11eb-8934-bbc52d4ff202.mp4

# Expected Result
After a new workspace is created, it should be able to display on a member's Workspace list. 

# Environment
Both iOS and Android App
Build version: 2.2.9-4

**Comment by bobs4462** [comment]
@RomaricMourgues can you please tell, what is the websocket endpoint for listening to workspace related changes?
I think we should subscribe to that endpoint in order to monitor the changes in realtime

**Comment by RomaricMourgues** [comment]
I think it is better to avoid websocket here, and load from backend each time we open the side bar what do you think?

If you want the realtime endpoint here it is:
`workspace/:workspace-id` and `group/:group-id` and `workspaces_of_user/:user-id` they are all old websockets endpoints so the same as for channels messages feed.

**Comment by bobs4462** [comment]
Agree with you, workspace creation is rare enough event, and is not worth to listen constantly. Okay, I'll discuss it with others, and we'll probably go with full reload, thanks :)

**Comment by tlle14** [comment]
Thank @bobs4462 and @RomaricMourgues 
Retest pass!
The workspace after created will display on the member's list after pull to refresh the app or reopen the company 
https://images.zenhubusercontent.com/309637937/3275488f-e422-4b27-b392-c682c5b8d3ef/videofd2e9cdc_6620_4629_ae61_3fb2396ccfeavideo.mp4

**Comment by tlle14** [comment]
I reopen this issue for the newly created workspace cannot display on the member's workspace list ... or even on the creator's workspace list but by a different device. @bobs4462

**Comment by bobs4462** [comment]
@EvGen94 please confirm that this issue is fixed and move to QA test column

**Comment by tlle14** [comment]
The new workspace displays after the member restart app. 
Are you guys going to apply automatically update when a member invited to a new workspace? @bobs4462 @RockinPaul

**Comment by bobs4462** [comment]
I'll workspace fetching when user opens the drawer, so he will always see the latest list of workspaces

**Comment by bobs4462** [comment]
I've made a change, so that the list of workspaces are updated every time user opens a side drawer.

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462 
The new workspace is updated each time opening the sidebar
