### ISSUE TITLE
The private channel name is not bold when it has a new action in the channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#379]
# Actual Result
When there has any new action in the private channel (example: send a message neither mention to anyone nor reply to a thread), the channel name is not displaying bold
![image](https://user-images.githubusercontent.com/69950655/112620401-10cd7300-8e5b-11eb-9429-d4ec670acf1b.png)

# Expected Result
It should display bold when having a new action in the channel

# Environment
iOS App
Build version: 2.2.9-4

**Comment by RockinPaul** [comment]
Isn't actual anymore due to the full redesign of this UI.
