### ISSUE TITLE
Preview message in the channel becomes `no message yet` after pulling to refresh the app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#380]
# Actual Result
When sending a message to a channel, it displays a preview message in the channel list. 
After user pulling to refresh the app, the preview message becomes the text `No message yet` but the unread counter is still displaying
https://user-images.githubusercontent.com/69950655/112621932-e8df0f00-8e5c-11eb-8592-87c183208dee.mp4

# Expected Result
The preview message should stay after pulling to refresh the app

# Environment
Both iOS and Android App
Build version: 2.2.9-4

**Comment by bobs4462** [comment]
@tlle14 Do you only see this on QA server?

**Comment by tlle14** [comment]
Hi @bobs4462 yes, only on QA server.

**Comment by bobs4462** [comment]
@RomaricMourgues I checked it on QA server, and it seems that no matter how fresh the message is in the channel, the channel itself still doesn't update it's last_message field.

**Comment by bobs4462** [comment]
@RomaricMourgues Anything here? It seems it's related to the event when QA got it's database from prod backup.

**Comment by RomaricMourgues** [comment]
Thanks for the reminder, I just fixed the db, it should be right now :)

**Comment by tlle14** [comment]
Thank @RomaricMourgues and @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/29502920-fc9b-4f2e-8fe8-a0cd2518c7d5/video34aba820_2bbd_4482_ad7a_4655abb149f6video.mp4
