### ISSUE TITLE
Unread Counter > The unread counter appears after user back from the new message thread to the channel list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#381]
# Precondition
Public channel 
User is on the thread screen

# Actual result
When there is a new message in a thread, User read it then goes back to the channel list, the unread counter is still displaying

https://user-images.githubusercontent.com/69950655/112786059-9fbad500-907f-11eb-9bf7-135ff2c4b31f.mp4

# Expected Result
The unread counter shouldn't appear when the new message has been read

# Environment
Both iOS and Android App
Build version: 2.2.9-4

**Comment by bobs4462** [comment]
I think the problem is related to bad availability of the service or bad internet connection. Anyway I added socketio (realtime) connection checks. Tell me if the problem persists.

**Comment by tlle14** [comment]
Hi @bobs4462 
I think the problem is not relating to server availability. 
It happens when you are in the thread/ message screen that the new message is displaying. Then when you come back to the channel list, the unread counter is still displaying for the new-read message. 
The unread counter doesn't disappear after you pull to refresh the app.

**Comment by bobs4462** [comment]
Oh, got it, I misunderstood the problem.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/429eb4ae-f306-4583-8966-cb269ebb7955/rpreplay_final1618565973.mp4
