### ISSUE TITLE
Direct group doesn't automatically display on Mobile after created

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#382]
# Precondition
The group chat is created on the Web
Members are on the Mobile

# Actual Result
After the group chat is created:
1. Before sending any message, the group doesn't display on other member's direct lists. 
2. After sending messages to the group, it still doesn't display on other member's direct lists on Mobile. User needs to pull to refresh the app to see it displays.
3. The unread counter doesn't show for the first unread message.

https://user-images.githubusercontent.com/69950655/112787501-da723c80-9082-11eb-8d7f-7efe1b48c8be.mp4

# Expected Result
After the group chat is created:
1. When having no message, the group should display on other member's direct list. 
The single direct chat shouldn't.
2. After sending messages to the group, the group should automatically display on other member's direct list
3. The unread counter should show for the unread message of a group. 
It shouldn't disappear after pull to refresh the app

# Environment
Both Android and iOS app
Build version: 2.2.9-4

# Environment

**Comment by bobs4462** [comment]
@RomaricMourgues Hi, can you help us out here, can we receive updates about new direct chat creation via sockeio? If yes, what is the resource address that we should listen to?
Thanks.

**Comment by RomaricMourgues** [comment]
1. It is expected
2. So for the realtime, like for other collection, you get the endpoint to listen to in the GET request used for direct channels
3. This is a bug from us, an issue exists on our side, please ignore it on Mobile it will be fixed someday :)

**Comment by bobs4462** [comment]
Ok, got it. About the second point though...
```
curl --location --request GET 'https://chat.twake.app/internal/services/channels/v1/companies/<company_id>/workspaces/direct/channels' \
--header 'Authorization: Bearer <token>'
```
We are currently requesting direct channels via the above given method, which doesn't provide the endpoint to listen to, are using the wrong method?

**Comment by RomaricMourgues** [comment]
To get the weboskcets information you need to add the ?websockets=1 query parameter ;)

https://web.twake.app/internal/services/channels/v1/companies/:company_id/workspaces/direct/channels?websockets=1

**Comment by bobs4462** [comment]
Missed that one :). Thanks :+1:

**Comment by tlle14** [comment]
Thank @bobs4462 and @RomaricMourgues 

1. After created without new messages, the direct group doesn't display on the member's direct list => Pass!
2. When having a new message, the direct group automatically displays on the member's direct list => Pass!
3. No message counter when having a new message in a direct group => Web issue. 

I should close this ticket.
