### ISSUE TITLE
Unread counter  > Timestamps on the channels and directs list are lost

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#383]
# Actual Result
The Timestamp doesn't display anymore on the Channel list or direct list
![image](https://user-images.githubusercontent.com/69950655/112800464-e289a680-9099-11eb-9718-302dc029d47e.png)

# Expected Result
The timestamp should be displayed with the unread counter. Unless the design has been changed. 
![image](https://user-images.githubusercontent.com/69950655/112799311-62af0c80-9098-11eb-9f57-6bc48a105af4.png)

# Environment
Both iOS and Android App
Build version: 2.2.9-4

**Comment by tlle14** [comment]
CC: @BastiaanVanGaalen
 hi, we need your opinion about how timestamps displaying with the unread counter on the direct list.

**Comment by bobs4462** [comment]
Hi @tlle14 Is the issue reproducible on both prod and qa servers?

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue only happens on QA server. On Production it works fine

**Comment by bobs4462** [comment]
@RomaricMourgues is this issue temporary? Currently we are getting all channels' last_activity property being set to zero on QA server...

**Comment by RomaricMourgues** [comment]
I don’t know, we are using a old backup of prod may be this is related I will take a look

**Comment by bobs4462** [comment]
Is this still reproducible?

**Comment by tlle14** [comment]
Thank guys, 
no more issue on the newest version
![image](https://user-images.githubusercontent.com/69950655/114810732-e413d800-9dd6-11eb-9d39-96c8a112fdfb.png)
