### ISSUE TITLE
Direct group order is changed after pulling to refresh app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#384]
# Actual Result
When having a new message in a direct group, the direct group jumps on the top of the direct list. 
But after pulling to refresh app, the direct group becomes unbold and changes its position in the list. 

https://user-images.githubusercontent.com/69950655/112803220-41045400-909d-11eb-8098-89c8137a0681.mp4

# Expected Result
When having a new message, the direct group should be bold and on top. It should keep the state even after pulling to refresh the app. 
After new messages are read, the direct group should keep its position until having new messages in another direct.

# Environment
Both ios and android app
Build version: 2.2.9-4

**Comment by bobs4462** [comment]
@tlle14 Are still able to reproduce this issue?

**Comment by tlle14** [comment]
Retest pass!
Thank @RockinPaul and @bobs4462 

https://user-images.githubusercontent.com/69950655/114811146-c5faa780-9dd7-11eb-82e0-62699eae18eb.mp4

**Comment by tlle14** [comment]
I reopen this issue for the incorrect order on the mobile app (build version: 2.2.9-7)
https://images.zenhubusercontent.com/309637937/ccf70955-efd9-4db0-91be-5da39384249a/rpreplay_final1619515639.mp4

**Comment by tlle14** [comment]
No more existing on 2.2.9-8
