### ISSUE TITLE
Notification > Notification doesn't work on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#385]
# Actual Result
There's no push notification for mobile app

# Expected result
Please fix the issue. 
Notification should appear when mentioned or comment on a thread user relates to. 

# Environment
Both ios and android app
Build version: 2.2.9-4

**Comment by RomaricMourgues** [comment]
I thinks it is on us, I'm on it

**Comment by RomaricMourgues** [comment]
@bobs4462 can you check if you are sending the device 'type' and 'value', and also on which route (/login or users/current/get or both)

**Comment by RomaricMourgues** [comment]
It seems I don't get the device on the current/get endpoint:
```
PHP message: [Router] - POST /ajax/users/current/get"
PHP message: device: false"
```

I do receive it in /login but it will not work with console in this case (because for console we don't use this route)

**Comment by RomaricMourgues** [comment]
I fixed this issue (soon on production), but the "/ajax/users/current/get" questions still persists :)

**Comment by bobs4462** [comment]
When we authenticate via internal mode we send this 
```
{ 
   _username : username,  
   _remember_me: true,  
   'device': { 
      'type': "fcm",  
      'value': fcm_token,  
      'version': '2020.Q3.107'
    }
}
```
to `/ajax/users/login`
Then we receive access token and make another POST request to `/ajax/users/current/get` using the token and body contains only timezoneoffset parameter

**Comment by bobs4462** [comment]
Well, when we use auth mode console, the workwflow is basically the same except that we authenticate by token which we receive from twake console, and not by password.

**Comment by bobs4462** [comment]
There's also a prolongation method on proxy, which uses the same `POST /ajax/users/login`, but with refresh token instead of access one, and the request body only contains 
```
{ 
   'device': { 
      'type': "fcm",  
      'value': fcm_token,  

      'version': '2020.Q3.107'
}
```

**Comment by RomaricMourgues** [comment]
So it is fine on your side, and my fix will come soon

**Comment by RomaricMourgues** [comment]
Our fix is on production (and on QA soon).
To have it working, don’t forget to login again.

**Comment by tlle14** [comment]
Hi @bobs4462 
I saw push notification doesn't work on Android for the newest build. Could you please check?

**Comment by tlle14** [comment]
@RomaricMourgues @bobs4462 could you please take a look? The notification feature doesn't work on QA environment

**Comment by tlle14** [comment]
@bobs4462 It doesn't not work on iOS so I cannot close the ticket
