### ISSUE TITLE
Add workspace button displays on Choose Company sidebar

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#388]
# Precondition
Login as Admin

# Actual Result
On the company list, the `Create Workspace` button is displaying on the top of the sidebar
https://user-images.githubusercontent.com/69950655/112931295-17533780-9146-11eb-8e85-993b691c9d5e.mp4

# Expected Result
The button shouldn't display on the company list. 
It should display on Workspace list only.

# Environment
On both android and ios app
Build version: 2.2.9-4

**Comment by RockinPaul** [comment]
Has nothing to do with the new design, where we got rid of the side menu at all. The future destiny of choosing a company will be discussed with @BastiaanVanGaalen
