### ISSUE TITLE
A long channel name cannot display on a regular/small screen size

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#390]
# Actual Result
The channel name is too much cut on regular or small screen size.

**On 6.1 inches screen:**
![image](https://user-images.githubusercontent.com/69950655/113085680-7bd7ca80-920a-11eb-8d23-2a46ec36035a.png)
![image](https://user-images.githubusercontent.com/69950655/113085179-8a71b200-9209-11eb-8489-15cabc33f3b0.png)

**On 6.5 inches screen:**
![image](https://user-images.githubusercontent.com/69950655/113085261-b42ad900-9209-11eb-9794-4c6b0c9cbd18.png)

# Expected Result
The channel name should display longer

# Environment
Server: Production
Device: iPhone 12 - screen size 6.1 inches
Build version: 2.2.9-4

**Comment by RockinPaul** [comment]
Isn't actual anymore due to the full redesign of this UI.
