### ISSUE TITLE
Channel list > UI collapse when the preview message has multiple lines

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#391]
# Actual Result
When the newest message has multiple lines, its preview in the channel list makes UI collapse on Android and looks complex on iPhone. 

On android
![image](https://user-images.githubusercontent.com/69950655/113105971-670c2e80-922c-11eb-8df6-627f18399dc3.png)

On iPhone
![image](https://user-images.githubusercontent.com/69950655/113106106-902cbf00-922c-11eb-93cc-4a826ea8f10c.png)

# Expected Result
The preview message should have limited characters, without a line break.

# Environment
- Server: Production
- Both Android and ios app
- Build version: 2.2.9-4

**Comment by tlle14** [comment]
Also see https://github.com/linagora/Twake-Mobile/issues/440
Since we have many feedbacks from users about this issue, I should increase the priority of the issue. 
Please fix it soon. @RockinPaul

**Comment by RockinPaul** [comment]
Makes no sense due to the full redesign of this page.

**Comment by RockinPaul** [comment]
@tlle14 it won't be fixed in the current design anyway, take it easy :)

**Comment by tlle14** [comment]
Thank @RockinPaul for your confirmation. This should be closed.
