### ISSUE TITLE
Open a message link redirects to the web instead of a message in the app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#393]
# Precondition
The link is a message in a channel 

# Actual Result
When tap to open the link, it redirects to the corresponding message on Browser, not open the message in-app
https://user-images.githubusercontent.com/69950655/113111047-f536e380-9231-11eb-8fc7-19bfa2bf3c6d.mp4

# Expected Result
It should open the message in app

# Environment
- Server: Production
- Both Android and iOS app
- Build version: 2.2.9-4

**Comment by bobs4462** [comment]
This one is pretty big and deserves entire user story and coordination with twake core. Closing for now, as it will not be implemented any time soon
