### ISSUE TITLE
iOS > App crashed when open the web view on app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#396]
# Actual Result
When opening the web view on App with complex behavior, kill the app then reopen, the app crashed.
Please see the below video:
https://user-images.githubusercontent.com/69950655/113278610-559a5380-930c-11eb-84d0-4a80b913f71d.mp4

# Steps
1. Open App > Login screen
2. Tap `Sign Up`
3. Tap `Privacy` on the bottom of Sign up screen
4. Scroll the privacy screen
5. Tap to chat icon Crisp
6. Tap to open Emoji keyboard: switching between smileys and gifs
7. Close the Crisp screen
8. On the Privacy screen, open the hambuger menu
9. Kill the app
10. Reopen the app 
Verify the app crashed

# Expected Result
Please investigate. 
The app should be stable.

# Environment
iOS App
Build version: 2.2.9-4

**Comment by bobs4462** [comment]
Hi @tlle14 Is the issue reproducible on android too, or is it only iOS specific?

**Comment by tlle14** [comment]
It seems only on iOS. For now, I still cannot reproduce on android.

**Comment by bobs4462** [comment]
@tlle14 I think we can close this one

**Comment by tlle14** [comment]
Rightttttttt @bobs4462
