### ISSUE TITLE
User feedback > Channel emoji is not fit

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#400]
# Actual Result
The channel emoji is too large that overflow on the channel list screen.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/423f21ff-752b-436b-8df7-40fb1e97e0f1)

# Expected Result
The channel icon should be fit

# Environment
- Device:Xiaomi Mi 5X - Android 8.1.0
- Build version: 2.2.9-5
- Server: Production

**Comment by RockinPaul** [comment]
Not actual anymore due to the full redesign of this UI.
