### ISSUE TITLE
No messages when opening the channel

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#401]
When switching workspaces and opening channel, it shows no messages, though channel definitely has some messages. The issue seems spontaneous and not always reproducible.

**Comment by tlle14** [comment]
Hi @bobs4462 
I got a problem when opening a channel on production. It displays a grey screen
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/238bdd55-34c2-4792-a3c7-dca80b7bf22d)

This issue may relate to bot-message from Github. Please check.

**Comment by bobs4462** [comment]
Can you please add me to this channel, so I can investigate what might be going wrong in there

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed!

We still have trouble with displaying chat history when the channel has a poll
On Mobile:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/fc635608-5485-4743-8fdf-1ffa1468e6fb)

On the Web:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2d2460d5-efa3-42b8-a3d6-12c3ca72be98)

**Comment by bobs4462** [comment]
@BastiaanVanGaalen help us out here, we need a visual design for user created polls, I think you can consult Benoit about how polls work now, and if they are going to change in near future.

**Comment by bobs4462** [comment]
I fixed the issue temporarily by not rendering interactive elements for now. Because:
1. We don't have design for them yet
2. Romaric and others are reworking the twacode into new Block based structures which is going to be future format for those interactive elements (like buttons, polls, video calls etc.).

**Comment by tlle14** [comment]
Hi @bobs4462 
Is this your temporary solution? I cannot close this ticket since it only displays all messages before the poll (I only agree that I hate calendar team, they always use the poll >"< ) 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/99f442b2-5075-4eb5-90de-3cec79991d1a)

How about rendering the poll as an empty message, then the before messages is still displaying normally.

**Comment by bobs4462** [comment]
I fixed it, should out be in the next build

**Comment by bobs4462** [comment]
The issue was, that there's no consistent format for twacode items for now, everything is so dynamic, that it's hard to foresee and account for every possible scenario. Polls for now should just render not supported text.

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/37347ec7-1ba2-4dac-a582-855f90a7cebb)
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/18c2e18b-e814-4f65-bd4f-f9e28ed3df1b)
