### ISSUE TITLE
My writing message disappear when I receive a new message in a thread

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/Twake-Mobile#402]
I tried the last mobile version, in a thread replies, I was writing a message and my message disappear when the someone post a new message in the thread!

IOS device

**Comment by bobs4462** [comment]
@tlle14 I believe that this issue was "accidentally" fixed during redesign, can you please test it with real devices?

**Comment by tlle14** [comment]
Retest pass!!!!
Thank @bobs4462 
https://images.zenhubusercontent.com/309637937/a3cfc801-46e5-4bf2-bd87-5e894637602f/rpreplay_final1620296148.mp4

@fabienmoyon I've never been able to reproduce this issue. So please tell us if it is still existing in the next release. Thank you ;)
