### ISSUE TITLE
Unable to create self-direct chat on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#411]
# Actual Result
The user is unable to create a self-direct chat. 
After selected his name, the app always opens the first chat in the direct list.

https://user-images.githubusercontent.com/69950655/113562948-29931100-9631-11eb-82e0-0b67015150eb.mp4

# Expected Result
Compatible with the Web version, user should be able to create a self-direct chat

# Environment
- Both iOS and Android App
- Build version: 2.2.9-5
- QA environment

**Comment by tlle14** [comment]
Hi @EvGen94 
This issue still happens on 3.0.2. 
When select to create a self-direct-chat, it opens a random direct chat

https://user-images.githubusercontent.com/69950655/124859528-4ea17200-dfda-11eb-93f7-8e7b3741a749.mp4

**Comment by manhduc-nguyen** [comment]
@bobs4462 I checked the api, it returns Pavel's account when create self direct (I'm using your account bobs4462@gmail.com)

curl `curl --location --request POST 'https://web.qa.twake.app/internal/mobile/direct' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY4NDE2ODksInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2MjY4Mzc0ODksIm5iZiI6MTYyNjgzNzQ4OSwic3ViIjoiNTMwMjg4MTgtMzIyNy0xMWViLThmOGItMDI0MmFjMTIwMDA0IiwiZW1haWwiOiJib2JzNDQ2MkBnbWFpbC5jb20ifQ.YPPFB97jCYbeTzxyk1q-SlrRB4qIxDQixm6wrf1G-vA' \
--header 'Content-Type: application/json' \
--data-raw '{
    "company_id": "ab441952-8d3e-11eb-9f13-0242ac120005",
    "member" : "53028818-3227-11eb-8f8b-0242ac120004"
}'`

**Comment by bobs4462** [comment]
hmmm, that's strange, ok, just push your code, I'll be migrating channel endpoints anyway to make direct requests to twake backend, so I'll take a look at it then

**Comment by manhduc-nguyen** [comment]
> hmmm, that's strange, ok, just push your code, I'll be migrating channel endpoints anyway to make direct requests to twake backend, so I'll take a look at it then

Oh, no code changes needed

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/64c57bcc-dbf9-442c-8a09-622997bfa81f/video96e196d8_cdbe_4d29_a551_ead5ec2dcad6video.mp4
