### ISSUE TITLE
There is no informing to user about sending message's failed

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#412]
# Actual Result
Recently, there's a problem that unable to send a message. But the user doesn't know until he pulls to refresh the app then sees the sent messages are lost.

https://user-images.githubusercontent.com/69950655/113566826-a2956700-9637-11eb-8b78-7a599187b5ef.mp4

# Expected Result
There should be a sign for unsuccessfully sending messages.
The unsuccessfully-sending message better be saved on the screen with a retry-sending button.

# Environment
- Both Android and iOS app
- Build version: 2.2.9-5
- QA environment

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 @RockinPaul Didn't we agree last week guys on showing "clock" icon next to the message bubble as the indication of deferred delivery status (waiting to be send) in order to unburden users of re-freshing and re-sending message themselves?

**Comment by RockinPaul** [comment]
@BastiaanVanGaalen If so, could you please provide us with how it looks like?
The only place where I've found the clock icon is here: ![изображение.png](https://images.zenhubusercontent.com/5ffc24a2a62ff7cf134e10b3/cf8da1e2-2348-4786-9306-d7e56fc4bfb4)

**Comment by tlle14** [comment]
Hi @bobs4462 and @EvGen94 
In no internet connection condition, after submitted, the message is lost.
Expected result: The message should display with the red exclamation mark.

**Comment by tlle14** [comment]
Thanks,
Retest pass
![screenshot_27.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/10902242-324d-421c-8c75-c004fd7045c8)
