### ISSUE TITLE
Preview message reveals the deleted one

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#415]
# Actual Result
When a user posts a new message to the channel, it will display as a preview in the channel list. 
After a user deletes that message, the preview is still staying

https://user-images.githubusercontent.com/69950655/113966983-4cecd480-985a-11eb-8089-7acc359ff531.mp4

# Expected Result
The preview shouldn't show the deleted message. 
It should be the previous one or the title "The message was deleted"...

# Steps
1. Send a new message to a channel
2. Navigate to the channel list, see the message preview
3. Delete the newly posted message
4. Go back to the channel list, verify the preview message is the deleted one.

**Comment by bobs4462** [comment]
@RomaricMourgues, can I try to solve this issue myself, as I understand we need to add another subscription for the channels service, so that if the last message is deleted or modified, we update the last_message accordingly, correct me if I'm wrong.

**Comment by RomaricMourgues** [comment]
You also need to verify if the message is the last one, if someone edit an old message in the history you must not update the last_message parameter.
I would be better to wait for the new message api because a lot of things are going to change:
https://github.com/linagora/Twake/pull/1101

**Comment by bobs4462** [comment]
Ok, then let's wait for the complete merge of the new messaging API, and then we'll go through this issue once more. For now I'll postpone it.

**Comment by bobs4462** [comment]
@RomaricMourgues a quick reminder here :)

**Comment by RomaricMourgues** [comment]
Created here: https://github.com/linagora/Twake/issues/1428

**Comment by RomaricMourgues** [comment]
I consider this as a minor issue if you don't mind ? :)

**Comment by sherlockvn** [comment]
# The problem is already fixed.



https://user-images.githubusercontent.com/43041967/160811228-43be8e87-ad60-4094-8707-fda0f8a7ca2f.mp4


# Environment
Build version: 1.0.7
Device:
    Google Pixel 4 - Android 11.0 x86 - 5.7 inch
    QA environment
