### ISSUE TITLE
Message > Cannot display the message contains script on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#419]
# Actual Result

On Web:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/cd316acd-2e08-48b8-9894-7cab9916a13f)

On Mobile: 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/044e03e8-3177-4f83-86b7-62b940c982e5)

# Expected Result
Please find a way to display the scripts also avoiding XSS attacks. 

# Environment
Both Android and iOS
Build version: 2.2.9-5

**Comment by bobs4462** [comment]
@tlle14, what's the issue here? I believe it's now possible to render such a content, or am I missing something?

**Comment by tlle14** [comment]
I retested this issue. It's no longer appear
![image](https://user-images.githubusercontent.com/69950655/114996276-df2f5100-9ec8-11eb-956a-bf7ac1be9c98.png)
