### ISSUE TITLE
Message > formatted message is not displaying well on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#420]
# Actual Result
1. A quoted message is displaying as the highlighted

2. The iOS keyboard doesn't allow to input the grave accent `

3. A highlighted message is displaying less contrasting 

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/8804fa47-3570-4bda-ad51-547d3c434479)

# Expected Result
1. A quoted message should display obviously as a quote.
Like having a quote block or vertical line or in italic font...

2. The iOS keyboard should allow inputting the grave accent for composing a highlighted message

3. A highlighted message should be a real highlighted one as on the Web. 

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a6b68339-e5d3-448f-8f08-72a6ba5ddf1a)

# Environment
iOS or Android device
Build version: 2.2.9-5

**Comment by bobs4462** [comment]
@tlle14 Hi, regarding the second point, are you sure there's no way to access backtick (backquote | grave accent) from iOS keyboard?
https://apple.stackexchange.com/questions/1808/is-there-a-backquote-on-the-iphone-keyboard - can you try to follow instructions from this post

**Comment by tlle14** [comment]
> @tlle14 Hi, regarding the second point, are you sure there's no way to access backtick (backquote | grave accent) from iOS keyboard?
> https://apple.stackexchange.com/questions/1808/is-there-a-backquote-on-the-iphone-keyboard - can you try to follow instructions from this post

Thank @bobs4462 But a low-tech user cannot do. If you can fix, kindly make it always available for user.

**Comment by bobs4462** [comment]
I don't really think that's up to us, Apple designed this keyboard...
I'll ask Pavel to think of solution, but most likely there's none.

**Comment by tlle14** [comment]
I checked the other app, they are the same as ours.
Thank @bobs4462 for your explanation. This is not a bug
