### ISSUE TITLE
Extract name from 'text' field of lastMessage

### ISSUE THREAD

**Issue by RockinPaul** [linagora/Twake-Mobile#433]
Right now we have:
lastMessage: {date: 1616168929000, text: Test Bot: Hi everyone}

We need something like that:
lastMessage: {date: 1616168929000, text: Hi everyone, name: Test Bot}

In order to comply with the new design:
![изображение.png](https://images.zenhubusercontent.com/5ffc24a2a62ff7cf134e10b3/4924f8fc-48f7-46cd-8557-e9f4207721b3)

**Comment by bobs4462** [comment]
In new design you can see, that in channels' list, each channel has last message preview, and username and the message by that user is displayed differently, if you can confirm that on all servers, you can close this issue.

**Comment by tlle14** [comment]
It works fine on both QA server and Production
Thank @bobs4462
