### ISSUE TITLE
Add application (bot) messages support in Mobile app

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#434]

**Comment by bobs4462** [comment]
FT - Twake channel should now render properly

**Comment by tlle14** [comment]
How can I test this ticket? @bobs4462

**Comment by bobs4462** [comment]
Any channel with bot messages (gitlab, n8n) should now render all messages, both from users and from bots alike.

**Comment by tlle14** [comment]
> Any channel with bot messages (gitlab, n8n) should now render all messages, both from users and from bots alike.
> 
> FT - Twake and SmartSlaa are examples of such channels

I got it. Thank @bobs4462 
The links in the bot-message are not highlighted. could you please check their format?
![image](https://user-images.githubusercontent.com/69950655/114855113-c6169980-9e0f-11eb-8a41-31a35b4e5566.png)

**Comment by bobs4462** [comment]
Yes, I noticed that too. Messages from bots are tricky, as they don't conform to the format used by ordinary users. I'll work on correct formatting in another ticket (#405).

**Comment by tlle14** [comment]
Thank @bobs4462 
I should close this one.
