### ISSUE TITLE
Message preview overlaps other channel information if message content is long and includes URL

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake-Mobile#440]
As you can see from the screenshot, message preview of FT - LinID DM channel overlaps FT - Linshare and FT - Mobile channels

The message from LinID channel is long and inclues URL as below:
![1618286226027](https://user-images.githubusercontent.com/53081477/114494731-0bd43600-9c47-11eb-9334-5e56473322e1.JPEG)

![1618284625837](https://user-images.githubusercontent.com/53081477/114494451-a122fa80-9c46-11eb-93fb-772cbc1f142a.JPEG)

**Comment by tlle14** [comment]
Duplicate with https://github.com/linagora/Twake-Mobile/issues/391
