### ISSUE TITLE
Unable to see file attachment

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake-Mobile#441]
1. Send a message with file attachment on Twake web
2. Go to Twake app to view the above message

Expected result:
User is able to see the file attachment 

Current behavior: 
Unable to see attachment, just see the text

What we see on Twake web
![IMG_0169](https://user-images.githubusercontent.com/53081477/114497194-c403dd80-9c4b-11eb-95f7-02356db10246.png)

Twake mobile:
![1618288325374](https://user-images.githubusercontent.com/53081477/114497255-ebf34100-9c4b-11eb-9496-f984cefa2c50.JPEG)

**Comment by bobs4462** [comment]
@BastiaanVanGaalen can you provide us with design of how attached files should look like when combined with text. Currently we only have mocks for the single files (without text). Also it'd be nice to have a look of it, when it's sent by the user himself and by the others.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 https://zpl.io/a7PxZgp
Please, Sir!

**Comment by tlle14** [comment]
The attachment file has been rendered in a message but having some UI issue. I will log in another ticket
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e17cbc2a-de2c-4736-a599-72d176ea7fc0)
