### ISSUE TITLE
There should have an update between the new app and the old installed app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#447]
# Precondition
- The old app is installed on the device by apk file
- The new app is on the Play Store 

# Actual result
When open the Play Store, the app on Play Store displays as if it is updated to the newest version. 
![image](https://user-images.githubusercontent.com/69950655/114654890-4efcda80-9d15-11eb-9377-97559b0a59c5.png)

# Expected Result
The app on Playstore is newer, it should display an update button. 

# Environment
Android App on App Store
Build version: 2.2.9-1 vs. Playstore app.

**Comment by romanesko** [comment]
And how we are supposed to do this? It's a play store behaviour

**Comment by tlle14** [comment]
Okay, thank @romanesko 
This is not an issue.
