### ISSUE TITLE
User feedback > When entering the app, it should have a screen for choosing Company/Workspace instead of visiting the random place.

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#448]
# Actual Result
User Feedback: 
```
My first feedback is that at the first connection we should present the different organizations and then choose a workspace.
Because there, we arrive on a random channel I think that is not necessarily relevant.
```

# Expected Result
Please discuss with our UX Designer, BA and PO if we need to improve as the user suggestion.

# Environment
Android App on Play Store
Build version: 2.2.9-5

**Comment by tlle14** [comment]
@PokoinikRWS @BastiaanVanGaalen please take a look

**Comment by bobs4462** [comment]
@BastiaanVanGaalen please take a look at this. If you don't think that this issue should be addressed, please close it. 
Right now, if user logs in for the first time, we choose his first company and first workspace in that company (just like web) and then we persist selection across restarts.

**Comment by RockinPaul** [comment]
Dear @BastiaanVanGaalen  , the task is still here and doesn't seem to be going anywhere without your participation.

**Comment by BastiaanVanGaalen** [comment]
To my knowledge, users are invited to join a particular workspace inside a particular company. So there is no point for users to select something since our service is invitation-based.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462

**Comment by bobs4462** [comment]
We can implement it if you want, from UX perspective it's up to you ultimately to decide (I'm not good at those things :)). Currently we pick first company and first workspace (whatever they are) when user logs in for the first time

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Please, confirm the case, user can see the listing of available workspaces, ha can select one and will be redircted to channel listing? is that correct, please confirm.

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen
Yes. The user can see the available workspace list, he can select a workspace then it will display the corresponding channel list.
 
As I understand, the feedback is about **the first time login to the app**, the user wants to be able to choose a company > choose a workspace of the company instead of going to a random place (used to)

Now when we first-time login to the app, the user will redirect to the first workspace of the first company in the list which is sorted by alphabetical order.

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen @bobs4462 Do you have any update on this ticket? We got another feedback about choosing a company (when the user has more than 1 company) right after login, instead of open the first company in the list. 
You can check the feedback on Feedback Twake Mobile channel.
