### ISSUE TITLE
User Feedback > Pre-loading system or local-cache for the app when switch between companies or workspaces

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#449]
# Actual Result
User feedback:
```
Then, the change of workspace and channel induces a loading of a few milli or seconds. Can't we implement a pre-loading system or a local cache on the app?
```

# Expected Result
Please have a look at this. The loading time should be reduced
The local cache might cause an issue relates to login:
https://github.com/linagora/Twake-Mobile/issues/291
https://github.com/linagora/Twake-Mobile/issues/252

# Environment
Android App on Play Store
Build version: 2.2.9-5

**Comment by tlle14** [comment]
@bobs4462 @PokoinikRWS @RockinPaul @manhduc-nguyen

**Comment by bobs4462** [comment]
We tried to cache everything at first, but then there's an issue of syncing all the new events that we missed (like workspace or channel addition/editing/deletion), so we need to sync all the data just in case if other sync mechanisms failed. 
I agree that it very negatively affects user experience, but before we have a reliable (100 % cases) way to sync all the changes between clients, we cannot use local cache only. For now local cache is implemented to only provide offline capabilities to the application. 

I'll postpone this issue for now

**Comment by tlle14** [comment]
Thank @bobs4462

**Comment by bobs4462** [comment]
Everything is cached now, so this should not be an issue anymore

**Comment by tlle14** [comment]
Hi @bobs4462 
I still see a latency white screen while switching back to the workspace (with lots of channels but none of them has messages). 
This should be an improvement, not an issue. 
https://user-images.githubusercontent.com/69950655/123733975-ab0fdd80-d8c6-11eb-9ec1-0784ef31d995.mp4

**Comment by bobs4462** [comment]
It's already fixed, you should be able to test it in the next build

**Comment by tlle14** [comment]
We have a loading message screen 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/83cfae63-c52f-49b1-89f2-e7ea67b5d57f)
