### ISSUE TITLE
User Feedback > The app should have mark as read/unread

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#450]
# Actual Result
User feedback:
```
[FEATURE REQUEST] Also, it's not possible to mark all unread messages as read in a channel.
```

# Expected Result
Please discuss if we should have "Mark all as read/unread" as on the Web version in the next release. 

![image](https://user-images.githubusercontent.com/69950655/114676921-fc7ee680-9d33-11eb-8b72-8d57e4faf139.png)

**Comment by bobs4462** [comment]
@BastiaanVanGaalen can you please take a look at that and come up with design suggestion?

**Comment by BastiaanVanGaalen** [comment]
Can we somehow evaluate the usefulness of this feature? Is there any point for this?

Personally, me i see much more sense  in having some channels pinned to the top "add to favourites" and i'd rather
implement this one first, but for this UI needs to be prepared) so.

**Comment by tlle14** [comment]
Hi @RomaricMourgues you asked for this feature, could you please answer Bastiaan? 
CC: @BenoitTallandier

**Comment by BenoitTallandier** [comment]
@BastiaanVanGaalen I agree with you, this is not a priority feature. Furthermore, this would become almost useless when we'll  be able to bookmark a message (~ save it to read or answer later).

**Comment by EvGen94** [comment]
@tlle14 Hello! 
I guess we can close this one, this is not relevant
