### ISSUE TITLE
When change the server address, the app keeps loading when the user opens it

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#455]
# Precondition
- The user has already logged in to the app
- The server address was: <server_address_1>

# Actual Result
When the server address is changed to <server_address_2>, the user opens the app but it keeps loading. User cannot enter to the app.

# Expected Result
It should force the user to logout from the app instead of keep loading app when it has an invalid server

# Environment
Android app
Build version: 2.2.9-6

**Comment by bobs4462** [comment]
Hi @tlle14, do you mean the server change from mobile.twake.app to chat.twake.app for example?
If so, such a thing should not really happen. We did it once to integrate proxy into main twake api.

**Comment by tlle14** [comment]
> Hi @tlle14, do you mean the server change from mobile.twake.app to chat.twake.app for example?
> If so, such a thing should not really happen. We did it once to integrate proxy into main twake api.

You mean it will never happen on production?

**Comment by bobs4462** [comment]
Well, it's hard to say that it will never never happen, but it's the same as if facebook decided to change their host. It might happen, but the chances are, that it won't. And if it does in production, we'll know about it way ahead of time, and will prepare the application before that happens.

**Comment by manhduc-nguyen** [comment]
@tlle14 yes I agree with @bobs4462 . I think we can skip this for now.

**Comment by tlle14** [comment]
This ticket will be fixed when the developer team has time. 
That why I moved it to the icebox column

**Comment by bobs4462** [comment]
I think we can close this one, because host server changing URL is something that's pretty unlikely and we cannot differentiate between whether server's URL is changed and if the server went down for a few minutes

**Comment by tlle14** [comment]
Okay @bobs4462
