### ISSUE TITLE
Edit channel > Search member function doesn't work

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#458]
# Actual Result
When searching for a member to add to the channel, it doesn't return any result.
https://user-images.githubusercontent.com/69950655/114845751-37514f00-9e06-11eb-8db8-ddc59ab0db90.mp4

# Expected Result
It should return the matching result when searching for members to add to the channel

# Environment
Android App
Build version: 2.2.9-6

**Comment by romanesko** [comment]
api response format was changed 

fixed

**Comment by tlle14** [comment]
Retest pass!
https://images.zenhubusercontent.com/309637937/1cb418fb-cf52-4b13-9a2f-429935c4c5c9/rpreplay_final1619079406.mp4
