### ISSUE TITLE
It allows to create a duplicated channel name and privacy but the duplicated channel doesn't show.

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#460]
# Precondition
The channel named "Fish" is created

# Actual Result
When creating another channel with the same name and privacy, it is able to create successfully. But the new channel doesn't appear in the channel list. 

https://user-images.githubusercontent.com/69950655/114971300-4091f880-9ea6-11eb-9464-e6b68ea6a7dc.mp4

# Expected Result
I checked with the Web version, it is able to create a channel with duplicated name and privacy
For mobile, it should display the channel with duplicated name. 
![image](https://user-images.githubusercontent.com/69950655/114970548-d9c00f80-9ea4-11eb-81c5-3cde02224dfb.png)

# Environment
Android App
Build version: 2.2.9-6

**Comment by romanesko** [comment]
![IMG_9599.PNG](https://images.zenhubusercontent.com/5ffc2be36713670ebf05d4f9/0739b3c7-5858-4ba9-acfc-b146c5ea13e2)

**Comment by tlle14** [comment]
Thank @romanesko 
Retest pass
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2bbad79c-5db0-4257-b68d-c5d9e754f2eb)
