### ISSUE TITLE
Adding member button is not obvious to the user 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#466]
# Actual Result
The (+) button to add a member to the inviting list is always be mistook with the button to add a new line. 
The user may put the last member then forget to submit.  
![image](https://user-images.githubusercontent.com/69950655/115012624-41448200-9eda-11eb-8777-7a99f65382ed.png)

It causes the issue: https://app.zenhub.com/workspaces/twakemobile-5fa5101d98879700119ccea9/issues/linagora/twake-mobile/358

# Expected Result
Please work with our UX designer to improve this feature.
(I suspect if our DEV team misunderstand the Designer's idea)

# Environment
Mobile App
Build version: 2.2.9-6

**Comment by bobs4462** [comment]
not relevant anymore due to redesign
