### ISSUE TITLE
Password Recovery screen > The keyboard always capitalize the first letter in the Email text field 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#468]
# Acutal Result
When tapping on the Email text field, the keyboard displays with capitalizing mode as a default
![image](https://user-images.githubusercontent.com/69950655/115180207-46364b00-a0ff-11eb-8035-ade5bf18cc0e.png)

# Expected Result
The keyboard should display without capitalizing the first letter. 

# Environment
Android App
Build version: 2.2.9-6

**Comment by manhduc-nguyen** [comment]
@tlle14  The screen is a webview. I took a research, I don't think we can change this behavior.

**Comment by tlle14** [comment]
I asked Console DEV team. I hope they can help. 
Thank @manhduc-nguyen

**Comment by tlle14** [comment]
emeral
