### ISSUE TITLE
The internet connection banner hides action buttons

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#469]
# Actual result
When opening adding member screen/ create a direct channel screen without an internet connection, the warning banner displaying hides the action buttons
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/ebc3b2f3-ef6d-4f65-b39b-d10bf6fb70c0)

# Expected Result
The banner shouldn't hide the action buttons

# Environment
Android app
Build version: 2.2.9-6
QA environment

**Comment by bobs4462** [comment]
We will rework entire logic for the connection loss cases
