### ISSUE TITLE
Create Workspace > The invited list stays on the form after created a new workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#472]
# Precondition
Create a workspace and invite some people

# Actual Result
When open the create workspace form again, the invite member screen still keeps the old data. 
https://user-images.githubusercontent.com/69950655/115198546-5f012980-a11c-11eb-97f4-0e5b4dc57ad5.mp4

# Expected result
Data on the creation form should be cleared after created successfully

# Environment 
Both Android and iOS app
Build version: 2.2.9-6
QA environment

**Comment by EvGen94** [comment]
@tlle14 Good day  
I can't catch this problem, does it occurs after new workspace created successfully? Because the newly opened invited list is clean. Сould you please check it out ?

**Comment by tlle14** [comment]
Hi @EvGen94 
Kindly check out this video:


https://user-images.githubusercontent.com/69950655/115690019-d4703280-a386-11eb-9441-e0a6441b9502.mp4

**Comment by tlle14** [comment]
Thank @EvGen94 @manhduc-nguyen 
Retest pass!

https://user-images.githubusercontent.com/69950655/117261800-c3411e80-ae7a-11eb-8d75-4e22910b3865.mp4
