### ISSUE TITLE
Create Workspace > Back button works incorrectly in Adding Member screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#474]
# Actual Result
The `Back` button is able to save the change in Adding Member screen
https://user-images.githubusercontent.com/69950655/115208734-1602a280-a127-11eb-93a5-61c20d5e1f1b.mp4

# Expected Result
After tapping the `Back`button, it shouldn't save the change in Adding Member screen

# Reproduce
1. Open Add Workspace screen 
2. Open Add member screen
3. Input the member list
4. Tap on the Back button
5. Open the Add member screen again
6. Verify data is saved 

# Environment
Both Android and iOS App
Build version: 2.2.9-6
QA environment

**Comment by tlle14** [comment]
Hi @EvGen94 
Retest failed!
When there's a record that wasn't added to the list, the list is not cleared when it is reopened. 
https://images.zenhubusercontent.com/309637937/99141f7f-bcd0-4fb9-9b4a-5e01fb802d2f/rpreplay_final1619150203.mp4

**Comment by EvGen94** [comment]
@tlle14 Good day!
Could you please specify how exactly you go back because I do not see the pressing of the "Back" button and if you go back using "Back" is the sheet still filled?

**Comment by tlle14** [comment]
Hi @EvGen94 
Please refer this video 
https://images.zenhubusercontent.com/309637937/532fb4f5-040e-4a3c-9496-543f3149d94c/video7100b203_a934_4a52_9c0a_233fd1ed09e4video.mp4

**Comment by EvGen94** [comment]
@tlle14 
Thanks! now I understand why I did not see this behavior, because I always finished filling completely and pressed the back button from an empty line, in this case the fix works fine.
I will fix it.

**Comment by EvGen94** [comment]
Hi @tlle14, the bug has been fixed in the latest build, can you test it out?

**Comment by tlle14** [comment]
Hi @EvGen94 

Retest failed!
When **there's a record that wasn't added to the list**, the list is not cleared when it is reopened. 
Tested on 2.2.9-7 - QA environment (web.qa.twake.app)

**Comment by tlle14** [comment]
Thank @bobs4462 @EvGen94 
Retest pass!
https://images.zenhubusercontent.com/309637937/dea731ec-f0ae-44e4-98fe-aa6019d3ea3f/rpreplay_final1620203497__1_.mp4
