### ISSUE TITLE
When open an unread messages list, it doesn't focus on the first unread message

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#475]
# Precondition
A direct chat has about 25 unread messages (unread counter is 25)

# Actual Result
When opening the direct chat, it focuses on the unread message 18, instead of the unread message 1
https://user-images.githubusercontent.com/69950655/115339043-39ccf380-a1ce-11eb-900a-d02f0f316f4a.mp4

# Expected Result
When opened, the channel/direct screen should focus on the first unread message

# Environment
Both iOS and Android App
Build version: 2.2.9-6
QA environment

**Comment by tlle14** [comment]
Hi @manhduc-nguyen 
Retest failed!
I've sent about 24 messages. But when opened the channel, it focuses on 16th message.

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/fab44c94-2c8f-41f2-ae86-7f76c729b845)

**Comment by tlle14** [comment]
Hi @manhduc-nguyen 
Retest failed with the messages in a channel. 
https://images.zenhubusercontent.com/309637937/bf70f1d0-afb5-4216-ba4e-d2fd596b60cb/video31f230ae_2705_4f20_8faa_46a19b468627video.mp4

**Comment by tlle14** [comment]
This should be an improvment. I changed the label.

**Comment by BenoitTallandier** [comment]
Related US : https://www.notion.so/linagora/Open-channel-at-the-first-unread-message-b89a128a4e92451986a26a7ca5aa94f4

**Comment by BenoitTallandier** [comment]
Related US : https://www.notion.so/linagora/Open-channel-at-the-first-unread-message-b89a128a4e92451986a26a7ca5aa94f4
