### ISSUE TITLE
Message > After edited, the twacode text doesn't display correctly

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#479]
# Precondition
A message contains twacode

# Actual Result
After editing, the updated message doesn't display in the format of twacode. 

https://user-images.githubusercontent.com/69950655/115648756-3792a280-a350-11eb-83f1-d6668b118b72.mp4

# Expected Result
The message should keep displaying the twacode format after edited

# Environment
Both android and ios app
Build version: 2.2.9-6
QA environment

**Comment by bobs4462** [comment]
@tlle14 Can you please provide us with examples, so we can reproduce the issue locally?

**Comment by tlle14** [comment]
> @tlle14 Can you please provide us with examples, so we can reproduce the issue locally?

Sorry @bobs4462 I forgot to attach the evidence. Please see the updated details.

**Comment by bobs4462** [comment]
@tlle14 Sorry, but no matter how we try the issue seems to be not reproducible in current builds (which you don't have yet). So I ask you to check it again when you get the new build

**Comment by tlle14** [comment]
In the newest build, the bug is no longer existing since the twacode implemented on Mobile. 
I should close this issue.
Thank @bobs4462
