### ISSUE TITLE
The unread message counter isn't updated after user read the messages

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#48]
# Precondition
A direct has unread messages

# Actual Result
After reading the new messages, the user goes back to the channel list but the unread message counter doesn't disappear.
The User needs to refresh the app manually to update.
Refer https://streamable.com/m0m819

# Expected Result
The unread message counter should be updated when the user has read them.
 

# Environment
All android devices

**Comment by bobs4462** [comment]
@RomaricMourgues When we pulled messages from server the unread messages counter was autmatically updated on next pull.
But now this doesn't seem to be the case. Is it possible to restore the old behavior?
All the details regarding proxy<->twake api interaction can be clarified by @romanesko

**Comment by RomaricMourgues** [comment]
I will see what I can do, I may have removed some part of code because now we are using the new channels and notifications.

But all APIs related to notifications and channels will break one after the other I warned you :p

Romaric

**Comment by bobs4462** [comment]
Yes, I understand, but @tlle14 really wants those counters working :D

**Comment by bobs4462** [comment]
So @RomaricMourgues is there a way to fix it now, or will we all be better off, if wait for release of new version of Twake API?

**Comment by RomaricMourgues** [comment]
I think it is also better to wait for the january release, you should be able to start working with new notification API on monday

**Comment by PokoinikRWS** [comment]
Hold task.
Clarify date of solution from Romaric

**Comment by tlle14** [comment]
Hi @bobs4462 
1. The message counter disappears after the new message is read. But the direct message still displays bold after refreshing the app. 
=> It shouldn't be bold after the new messages are read.

2. Do we need to use both bold and unread counter to emphasize the unread messages?

**Comment by RomaricMourgues** [comment]
Here is the logic for bold / not bold:
```
const isBold =
    (channel.last_activity || 0) > (channel.user_member.last_access || 0) &&
    channel.last_message?.sender != channel.user_member?.user_id;
```

**Comment by bobs4462** [comment]
1. The issue seem spontaneous, sometimes twake backend doesn't acknowledge the read request, I'll investigate.
2. Yes, the bold means something has happened in the channel, counter means  someone mentioned you in a thread (@all @here @username)

**Comment by RomaricMourgues** [comment]
@bobs4462 see my last message just on top of yours, maybe you don't use the "channel.last_message?.sender != channel.user_member?.user_id;" part

**Comment by bobs4462** [comment]
Ok, I'll check whether that's the case

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/cd53cad7-2b77-4116-bad0-bfc568f2c330/videof37b7b6d_cff5_464b_94cf_5d302f333bc1video.mp4
