### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#480]
We need to integrate [Segment](https://segment.com) (our analytic hub).

### Package
There is no official package for now. But I found this : https://pub.dev/packages/flutter_segment that can be used.

### Analyse
We have to identify user with their console ID when they open the app.

**Comment by bobs4462** [comment]
Hi @BenoitTallandier, do you mean we just need to send statistics every time the app is opened?

**Comment by BenoitTallandier** [comment]
Yes, the rest we'll be handle by the server :)

**Comment by bobs4462** [comment]
@RomaricMourgues What is correct way to retrieve user's console Id (if present)?

**Comment by RomaricMourgues** [comment]
It will be in the "provider_id" and "provider" (should be = to "console") of the user object

**Comment by bobs4462** [comment]
@BenoitTallandier I added analytics support in release mode. You should be able track them in Segment now.
If everything works as expected, please close this issue.

**Comment by BenoitTallandier** [comment]
Perfect, thank you ! 🙏

**Comment by tlle14** [comment]
How can I test this feature? @bobs4462

**Comment by bobs4462** [comment]
Actually you cannot :), unless @BenoitTallandier gives you access to Segment. He was supposed to test and close this issue himself

**Comment by bobs4462** [comment]
@BenoitTallandier please close this issue, if you have no further requests :)

**Comment by tlle14** [comment]
I think we should.
