### ISSUE TITLE
Login > A new account cannot login to the app 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#485]
# Precodition
A new Linagora account (the guy joined on 5th April)
Server address: Beta server

# Actual Result
Cannot log in with the Linagora new account to the beta server. 
It displays an error credential message
https://user-images.githubusercontent.com/69950655/115654053-86453a00-a35a-11eb-9d9e-2f507304efea.mp4

# Expected Result
Please investigate.
The new account should be able to login to the mobile app

# Environment
Android App
Build version: 2.2.9-6
Beta environment

**Comment by bobs4462** [comment]
@tlle14, can you please make sure that you actually can login with this account on beta.twake.app?

**Comment by tlle14** [comment]
I cannot log in by the account on web beta.twake.app either.

**Comment by bobs4462** [comment]
Then the account was either registered via chat.twake.app or it wasn't registered at all. Because if you go to chat.twake.app and register there you won't be able login via beta.twake.app, regardless of whether it happened before 09/01/2021 or later.

**Comment by tlle14** [comment]
Hi @bobs4462 

The problem is related to changing passwords and no longer existing after the user changed his password.
Yesterday, my test account got the same problem. After changing the password, I can log in successfully. 

Do you have any idea about how is it happen?

**Comment by bobs4462** [comment]
Hi, I suppose only @RomaricMourgues can shed some light to this truly weird behavior.

@tlle14 Can you provide us with details, like which server it was, how did you change the server etc.

**Comment by tlle14** [comment]
Well, it happens one day I woke up and find myself cannot log in to the Twake app... It said the credentials were incorrect.
(My test account is on QA server, the other user is on Linagora production)
That's why I reset the password and login again, then it's successful.

**Comment by RomaricMourgues** [comment]
I don't have any clue, changing password does not have an impact on Twake. I will think about it

**Comment by tlle14** [comment]
Ahhh, the other user once changed the default password to his current password, then he couldn't login when I asked him. 
After the second change, he can login. I will try to reproduce with the changing password feature.

About my account, I doubt someone had changed the password (maybe someone from the dev team?) Let's see.

**Comment by tlle14** [comment]
I cannot reproduce this issue in QA enviornment. I should close this one
