### ISSUE TITLE
Edit channel > A result cannot display after it is selected in another channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#488]
# Actual Result
When adding members to the channel, if a record is selected (but not yet submitted), it won't be returned when searching on another channel

https://user-images.githubusercontent.com/69950655/115697931-41d39180-a38e-11eb-9db3-998725c0a45c.mp4

# Steps
1. Open ChannelA
2. Open the adding member screen
3. Search and select MemberA to add to the member list (but not yet submitted)
4. Close the adding member screen of ChannelA
5. Open ChannelB
6. Open the adding member screen of ChannelB
7. Search for MemberA
8. Verify the result: MemberA doesn't display on the search result

# Expected Result
When search to add members to a channel, the matched results should show anyway 

# Environment
Both android and iOS app
Build version: 2.2.9-6
QA environment

**Comment by EvGen94** [comment]
@chibenwa Good morning!
Could you test it please, bug has been fixed in the last build

**Comment by tlle14** [comment]
You're right, the bug is no longer existing. I should close this one
