### ISSUE TITLE
Message > Reaction is not synced in real-time

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#489]
# Precondition
There has user1 and user2
user1 has reacted to the message in a channel

# Actual Result
When user2 adds more reaction (+1 to the same icon)  to the message, the reaction is not updated in real-time.
The user needs to pull to refresh the app to see the change

https://user-images.githubusercontent.com/69950655/115700953-739a2780-a391-11eb-907a-ab68cea1b389.mp4

# Expected Result
The reaction counter should be synced in real-time

# Steps
1. User1 reacts to a message
2. User2 tap to the reaction of User1 
3. Verify on User1 screen, the reaction counter is not increased

# Environment

**Comment by bobs4462** [comment]
@tlle14 Try it again please with the new build, on chat.twake.app I couldn't reproduce the issue.

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue happens on both QA environment and Production, between an Android App and iOS App

**Comment by bobs4462** [comment]
@tlle14 Can you confirm, that the issue only occurs inside the threads, or does it happen on top message level too?

**Comment by tlle14** [comment]
Hi @bobs4462 
To answer your question:
- Inside a thread: yes (react on android)
- Top level: yes  (on both)
- Single message: yes (on both)

**Comment by bobs4462** [comment]
After next update it should work as expected (given that internet connection is stable and twake backend is stable)

**Comment by tlle14** [comment]
Hi @bobs4462 
This retest is blocked by the issue cannot react to a message. I'm not sure if this is related to state management or not. Please investigate.

**Comment by tlle14** [comment]
Thanks, 
The issue is no longer exists in good internet condition
