### ISSUE TITLE
New Feature: user mentions 

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#494]
Because we have completely reworked twacode parser, now we can add support for user mentions. 

I suggest that we download and store all the users right when starting the app and then use this data to autocomplete username when user starts typing after at symbol `@`, also the same info can be used to retrieve userIds by their usernames, so that we can complete the string with userids if it has valid usermentions. For example: 
```Hello @johndoe, how do you do?``` - will be shown to the end user when he types the message
```Hello @johndoe:<user_id>, how do you do?``` - will be passed to parser to generate correct twacode structure.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 @RockinPaul 
https://zpl.io/VOvpLwQ
Dear colleagues, user mentions.

Message bubble near the right edge of the cell is the ability to be redirected into a direct chat with a desired user + online status indication As for a mainstream UI logic is repeats Telegram where mentioned user is highlighted as underline inside a message bubble

**Comment by tlle14** [comment]
Hi @bobs4462 @BastiaanVanGaalen 
I have some questions:
1. Is the user able to mention himself? 
2. When tapping on the mentioned text in a bubble message, what would happen? Redirect to the user private discussion or open a bubble chat icon?
3. It should display the username or the name of mentioned one? For example: Me is `@leloan` or `Le Loan` ?
4. The suggestion is based on the username or the name?

**Comment by bobs4462** [comment]
@tlle14 Hello
1. Should be able to, why not
2. Nothing, the bubble will be removed in the next build
3. In options list it displays first name + last name in message input field it displays username
4. The suggestion is based on username, firstname, lastname, whichever matches
5. It should scroll, yes.

**Comment by tlle14** [comment]
About the number 2, the user cannot open a direct chat with the mentioned user, did you mean? 
Or we just do not implement it yet?

**Comment by bobs4462** [comment]
You should be able to open direct chat with the user (not now thought), but not via mentions suggestion list, while typing the message (because it doesn't make any sense to open direct chat with the user, when you are already typing the message). 
It will be implemented in near future, when we work on mention based navigation (so it's just going to like the web version).

**Comment by tlle14** [comment]
I got your point, thanks @bobs4462

**Comment by tlle14** [comment]
Hi @bobs4462 could you please confirm one more thing? By replacing yes (y) or no (n) instead of the question mark. 


Workspace member | Channel member | Able to mention? | Question?
-- | -- | -- | --
y | y | y |  
y | n (private channel) | ? | Can the mentioned user see the message?
y | n (public channel) | ? | Can the mentioned user see the message?
n | n | ? |

**Comment by bobs4462** [comment]
Workspace member | Channel member | Able to mention? | Question?
-- | -- | -- | --
y | y | y |  
y | n (private channel) | y | Mentioned user will not get notification
y | n (public channel) | y | Mentioned user will not get notification
n | n | n |  

Basically, mentions are workspace wide, and you can mention anyone in workspace, regardless of channel membership, but the mention based notifications will still respect channel membership and notification settings of the user.

**Comment by bobs4462** [comment]
@tlle14 Hi, should we close this one?

**Comment by bobs4462** [comment]
@tlle14 ping

**Comment by tlle14** [comment]
Hi @bobs4462 I don't see this feature implemented in the new build. Could you please confirm?

**Comment by tlle14** [comment]
Mention is implemented on 3.0.2
