### ISSUE TITLE
New UI > The background color of "my message" is too bright 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#496]
# Actual Result
On the chat screen, the blue shade is too bright makes my eyes feel tired
I checked with a tool, the current blue is #5600ff instead of #004dff

https://user-images.githubusercontent.com/69950655/115862616-8a5a8000-a45e-11eb-8039-10dff3fb94ac.mp4

# Expected Result
Both #5600ff and#004dff shouldn't be used in the background. 
Please use another color which is more eye-friendly.

# Environment
Both Android and iOS app
Build version: 2.2.9-7
QA environment

**Comment by bobs4462** [comment]
@BastiaanVanGaalen, I think it's your area of expertise :)

**Comment by BastiaanVanGaalen** [comment]
I kindly asked @RockinPaul to replace the color of message bubble to milder tint of blue in the following sprint.

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul 004DFF > 2B8FFD

**Comment by RockinPaul** [comment]
315EFB - new color to try.

**Comment by tlle14** [comment]
Close issue since the design has been changed a lot.
