### ISSUE TITLE
New UI > Screen is not updated

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#498]
There are some screens are not updated. They also don't have a new design. 
Please confirm if you have a plan to update them:

### 1. Login screen
[image](https://user-images.githubusercontent.com/69950655/116020530-a9306080-a670-11eb-8c38-992f370804cf.png)

### 2. Thread screen
[image](https://user-images.githubusercontent.com/69950655/116020845-44c1d100-a671-11eb-9c42-5d59fcaff41f.png)

I saw the design of reply messages. Will the thread screen be removed in the future?
[image](https://user-images.githubusercontent.com/69950655/116020712-117f4200-a671-11eb-95d2-7083e0baa3c5.png)

### 3. Splash screen
Splash screen is recently using the old app color
It should be updated.
[image](https://user-images.githubusercontent.com/69950655/116065085-d69cfe80-a6b0-11eb-8ba4-3c0d0477e531.png)

**Comment by tlle14** [comment]
Hi @RockinPaul @BastiaanVanGaalen @bobs4462 could you please confirm?

**Comment by bobs4462** [comment]
@BastiaanVanGaalen do you have anything to say about this one?

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Sign in flow was re-designed and is to be implemented in a scheduled time!
Screens for the reference: https://zpl.io/be3rNPY

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen 
Please tell me to retest this issue when it is implemented.

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen 
Could you please update the design when there is an invalid credential? It should have an error message

**Comment by BastiaanVanGaalen** [comment]
@tlle14 In case user makes an attempt to log in using an email address the is valid but is new, in this case we offer him to create an account with this new email: https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/60aca0c818edbb04cf173310

All other validation errors occurring inside input fields are reflected in designs.

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul @tlle14 Splash screen: https://zpl.io/2ZMGqDE

**Comment by BastiaanVanGaalen** [comment]
@tlle14  as for thread screen, i will re-design it tomorrow.

For now, we have just reply to a message by a single person.

**Comment by bobs4462** [comment]
Closing it for now, because a lot of screens including the login and others will be changed again pretty soon (during the next month)
