### ISSUE TITLE
The channel isn't bold when having a new activity

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#499]
# Actual Result
When having a new activity in the channel, the channel is not bold
https://user-images.githubusercontent.com/69950655/116027509-48f4eb00-a67f-11eb-9bda-ff783649b04d.mp4

# Expected Result
When having a new activity in a channel, the channel name should be bold

# Environment
Both Android and iOS app
Build version: 2.2.9-7
QA environment

**Comment by BastiaanVanGaalen** [comment]
@tlle14 @RockinPaul @bobs4462 

1. Boldness will compete with channel name itself, and, instead, i decided to use blue dots as the indication of new activity in channels and chats you haven't caught up with yet, please, follow the link to see the design: https://zpl.io/Vq7BL0Z

2. Can we at least leave "at" icon to indicate user_id unread mentions on channel preview cell or API constraints don't provide such opportunity?

**Comment by bobs4462** [comment]
API does provide to pieces of information
1. A flag (boolean), whether there's been some activity from the time user has last checked in
2. A number of messages (top level, threads a counted once), where user has been mentioned / or user has participated.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 
Thank you for explanations.
1. Boolean flag = our blue dot
2. Number of messages with mentions stays the same. Blue oval with number count.

@tlle14 This task can be considered as resolved.

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen 
Since we change to the new design, this is not an issue anymore.
