### ISSUE TITLE
New UI > Channel list/ Direct list 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#500]
# 1. Total unread counter doesn't display on Channels and Directs tab
**Actual Result**
![image](https://user-images.githubusercontent.com/69950655/116026972-f23ae180-a67d-11eb-87ce-e0c6505a10b9.png)

**Expected Result**
The total unread counter for Channel and Directs should be displayed as the design
[image](https://user-images.githubusercontent.com/69950655/116026325-ac314e00-a67c-11eb-83dc-3cf44fc86964.png)

# 2. Unselected tab color is not correct
**Actual Result**
![image](https://user-images.githubusercontent.com/69950655/116028486-73e03e80-a681-11eb-9652-7dbc3154f34d.png)

**Expected Result**
Should using the correct color as the design
[image](https://user-images.githubusercontent.com/69950655/116028568-9eca9280-a681-11eb-8515-6159e1df0cb9.png)

# 3. Missing the search bar
**Actual Result**
Recently, the search bar is not appear in the channel/directs list
[image](https://user-images.githubusercontent.com/69950655/116028844-362fe580-a682-11eb-9767-cc7a44e5b4cf.png)

**Expected Result**
The search bar should appear as the design
[image](https://user-images.githubusercontent.com/69950655/116028825-2adcba00-a682-11eb-85cf-e9428bef666f.png)

# Environment
iOS App
Build version: 2.2.9-7
QA environment

**Comment by EvGen94** [comment]
@tlle14 The search bar has been added

**Comment by tlle14** [comment]
Hi @EvGen94 
Is this the filter for the current channel list or also search for the public channel that user hasn't joined yet?

**Comment by EvGen94** [comment]
@tlle14 Hi!
For the current channel list

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass!
![screenshot_13.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6123760b-7e42-4ce2-a01c-a5900ac1c2eb)
