### ISSUE TITLE
It takes about 3-4 seconds to display the unread counter of a direct chat

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#501]
# Actual Result
It takes about 3-4 seconds to display the unread counter of a direct chat
https://user-images.githubusercontent.com/69950655/116030995-06371100-a687-11eb-95cd-d28cc446c176.mp4

# Steps
1. Open the app
2. Open the Direct chats
3. Verify the issue: it takes time to display the unread counter

# Expected Result
The unread counter of a direct chats should display right after open the tab.

# Environment
iOS App
Build version: 2.2.9-7
QA environment

**Comment by tlle14** [comment]
No more issue on 2.2.9-8

**Comment by bobs4462** [comment]
should be almost instant now

**Comment by tlle14** [comment]
the issue is no longer existing
