### ISSUE TITLE
Rewrite notification click based navigation to take the user to the pages from new design

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#502]
Recently @RockinPaul has been working on new design of application pages, and some of them has already been integrated into the application. But navigation which is triggered after user clicks on notification has not been adjusted to account for the new pages.

So the task is to rewrite the navigation logic, so that any click on notification redirects the user to the page from new design.

**Comment by tlle14** [comment]
Thank @bobs4462 @RockinPaul 
Retest pass!
https://images.zenhubusercontent.com/309637937/09f6c3e8-b750-4726-ac63-243f0bd0ac85/video44659745_3428_4b73_ad5d_4da8ad0d6e50video.mp4
