### ISSUE TITLE
New UI > Empty Channel/ Direct chat screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#503]
# 1. Doesn't show channel creation information
**Actual Result**
The channel creation information doesn't display on empty channel screen
[image](https://user-images.githubusercontent.com/69950655/116045677-73a16c80-a69c-11eb-884c-6d2c6f52db9b.png)

**Expected Result**
Should display the channel creation information as the design
[image](https://user-images.githubusercontent.com/69950655/116045833-a3e90b00-a69c-11eb-8402-48f0782e6b9c.png)

# 2. The welcome text in the direct chat has inappropriate line breaks
**Actual Result**
![image](https://user-images.githubusercontent.com/69950655/116047572-671e1380-a69e-11eb-9669-1408f287f196.png)

**Expected Result**
- It should display the line breaks as in the empty channel 
- It's better if we can shorten the welcome text (this is just a suggestion)
[image](https://user-images.githubusercontent.com/69950655/116048211-2377d980-a69f-11eb-86f3-2ac4f60cb36f.png)

# 3. The message textbox is not updated as a design
**Actual Result**
The textbox is still in the old design
[image](https://user-images.githubusercontent.com/69950655/116048578-80738f80-a69f-11eb-9e93-a4d36c5e15d6.png)

**Expected Result**
The message textbox should be updated following the new design
[image](https://user-images.githubusercontent.com/69950655/116048522-76519100-a69f-11eb-9f07-29b17b403c5b.png)

# 4. The small Twake logo has a solid background
**Actual Result**
The small Twake logo has a solid background
[image](https://user-images.githubusercontent.com/69950655/116050183-676bde00-a6a1-11eb-837c-5e22d9c389eb.png)

**Expected Result**
The Twake logo background should be gradient
[image](https://user-images.githubusercontent.com/69950655/116050580-da755480-a6a1-11eb-9d4f-a4a746dbf901.png)

# 5. Swipe left to reply
**Actual Result**
I saw the swipe left to reply function in the design, but it is not implemented yet.

**Expected Result**
Please confirm if we will apply this feature

# 6. Sent/Received states of the message
The feature does not appear on the app. Please confirm if you are going to apply it:
![image](https://user-images.githubusercontent.com/69950655/116052332-b450b400-a6a3-11eb-9894-c88fb1941944.png)

# 7. The distance between two correlated messages is not correct
**Actual Result**
[image](https://user-images.githubusercontent.com/69950655/116347774-0e25bb00-a817-11eb-8f93-23435f770f0b.png)

**Expected Result**
[image](https://user-images.githubusercontent.com/69950655/116347678-da4a9580-a816-11eb-9efb-346cae3d6949.png)

# Environment
iOS App
Build version: 2.2.9-7
QA environment

**Comment by bobs4462** [comment]
@BastiaanVanGaalen regarding the 6th point, this little check mark thing. I don't think it's ever going to be implemented (or at least not in near future) because such a feature is not even in roadmap.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 @RockinPaul as for 6th point, since API doesn't provide such opportunity there is no point implementing it. So, put it away.

**Comment by RockinPaul** [comment]
1. Right now, there is no way to obtain such information from API.
4. "The small Twake logo has a solid background" -
However it's a gradient, technically:
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: LinearGradient(
                  transform: GradientRotation(2.79253), // 160 degrees
                  tileMode: TileMode.mirror,
                  colors: [
                    Color(0xff4838b7),
                    Color(0xff3840f7),
                  ],
                ),
              ),
And it looks like a gradient if we try to look more precisely. Also, some platform-specific rendering issues may take place here, that's why it seems so different to mockup.

@BastiaanVanGaalen decided to skip this in favor to more urgent tasks.

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul Confirm jettisoning this task in favour of more urgent ones, gradient inside this small circle doesn't have any considerable impact on UX/UI. There are plethora of issues to be addressed. So, put it away.

**Comment by BastiaanVanGaalen** [comment]
@tlle14 As for **7th point** "The distance between two correlated messages is not correct". It cannot be by itself equidistant since left-side messages imply image avatar and right-sided imply just delivery status icon. Please, ignore equidistance at the moment, all our efforts should be put to secure smooth functional part of the app. We must ensure all features and core functionality work as expected, after that we will move to honing UX/UI.

**Comment by tlle14** [comment]
Please put a side the point you are not going to fix, define what will be done. So I can retest. Thanks for your confirmation!

**Comment by tlle14** [comment]
@BastiaanVanGaalen the 7th point you might misunderstanding, I meant I expect the app display as the design. The right side should be further from the border than the current.

**Comment by bobs4462** [comment]
@BastiaanVanGaalen @tlle14 should we keep this issue around? If yes, please list out the changes, that need to be implemented

**Comment by tlle14** [comment]
I should close this ticket
