### ISSUE TITLE
New UI > Workspaces list 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#505]
# 1. Selected workspace has no highlighted avatar 
 **Actual Result**
[image](https://user-images.githubusercontent.com/69950655/116061439-0ba75200-a6ad-11eb-9b6f-332721f3396f.png)

**Expected Result**
In fact, the workspace avatar is an uploaded image. The blue border may not emphasize the selected workspace effectively.
We should ask our designer for a better solution.
[image](https://user-images.githubusercontent.com/69950655/116061549-309bc500-a6ad-11eb-83d5-ef9aec701422.png)

# 2. Clicking on Channels button to close the workspace list will open then close the channel creation screen
**Actual Result**
1. Open the channel list
2. Tap on `Channels` button to close the channel list
3. Verify: the channel creation screen is opened and closed promptly before the workspace list is closed
https://user-images.githubusercontent.com/69950655/116061985-adc73a00-a6ad-11eb-9529-345f1395d761.mp4

**Expected Result**
It shouldn't open the channel creation screen

# 3. Total unread message in a workspace doesn't display
**Actual Result**
There doesn't have total unread message in the workspace
[image](https://user-images.githubusercontent.com/69950655/116069293-6b096000-a6b5-11eb-9858-13100cd025e4.png)

**Expected Result**
It should have a total unread message as in the design
[image](https://user-images.githubusercontent.com/69950655/116069362-7ceb0300-a6b5-11eb-8e1b-415dd86c8d70.png)

# Environment
iOS App
Build version: 2.2.9-7
QA environment

**Comment by RockinPaul** [comment]
Is not relevant anymore.
