### ISSUE TITLE
Channel list > The preview messages are replaced by the text "This channel/conversation is empty"

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#507]
# Actual Result
All the preview messages become `This channel/ conversation is empty` text
https://images.zenhubusercontent.com/309637937/4f312135-7911-4207-8b49-79b82a4dac5a/video43ff0c20_d951_4489_bb37_c47bf45ade5bvideo.mp4

# Expected Result
The channel/ direct chat should display the preview message when it has chat history

# Environment
Both iOS and Android app
Build version: 2.2.9-7
QA environment

**Comment by bobs4462** [comment]
Hi @tlle14, can you please confirm that those channels have at least one message which is fresh, i.e less than one month old?

**Comment by tlle14** [comment]
Hi @bobs4462 Even with the already posted message. Seems like Romaric recently changed something :-?

**Comment by bobs4462** [comment]
Ok, is the issue web.qa specific?

**Comment by RomaricMourgues** [comment]
Hi, it seems it is broken on qa, it is not on your side @bobs4462

**Comment by RomaricMourgues** [comment]
@stephanevieira75 could you take a look at this one when you have time ?
There is some logs to add to see why the last_message object isn't returned when getting list of channels (it is created, I checked)

**Comment by RomaricMourgues** [comment]
We just fixed it right now, it is going to QA in 20-30 minutes
