### ISSUE TITLE
Add adapter to proxy layer to handle new reactions format. 

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#508]
Soon we'll be moving to new messages format (block based), and we for now we need to handle new reactions format
The new format will look like this: 
```
{reactions: [{users: ["id1", "id2"], name: ":some-emoji", count: 123}}}
```
vs. old one
```
{reactions: {":some-emoji:": {users: ["id1", "id2"], count: 123}}}
```

I suggest that we implement a converter from old format to new one on proxy layer, and switch logic for handling new reactions format exclusively on mobile client.

**Comment by bobs4462** [comment]
@RomaricMourgues I have implemented a preprocessor for reactions on proxy level, so that any old reaction format will be converted to new format first before being returned to mobile client. On Mobile client only the new format will be supported, as proxy will ensure that all the messages conform to the new one. But all the current users will be forced to reinstall the app, because it might contain a lot of messages with old format in local DB.

**Comment by RomaricMourgues** [comment]
Thanks, we will have other big changes in the next months for messages, we will need to align ourselves at some point.

You can find all the new format here:
- https://www.notion.so/twake/Rest-APIs-f2ec07e17b20498381b03e96a443a795
- Here too (you will find the "FileObject": https://www.notion.so/twake/Database-models-19438d7d619b4d47bf01b0649c887b49
- And here for block format "BlockObject": https://github.com/linagora/Twake/blob/develop/twake/backend/node/src/services/messages/blocks-types.ts and https://app.slack.com/block-kit-builder/

**Comment by bobs4462** [comment]
@tlle14, if you can react to messages, and that doesn't lead to crashed application, you can close this issue.

**Comment by tlle14** [comment]
Hi @bobs4462 
I can react to a message but need to pull to refresh the app for showing the reaction. 
It doesn't lead to the app crashed. 
I will open a new issue then close this one as this ticket is your task :)
