### ISSUE TITLE
A thread screen becomes empty after deleting the last reply

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#519]
# Actual Result
After deleting the last reply in a thread screen:
- The parent message is also disappeared
- When back to the main screen, the link "see all answers" is still displaying

https://user-images.githubusercontent.com/69950655/116377584-869e7300-a83b-11eb-8a63-785e2f4b7408.mp4

# Expected Result
After deleting the last message in the thread screen, it should:
- Go back to the main screen without the "see all answers" link in the parent message
- OR stay in the thread screen with the parent message only

# Environment
Both ios and android app
Build version: 2.2.9-7
QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 
The retest is blocked by the issue: cannot open the context menu in the thread screen.
https://images.zenhubusercontent.com/309637937/5b86a284-3f46-4a66-af7f-e796c7dc614d/video87bf04dc_73ab_4d15_947b_2f359c413eb9video.mp4

**Comment by bobs4462** [comment]
@tlle14 please check again

**Comment by tlle14** [comment]
The issue is no longer existing
