### ISSUE TITLE
Message > Quote character from Mobile doesn't display as a quote

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#52]
# Actual Result
Write a quoted message on mobile, the message doesn't display as a quote.

**On Web version:**
![image](https://user-images.githubusercontent.com/69950655/101149921-2885af00-3652-11eb-94a3-39e52a69580e.png)

**On Mobile:** 
![image](https://user-images.githubusercontent.com/69950655/101150014-46531400-3652-11eb-97fa-5e8db4b1900c.png)

# Expected Result
A quote message is composed on mobile should display as a quote.

# Environment
All android devices

**Comment by bobs4462** [comment]
@romanesko Can we support quoting in markdown parser?

**Comment by romanesko** [comment]
@bobs4462 skipping this in case of moving to md?

**Comment by bobs4462** [comment]
@romanesko Not exactly, markdown parser will render the quotations on client side, that's not the issue here, the problem is that the web client doesn't care about text representation for now, it relies solely on twacode structure for rendering purposes. So we need to parse quotes, and convert them to twacode on proxy for now (before web catches up at least)

**Comment by romanesko** [comment]
Got it.
Fixed, now you can send messages started with >
(not sure if we need this in future)

**Comment by tlle14** [comment]
Thank @bobs4462  and @romanesko 
Retest pass

https://images.zenhubusercontent.com/309637937/6e42d644-78c3-4e23-8b54-cd0cb22c019a/video59d40a58_6945_456d_b2a2_b8e2219021c0video.mp4

**Comment by tlle14** [comment]
Hi @romanesko 
I reopened this issue because it always displays a multiline quote on mobile 

https://user-images.githubusercontent.com/69950655/106890194-90707880-671b-11eb-92c6-d1a340a6ec9f.mp4

While it is displaying correctly on the Web
![image](https://user-images.githubusercontent.com/69950655/106890281-ab42ed00-671b-11eb-9068-22527c0fc61f.png)

**Comment by tlle14** [comment]
Hi @bobs4462 
I don't see the change 

Created on the web using 1 line break
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/5ffea9b1-4fd0-428b-9da9-aa10f74a5a4e)

Displays on Mobile as a blockquote
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/471c0b73-51d9-4643-80e4-cc96b8ab5fb7)


Because this one is not on priority, please fix it later. 
Thank you

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/50afeea9-ad21-4bb1-a9a8-7dbce53b5a9d/videoa235b138_9395_4d52_a13b_9d5ec6e5a5d4video.mp4
