### ISSUE TITLE
Login autocomplete does not work

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake-Mobile#523]
1. Open the application
2. Click on the `Email` field: OS displays the email suggestion
3. Click on the suggestion: The `Email` field stays blank
4. Click on the `Email` field and add a space: The email I selected in step 3 is displayed (with a space at the end)
5. The password is not filled

I guess the suggestion should also fill the password field, but this is not the case.

Here are the screenshots in the steps order:

![Screenshot_2021-04-28-15-04-55-677_com twake twake](https://user-images.githubusercontent.com/264403/116409474-2bb54d80-a834-11eb-84dd-34153f271ab1.jpg)
![Screenshot_2021-04-28-15-05-02-175_com twake twake](https://user-images.githubusercontent.com/264403/116409507-32dc5b80-a834-11eb-8229-e69eec516aa0.jpg)
![Screenshot_2021-04-28-15-05-11-826_com twake twake](https://user-images.githubusercontent.com/264403/116409547-3b349680-a834-11eb-816f-1a13ff3efed3.jpg)

## Environment

- Android 10, Redmi Note 9S
- Latest version from the store

**Comment by manhduc-nguyen** [comment]
@tlle14 seems like the password is saved to google account and it can't be filled somehow. I think its a bug from the device but since we are WFH right now in VN, I can't get the device so I'm pending it.

**Comment by bobs4462** [comment]
closing this one, as we might be moving back to webview authentication, for the better future integration with twake console
