### ISSUE TITLE
There should have a message for the new user who has no channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#527]
# Actual Result 
For the very new user, who has not joined any channel yet, there has nothing on the channel list screen
https://user-images.githubusercontent.com/69950655/116499325-1ee93600-a8d6-11eb-9e03-db3221160b84.mp4

# Expected Result
There should have a message on the empty list screen to welcome the new user

# Environment
Both on ios and android app
Build version: 2.2.9-7
QA environment

**Comment by bobs4462** [comment]
Is it even still reproducible?  @tlle14

**Comment by tlle14** [comment]
When a new user joins the workspace, he is automatically added to the General channel => No need to have a message. 
But in the chat, this is an UX improvement. 
![image](https://user-images.githubusercontent.com/69950655/151313595-54e9ad38-3544-4de2-a0f4-57fd0b01b69d.png)
