### ISSUE TITLE
The Search function returns irrelevant results

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#543]
# Actual Result
1.The Search function returns irrelevant results
2. The matched result is not on the top

**On the Mobile:**
![image](https://user-images.githubusercontent.com/69950655/116955912-0ace7b80-acbe-11eb-8dae-19bff270e01c.png)

**On the Web:**
![image](https://user-images.githubusercontent.com/69950655/116955823-d0fd7500-acbd-11eb-97de-43479d245ac8.png)

# Expected Result
The search function should return the correct result (as on the web)
The most matched result should be displayed on the top.

# Environment

Build version: 2.2.9-8
Both android and iOS App
QA environment

**Comment by bobs4462** [comment]
@RockinPaul is that the same issue, we had with /users/search endpoint?

**Comment by bobs4462** [comment]
Irrelevant, as all the search happens on local database
