### ISSUE TITLE
Attachments > Cannot copy the message contains only attached files

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#548]
# Precondition
Task: https://github.com/linagora/Twake-Mobile/issues/483

# Actual Result
When copying the message that contains only attachments, it will have nothing to paste
https://user-images.githubusercontent.com/69950655/116993949-54d95080-ad02-11eb-9eb5-ddf3d832e87f.mp4

# Expected Result
It should hide the `copy` button in the context menu when selecting the message that contains only attachments.

# Environment
Both android and ios
Build version: 2.2.9-8
QA environment

**Comment by EvGen94** [comment]
Good day!
@tlle14 This bug was fixed, can you test it

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass!
https://images.zenhubusercontent.com/309637937/478fdf65-76fa-453a-95ef-6b8f351b95a6/videoac808e2c_d66b_43b6_b63f_44dcfa0844cevideo.mp4
