### ISSUE TITLE
After copied the message, the inform message hides the textbox

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#549]
# Actual Result
After copied the message, the inform message hides the chat textbox
![image](https://user-images.githubusercontent.com/69950655/116995466-4ab85180-ad04-11eb-9f71-36c4fc431fc5.png)

# Expected Result
The inform message shouldn't hide the chat textbox

# Environment
Both ios and android app
Build version: 2.2.9-8
QA environment

**Comment by bobs4462** [comment]
@EvGen94 please check this again

**Comment by BastiaanVanGaalen** [comment]
@EvGen94 Such notification should show up for no longer than 2,5 sec. It's ok that it overlaps message bubble during the time of showing.

**Comment by BastiaanVanGaalen** [comment]
@EvGen94 https://zpl.io/aRwkKWN

**Comment by tlle14** [comment]
Thank @EvGen94 and @BastiaanVanGaalen 
Retest pass!
https://images.zenhubusercontent.com/309637937/19847f5d-b953-4174-9061-0e671c9e5b8b/video60ebe261_ae72_44ca_b138_2e3830983cb4video.mp4
