### ISSUE TITLE
Message > The reaction displaying is not stable

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#551]
# Actual Result
On Android, the reaction cannot display after user reacts to a message 
https://user-images.githubusercontent.com/69950655/117111454-d3d99200-adb1-11eb-9df7-914c996ba957.mp4

On iOS, the reaction is duplicated after another user taps on (Randomly)
[image](https://user-images.githubusercontent.com/69950655/117111642-1d29e180-adb2-11eb-955c-eb01b8319eac.png)

# Expected Result
The reactions should be synced instantly between devices
Instead of duplicate the reaction, the reaction counter should increase 

# Environment
On both android and ios
Build version: 2.2.9-8
QA environment

**Comment by bobs4462** [comment]
@tlle14 is this issue still relevant?

**Comment by tlle14** [comment]
I still encounter the problem anytime reacting to a message. I think it relates to this one https://github.com/linagora/Twake-Mobile/issues/688

**Comment by bobs4462** [comment]
Yes I understand. The issue with sync is still there, but can you see the emoji (on your phone) right after you've reacted or not?

**Comment by tlle14** [comment]
Yes, we can close this one based on the description

**Comment by tlle14** [comment]
The duplicated reaction is still existing. But i prefer to create a new ticket for easier to track
