### ISSUE TITLE
It doesn't have a timeout when loading a channel unsuccessfully

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#554]
# Precondition
Internet connection is not stable 

# Actual Result
When opening a channel in the a internet condition, the channel keeps infinity loading

https://user-images.githubusercontent.com/69950655/117145916-dbaf2b80-addd-11eb-8eab-a2c73f5387cd.mp4

 

# Expected Result
1. Please find a solution to improve the way our app loading data in a channel, under the low speed internet connection
2. In case it cannot load the data, it should have timeout for loading or  a popup with retry button. We may need to ask BA and our UX designer to find a better solution

# Environment
Mostly on iOS App
Build version: 2.2.9-8
Production Server

**Comment by bobs4462** [comment]
I still consider ideal solution to be a completely autonomous application, which only works with local database (examples: Telegram, WhatsApp). And when there's internet connection present, it just requests the latest changes and incrementally applies them to local database. But this ideal model remains to be my wish, as it would require a complete architectural  redesign of the backend. So instead we'll try to patch it up somehow.

**Comment by bobs4462** [comment]
If channel messages were loaded once (and thus stored to local database), then they will be loaded again from it, and thus even if request to API timeouts, user will still be able to see messages from local cache

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed!

**Actual Result:** When I turn off the internet connection then open the app, it displays nothing but the gray screen.
**Expected Result:** It should load data from the local cache as your solution.
 
https://images.zenhubusercontent.com/309637937/19a0cdff-ded6-4e80-983a-97f8b60bb40e/videofa50d41a_3a9c_4e00_891b_b0b5c1f7ae4evideo.mp4

**Comment by bobs4462** [comment]
can you give this a retest?

**Comment by tlle14** [comment]
Local cache fixes this.
