### ISSUE TITLE
Create Channel > Cannot add member to the private channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#556]
# Actual Result
Cannot add members successfully when creating a private channel
https://images.zenhubusercontent.com/309637937/120d4376-32d0-4177-9e27-1a75210e8c6a/videocd5b377f_9b65_49f1_9db5_bd2869fa8df8video.mp4

# Expected Result
It should be able to add members to the private channel successfully

# Environment
Both android and ios app
Build version: 2.2.9-8
QA environment

**Comment by manhduc-nguyen** [comment]
@RockinPaul I have checked this bug, its ok from client side. I think its backend problem

**Comment by RockinPaul** [comment]
Thank you @manhduc-nguyen !
@romanesko please, pay attention to this.

**Comment by tlle14** [comment]
@bobs4462 @RockinPaul @manhduc-nguyen @romanesko  please notice this issue. 
Still happens on 3.0.1

**Comment by bobs4462** [comment]
Yes, I've created an issue on Twake core project, it's purely backend problem https://github.com/linagora/Twake/issues/1399

**Comment by bobs4462** [comment]
I believe, this should work now

**Comment by tlle14** [comment]
Thanks! 
Retest pass!
https://images.zenhubusercontent.com/309637937/c58ca288-a2f1-48d2-81d7-24ee536c2b8a/videoef32c8d7_072b_4a2a_8a3d_ca03295c48e7video.mp4
