### ISSUE TITLE
Changing role doesn't update on Mobile unless user re-login to the app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#558]
# Precondition
On Twake Console, change the role of the current user (on Mobile) from `Admin` to `Member`

# Actual Result
The current user on Mobile is still displaying as Admin. He is still able to act as an Admin. 
The role is updated only when the user logout from the app and login again. 

https://user-images.githubusercontent.com/69950655/117260159-fb476200-ae78-11eb-82c8-c986a772f106.mp4

# Expected Result
The role on Mobile should be updated right after it is changed on Console

# Environment
Android App
Build version: 2.2.9-8
QA environment

**Comment by RockinPaul** [comment]
I suppose we need some silent push notification to figure out when the role has been changed. @romanesko @bobs4462 what do you think?

**Comment by bobs4462** [comment]
@RomaricMourgues hello, is there any viable way to communicate such information to mobile app?

**Comment by RomaricMourgues** [comment]
Right now even the desktop doesn't have this in realtime, so I'm afraid not yet. Why not reloading this information when the app startup ?
You have new node endpoints to get users / workspace / company information that can be faster than the php ones: https://www.notion.so/twake/Rest-APIs-07c0294728794901b8c8a4518ad5852c

**Comment by bobs4462** [comment]
I personally think that we should ditch those ad-hoc permissions and use plain old roles instead for the following reasons:
1. There just 4 roles and way more permissions, the less the better here
2. Permissions are just proxy inserted attributes, and not recognized by twake core, unlike roles
3. We are going to remove proxy layer in near future

**Comment by bobs4462** [comment]
@tlle14 can you give me several test users, one on which can change the roles of the others? So I can test it with different role based actions?

**Comment by tlle14** [comment]
Hi @bobs4462 I've sent you the credentials on Twake Mobile channel

**Comment by bobs4462** [comment]
@RomaricMourgues It seems that even on web, when one changes roles in twake console, the update doesn't propagate instantly, user has to relogin in order to see the change right?

**Comment by RomaricMourgues** [comment]
Yes this is the case, we'll reimplement realtime soon

**Comment by EvGen94** [comment]
@tlle14 Can you heck it pls

**Comment by tlle14** [comment]
The issue is no longer happening. 
Thanks for reminding me @EvGen94 

**From Admin -> Member**

https://user-images.githubusercontent.com/69950655/151487098-9b5eead1-f910-4ab4-ab90-5da1ae197f6f.mp4


**From Member -> Guest**

https://user-images.githubusercontent.com/69950655/151487132-be6165a0-83f6-49be-8306-ed214a5a01c4.mp4
