### ISSUE TITLE
The URLs displays 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#559]
# Precondition
Task: https://github.com/linagora/Twake-Mobile/issues/405

# Actual Result
The link is not fit into the chatbox
The link color is not contrasting
[image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/0e071580-addd-45bc-9904-b2e4c9327bed)

# Expected Result
The link should fỉt into the chatbox
The link color should be more contrasting
[image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6f3bdbdb-20fb-45e8-bfd1-202f0959b80c)

# Environment
Both android and ios app
Build version: 2.2.9-8
QA environment

**Comment by bobs4462** [comment]
@BastiaanVanGaalen help needed

**Comment by tlle14** [comment]
Bastiaan has already commented in this issue https://github.com/linagora/Twake-Mobile/issues/753
I should close this old one.
