### ISSUE TITLE
Bot icon doesn't display 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#560]
# Precondition
https://github.com/linagora/Twake-Mobile/issues/405

# Actual Result
Bot icon doesn't display
[image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6a313dc3-f741-4be2-bd21-49ac0c4de224)

# Expected Result
Bot icon should display beside the bot message

# Environment
Both android and ios app
Build version: 2.2.9-8
Production Server

**Comment by bobs4462** [comment]
@tlle14 Hi, can you please clarify, what what kind of bot icon, do you mean bot avatar or inmessage icons?

**Comment by tlle14** [comment]
Hi @bobs4462 
I meant the bot avatar. 
![image](https://user-images.githubusercontent.com/69950655/117278057-9dbc1100-ae8a-11eb-8453-9707204f3171.png)

**Comment by bobs4462** [comment]
Ok, thanks, I'll take a look

**Comment by bobs4462** [comment]
@RomaricMourgues Do you remember the request about bot info in messages analogous to user info we have now (include_users flag), are there any ideas how to solve this?

**Comment by RomaricMourgues** [comment]
We have it my list, but not yet implemented yet.

**Comment by RomaricMourgues** [comment]
Hello hello, so from now on (as soon as it is on QA tonight) you will get the application object with the usual include_users flag.

**Comment by sherlockvn** [comment]
# Bot message don't sync in mobile anymore.
![image](https://user-images.githubusercontent.com/43041967/160977023-6f175b94-6934-4273-8460-0adb619b7d45.png)

![image](https://user-images.githubusercontent.com/43041967/160977129-2ec85874-f9ff-4ff1-a76f-9b6c0b41985b.png)

**Comment by RomaricMourgues** [comment]
Hi @sherlockvn  could you tell me if you still receive webhooks on web today ?
Also I am interested in your dark mode theme to share it to the other users :)

**Comment by sherlockvn** [comment]
Yes. Today I still receive messages from webhooks on web from tmail and linshare app(last message i received is about 4 hours ago), not from twake. About the extension, i will share it on twake channel :)

**Comment by BenoitTallandier** [comment]
Will be handled by this ticket : https://github.com/linagora/Twake-Mobile/issues/1329
