### ISSUE TITLE
It takes so long to return an error when input an invalid server address

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#564]
# Actual Result
When input an invalid server address then tap on `Connect` button, it takes about 15 mins to return the error message `invalid host`.
After correcting the server address, user still be unable to login to the app. 
He needs to kill the app and input the server address correctly right at the first try. Then things work.

https://user-images.githubusercontent.com/69950655/117438055-3fab2e80-af5b-11eb-8ad9-d9fe1736c455.mp4

# Expected Result
The server address validation should return the verification rapidly. 
After correcting the server address, user should be able to login to the app

# Environment
Both on Android and iOS App
Build version: 2.2.9-8
QA environment

**Comment by bobs4462** [comment]
can you please retest?

**Comment by tlle14** [comment]
The issue is no longer exist
