### ISSUE TITLE
State management refactoring

### ISSUE THREAD

**Issue by RockinPaul** [linagora/Twake-Mobile#571]
We got to the point where refactoring our state management solution is mandatory for keeping the development process effective. 
After all - Twake is an open-source project and we cannot leave its architecture completely without attention to continuous refinement.

**Comment by bobs4462** [comment]
https://github.com/linagora/Twake-Mobile/wiki - created a wiki here

I will document all the new changes that we make in this wiki. For now, I just created skeleton description of existing state management. 

You guys can contribute to it via git@github.com:linagora/Twake-Mobile.wiki.git

**Comment by bobs4462** [comment]
Finished
