### ISSUE TITLE
Change the font in the app

### ISSUE THREAD

**Issue by RockinPaul** [linagora/Twake-Mobile#572]
[https://app.zenhub.com/files/309637937/16c0b0ab-0d69-4885-a804-2ed1c812b65c/download](https://app.zenhub.com/files/309637937/16c0b0ab-0d69-4885-a804-2ed1c812b65c/download)

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul let's defer this task

**Comment by bobs4462** [comment]
@BastiaanVanGaalen what should we do with this one?
