### ISSUE TITLE
Create channel > Cannot display a channel without invitees after created 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#579]
# Precondition
Create a public/private channel without invitees

# Actual Result
After creation, the channel cannot display. It keeps displaying without channel information on header
https://images.zenhubusercontent.com/309637937/9e87e8d3-8ecd-490a-9fda-72187eab21f8/video8cbf59f2_bbc6_442c_8b2f_9985da7571d7video.mp4

# Expected Result
The channel should be able to display after created, no matter what it has members or not.

# Environment
Both android and ios
Build version: 2.2.9-9
QA environment

**Comment by bobs4462** [comment]
Does this issue still persist?

**Comment by tlle14** [comment]
The issue is no longer existing.
