### ISSUE TITLE
App does not  show the last updated display name 

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake-Mobile#58]
Steps to reproduce:
1. User A sends direct message to User B
2. User B view the message on Twake app
3. User A logs in in Web and change his Display Name
4. User B check user A's display name on Twake mobile app

Expected result:
User A's display name should be shown correctly

Actual result:
Old name is still shown even though I tried to re-login

**Comment by bobs4462** [comment]
It happens because of the usage of proxy server between main TwakeAPI and the app. And it so happens, that we cache all user data on proxy, and currently don't have any means for triggered updates of that cache. 
Postponing the issue for future, when we'll have a stable TwakeAPI

**Comment by bobs4462** [comment]
@tlle14 this issue now seems to originating from backend. When user changes his data from twake console, even on web he needs to relogin in order to see the changes in twake web interface

**Comment by tlle14** [comment]
It is no longer the issue on Mobile App ;)
