### ISSUE TITLE
[Story] Message system for thread answers

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#584]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a channel
When someone answer to a thread that is not the last the the channel feed,
Then I should see a message system at the end of the feed saying that there is an answer before
```

## Business case

- [ ] When I answer to the last thread of the channel feed, there is no message system
- [ ] When I answer to the thread of the channel feed that is not the last, there is a message system

**Comment by bobs4462** [comment]
@BastiaanVanGaalen please give some comments on that

**Comment by BastiaanVanGaalen** [comment]
@BenoitTallandier Was this case negotiated with Diana? There could be lots of system notifications about various answers in various threads so I don't think it's a good idea to bombard user with multiple notifications at the same time. I would suggest an option for users to "track" the thread
or to "watch" it that means that if user marks the thread as "track" this thread somehow important for him and he will be expecting to receive some notifications about new answers in this particular thread.

**Comment by BenoitTallandier** [comment]
@BastiaanVanGaalen I agree with your point.
This US is focused on how a user can see that there is a answer in a previous thread in the channel. 
I'm not convinced by this solution. I'll do some research to understand how other soft are managing this part.
