### ISSUE TITLE
[Story] Channel notifications settings

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#585]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a channel
When I want to change the notification settings of a channel
Then I click on the channel header 
And I click on the notification menu,
And a popup appears 
And I can choose which notification preference I want
```

## Business case

- [ ] In the notification preference, I have the options : "Every message", "@all, @here and @username", "@username only", "Nothing".
- [ ] Options with @username should contain the username of the user (ex, "@all, @here, and @benoit") 

 
## UI UX Design
![channelNotification.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/bc05d649-978a-4155-8ddb-99e91b26de5b)

**Comment by BastiaanVanGaalen** [comment]
@EvGen94 @bobs4462 
https://zpl.io/boEQAeM

**Comment by BenoitTallandier** [comment]
@BastiaanVanGaalen I just saw your design. It can't work : 
On Twake backend, there are 4 status for user notification preference : 
- Every message
- Message containing @all @there @username
- @username only
- no notification

As you understand, it is not option that you can mix. If you check "Every message", you can't use "notification" in the same time. Your design with little check is means the contrary. Is that possible to update your design ? :)
