### ISSUE TITLE
[Story] Open a file preview

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#586]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a channel
When someone sent a file in a channel or a direct chat
Then I can open a preview of this file by clicking on in
```

## Business case
- [ ] Open the server preview sent by the server
- [ ] Type accepted : office document (O365, mac suite, libre office), PDF, images (jpg, jpeg, png, tiff, svg), text (.txt)
- [ ] Resolution will be defined by the server

**Comment by tlle14** [comment]
Hi @BenoitTallandier could you please describe this File preview feature? 
I saw it is implemented in this story, but not in detail https://github.com/linagora/Twake-Mobile/issues/1143
There is some question I want to ask about this preview file feature:
1. What file types will be able to preview in the channel/discussion? (photo/video/text/doc file/eml file/...) 
2. What is the file size/resolution when previewing?

**Comment by tlle14** [comment]
Thank @BenoitTallandier for your quick action.
Hello @huynguyennovem could you please confirm if we have API to implement as defined?

**Comment by huynguyennovem** [comment]
Hi @tlle14 @BenoitTallandier,
Just want to notice that the file previewing (not image) is dependent on the device's supported formats. Because we use external apps to open downloaded files.

**Comment by tlle14** [comment]
Hi @BenoitTallandier I have another question. 
In the preview screen, the image should display in its original ratio or focus on the center?
