### ISSUE TITLE
[Story] mention user in the message input

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#587]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a channel
When I want to mention someone,
Then I type "@XYZ" in the message input
And a popup show users that contain "XYZ" in their name or email
```

## Business case

- [ ] I can see only member of the current channel in the input 
- [x] #797
- [ ] #798
 
## UI UX Design
![mention.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/f0d1f4c6-3f61-4e98-b0ae-abf9178ef5ef)

**Comment by bobs4462** [comment]
@BenoitTallandier 
>  I can see only member of the current channel in the input 

But in web we can mention anyone in the whole workspace, not just the channel members. So currently this feature is implemented the same as on web for the reasons of consistency
