### ISSUE TITLE
[Story] See mention in a message

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#588]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a channel
When someone is mentioned in a message
Then the mention is highlighted
And I can click on it to open the profile page.
```

## Business case

- [ ] #792
- [x] #793
- [ ] Mention that concern me (@myusername, @all, @here, @channel) are highlighted 
 
## UI UX Design
![mentionMessage.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/0eed456e-0068-4a21-97f4-4e0c5afb50a9)

**Comment by tlle14** [comment]
Recently, the only thing work is to highlight the mention. We have 2 problems:
- Cannot show the profile page: https://github.com/linagora/Twake-Mobile/issues/792
- Doesn't have @all, @channel, @here mentions: https://github.com/linagora/Twake-Mobile/issues/793

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen @BenoitTallandier Could you please confirm this one: the mention should display the username or the full name? 

Recently on Mobile, it displays the username only:
![screenshot_19](https://user-images.githubusercontent.com/69950655/127483169-0f2118b1-2885-49fc-a952-9ca71de9d6ba.png)

While on Web, it displays the full name
![screenshot_48](https://user-images.githubusercontent.com/69950655/127483947-f6cb58c8-211a-423f-8018-ba39b1d4caf3.png)

**Comment by BastiaanVanGaalen** [comment]
I suggest that we display user name since user nicknames are sometimes useless when don't identify user.

**Comment by BenoitTallandier** [comment]
I agree, let's display the full name

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 https://zpl.io/bzOYQgX

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 The link is the relevant one, isn't it? Full name user mention in a message bubble. Please, correct me if im wrong.[Uploading... Capture d’écran 2021-09-08 à 00.03.44.png]

**Comment by bobs4462** [comment]
Just review and close this issue, if everything is ok

**Comment by tlle14** [comment]
It's okay now. Any related issue will be logged in another ticket
