### ISSUE TITLE
[Issue] Star channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#598]
## User story summary
[Definition](#Definition)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a channel
When I want to star, or unstar, this channel
Then I open the channel
And I click on the channel header
And I switch the "starred" to on or off
```

## Criteria
- [ ] If I change the "starred" setting, the channel position is changed in the channel vue.

## UI UX Design
![starChannel.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/c5b9540c-db71-49da-ba3d-60267c2a7084)

**Comment by BastiaanVanGaalen** [comment]
@bobs4462  https://zpl.io/aXqW678
