### ISSUE TITLE
[Story] Message system wrapped up

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#602]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a member of a channel
When there are more than 5 system message of response in a row,
Then I can just see the 5 last messages
```

```gherkin
Given I am a member of a channel
When there are more than 5 system message of response in a row,
And I want to consult all these message
Then I can click on a button "show more" to display all system messages of a group
```

## Business case

- [ ] When there are more than 5 system messages of response in a row, they are wrapped up and only 5 last are shown. 
- [ ] When I click on "show more" at the end of a message system group, all message system are displayed
- [ ] When I click on "show less" at the end of a message system group, only 5 last messages are shown

**Comment by bobs4462** [comment]
@BastiaanVanGaalen please check this out
