### ISSUE TITLE
[Story] Channel order

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#607]
## User story summary
[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Business case
- Channel vue is split in 2 sections : pinned & non pinned channel
- Inside these section, by last activity
- Pinned channel do not stick to the top. They can be scrolled as other channel.

## Criteria
- [ ] If a channel A and B are non pinned, A has recent activity than B, A is above B
- [ ] If a channel A and B are pinned, A has recent activity than B, A is above B
- [ ] If a channel A is pinned and B not pinned, A has recent activity than B, A is above B
- [ ] If a channel A is pinned and B not pinned, B has recent activity than A, A is above B
 
## UI UX Design
![channelOrder drawio](https://user-images.githubusercontent.com/22451567/134684286-3671502e-0c74-464b-ae8b-32f6f1d33ecf.png)

**Comment by BastiaanVanGaalen** [comment]
Since we need to be similar to Teams, it's the solution they use: pinned channels:
https://zpl.io/aXqW678

**Comment by BenoitTallandier** [comment]
Let met update this US according teams system. 
FYI here a video of Teams pinned channel order
https://user-images.githubusercontent.com/22451567/134682456-51bedebd-051f-4e29-9f94-37a05ed6db0f.mov

**Comment by BenoitTallandier** [comment]
@BastiaanVanGaalen the US is updated. Here the feedback from the design : 
- Pinned channel are not fixed to the top, they can be scrolled to see other channels
- We don't have to limit the number of pinned channel. :)
