### ISSUE TITLE
Workspace avatars should be with a grey background with initials of two first words in the middle of the avatar

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#608]
Since there are too emojis inside cahnnels, it would be better if we reduce the amount to the minimum and start displaying workspace avatars in grey with initials. ![Capture d’écran 2021-05-31 à 16.07.21.png](https://images.zenhubusercontent.com/5ffec051b78a0364c9757c86/2a5153f6-1a4d-45be-84e1-b62a7c9ca936)

**Comment by tlle14** [comment]
Thank @RockinPaul 
Currently, the characters have different sizes. 
Characters are expected to have the same size when the workspace name is one or two words.
@BastiaanVanGaalen could you please confirm the appropriate character size to display? 


![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/387bca85-b8eb-46ff-8826-eaa74478ffe5)

**Comment by tlle14** [comment]
Thanks,
Retest pass!
![screenshot_74.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/ddbdd87a-9fb3-4b0a-9753-b1ac7bc9f3c3)
