### ISSUE TITLE
Message > Meeting form and GIF image cannot display on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#61]
# Actual Result
Meeting form and GIF display as code on Mobile
![image](https://user-images.githubusercontent.com/69950655/101321975-d4204080-3898-11eb-983e-cd0fdf0b4651.png)
![image](https://user-images.githubusercontent.com/69950655/101324054-2f076700-389c-11eb-85f9-9a1efddf4822.png)

# Expected Result
It should display in acorrect forml as on the Web version

# Environment
All mobile devices

**Comment by bobs4462** [comment]
Alas, that's meeting forms and GIFs (you can only see image preview) aren't supported in this version

**Comment by tlle14** [comment]
Retest pass!
