### ISSUE TITLE
[Story] Companies selection

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#616]
## User story summary
As a user I want to be able to switch between companies, that I have been invited to, so that in case if I'm a member of multiple companies, I can select the necessary one.

[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Business case
- User might have multiple companies
- User can switch to required company (organization) from the app drawer, while switching workspaces

## Criteria
- By default on first login the first company (sorted alphabetically) will be selected
- The chosen company should persist between application restarts 
 
## UI UX Design
https://anna151550.invisionapp.com/console/share/4W2NP2YKPY/655260199
https://zpl.io/a3rq3gx

## Related
#617

**Comment by tlle14** [comment]
Retest pass!
