### ISSUE TITLE
[Story] Workspaces selection

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#617]
## User story summary
As a user I want to be able to switch between workspaces in a given company, that I'm a members of, so that in case if company has multiple workspaces, I can select the necessary one.

[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[Criteria](#Criteria)  
[Notes](#notes)  
[Related](#related)  

## Business case
- User might be a member of several workspace in a single company
- User can switch to required workspace from the main screen

## Criteria
- By default on first login the first workspace of the first company (sorted alphabetically) will be selected
- The chosen workspace should persist between application restarts
- Chosen workspace should be consistent with the chosen company, i.e. it should belong to the chosen company 
 
## UI UX Design
https://anna151550.invisionapp.com/console/share/4W2NP2YKPY/655260199
https://zpl.io/a3rq3gx

## Related
#616

**Comment by bobs4462** [comment]
## User story summary
As a user I want to be able to switch between workspaces in a given company, that I'm a members of, so that in case if company has multiple workspaces, I can select the necessary one.

[Business case](#Business-case)  
[UI/UX Design](#UI-UX-design)  
[UI/UX Design](#Criteria)  
[Notes](#notes)  
[Related](#related)  


## Business case
- User might be a member of several workspace in a single company
- User can switch to required workspace from the main screen

## Criteria
- By default on first login the first workspace of the first company (sorted alphabetically) will be selected
- The chosen workspace should persist between application restarts
- Chosen workspace should be consistent with the chosen company, i.e. it should belong to the chosen company 
 
## UI UX Design
https://anna151550.invisionapp.com/console/share/4W2NP2YKPY/655260199

## Note

## Related
#616

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen @bobs4462 please confirm:
1. After selected a workspace, it opens the corresponding channel list, is this correct?
2. How can we open the workspace setting screen? 
 ![image](https://user-images.githubusercontent.com/69950655/121662836-fd33bf00-cacf-11eb-859c-bc87defdf50c.png)
3. Is the Workspace setting screen is only accessible by Admin/Company Owner?

**Comment by BastiaanVanGaalen** [comment]
@tlle14  As UI gets old within hours, this workspace switching logic became obsolete the day i designed it) Last Tuesday, new UI was approved by Alexandre where you switch between workspaces from within a side-menu on the left. You can see the updates by following the link:
https://zpl.io/VK7DMR8

@manhduc-nguyen Could you please confirm that you are working on the new [workspace switching mechanism](https://zpl.io/VK7DMR8) in order for the @tlle14  to be up-to-date on that)

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen 
I will ignore the design in #1, #2, and #3 
#4 Channel list will be ordered by Alphabetical as in Company list?

**Comment by tlle14** [comment]
Retest pass!
