### ISSUE TITLE
User feedback > Request for a quick scroll (elevator scroll) for the long channel list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#629]
# Actual Result
Original: 
`also, in the app, there is no elevator to scroll quickly in long channel with a lot of channel... it could be more than useful.`

# Expected Result
Please consider if we need the improvement or a better solution for a quick scroll.

# Environment
Production

**Comment by tlle14** [comment]
Please take a look when you have time @bobs4462 @RockinPaul @BastiaanVanGaalen

**Comment by RockinPaul** [comment]
@BastiaanVanGaalen please take a look. I'll be able to implement this with a Floating button, for example, which is a common approach for the case.

**Comment by tlle14** [comment]
If we have a search bar for a channel list, I don't think we need a quick scroll. 
And, if we have a search bar for a direct list, why do we need a "new direct chat" screen?

**Comment by bobs4462** [comment]
closing this one and we will implement a search bar for this
