### ISSUE TITLE
It is still be able to connect to the default server even the inputted server is invalid

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#644]
# Actual Result
When inputted an invalid server address, it shows a message "invalid host". 
If the user closes the choosing host screen then login, it keeps the invalid host in the textbox but connecting to the default server. 

https://user-images.githubusercontent.com/69950655/123579748-b0a3ef80-d802-11eb-99e5-962318914afb.mp4

# Expected Result
Please work with our UX designer/BA to make a flow. This is my suggestion:
1. The default server should be prefilled in the textbox
2. When input an invalid server address then close the screen, it should change the invalid server to the default one. OR it shouldn't be able to connect.

# Steps to reproduce
1. Open the app
2. On `Login` screen, tap on "Choose the server"
3. On `Server Connection preference` screen, input an invalid server address.
It will display an error message "invalid server". 
4. Tap on "x" button on the top left to close `Server Connection preference` and back to the `Login` screen
5. On `Login` screen, input the valid credential
6. Tap "login" button. Verify that it is able to connect to the default server.

# Environment
Build version: 3.0.0
Device: Xiaomi Redmi Note 9 - Android 10 - 6.53 inch

**Comment by EvGen94** [comment]
Hi @tlle14 
Now when input an invalid server address then close the screen the invalid server changes to the default one or the last validated

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass on 3.0.1

https://user-images.githubusercontent.com/69950655/124082642-22846f00-da77-11eb-800e-f1430fb030b1.mp4
