### ISSUE TITLE
No "internet connection" warning and no "pulling to refresh" function 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#646]
# Actual Result
The new app doesn't have a `pull to refresh` function and a "no internet connection" warning. 
There's nothing to acknowledge the user about the current situation. 

https://user-images.githubusercontent.com/69950655/123602714-3d5ea580-d823-11eb-9a1b-0c0829d739b3.mp4

# Expected Result
Please work with our BA/Designer to consider adding these functions to the app. OR the app should have automatically refresh function.

# Environment
Build version: 3.0.0
Device: Xiaomi Redmi Note 9 - Android 10 - 6.53 inch

**Comment by bobs4462** [comment]
@BastiaanVanGaalen is there a new design for notifying the user about internet connection loss?

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 https://zpl.io/anzNdvl

**Comment by bobs4462** [comment]
Incorrect design, we will always display channels list, even if we are offline

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 @EvGen94 
No internet connection snack bar: https://zpl.io/VOE1rMl
Swipe to refresh: https://zpl.io/a77ek1M

**Comment by bobs4462** [comment]
@BastiaanVanGaalen what is the purpose of "try again" button?

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Is there any purpose? If not, let's scratch the action off the snack bar)

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 "Try again" has been removed: https://zpl.io/VOE1rMl

**Comment by tlle14** [comment]
Thanks,
The app now has an Internet connection snackbar. 
https://images.zenhubusercontent.com/309637937/1c3bcf08-feef-43d6-8241-0f4064eae5b4/videoad592104_9b4f_42c8_9fcf_9b70cb6b112bvideo.mp4
