### ISSUE TITLE
Mention text in a preview message exposes user ID

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#652]
# Actual Result
Mention text in a preview message exposes user 
![image](https://user-images.githubusercontent.com/69950655/123751780-49f60300-d8e2-11eb-941b-5585554cc4cd.png)

# Expected Result 
The preview message shouldn't expose userID in a mention text

# Environment

- Build version: 3.0.0
- Device: Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by bobs4462** [comment]
Fixed, should be out in next build

**Comment by tlle14** [comment]
Thank @manhduc-nguyen 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/4bd3e647-a07a-4ff4-847a-4af9723811c8)
