### ISSUE TITLE
Create Workspace > It always displays limitation popup when adding over 5 members

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#653]
# Precondition
- User Story: [AC1] https://ci.linagora.com/linagora/lgs/saas/portal/specifications/issues/197
- Owner email has been verified

# Actual Result
1. When creating a new workspace, it always restricts when adding more than 5 members to the workspace, even the owner's email is verified.
https://user-images.githubusercontent.com/69950655/123758737-6ea1a900-d8e9-11eb-9276-0312c682401f.mp4

2. The popup content is confusing. The Email "alexandre@liangora.com" is fixed text
![image](https://user-images.githubusercontent.com/69950655/124063519-43d86180-da5d-11eb-8cb6-7c0ef8997c5b.png)

# Expected Result
1. Please follow the correct business:
As I confirmed with Console team:
- When the owner email is not verified, the restrict popup should be shown when the owner/admin adding more than 5 members to the workspace.

   + If the first time he adds 3 members to the workspace, the second time he adds 3 more members, the popup should be shown. 
   + If the first time he adds 3 members to the workspace, the second time he adds 2 more members, the popup should NOT be shown

- When the owner email is verified, the restrict popup should NOT be shown when the owner/admin adding more than 5 members to the workspace.

2. The popup content should be more clear for the user. Why don't we use the same content on the Web (except the comma part)? 

# Environment
- Build version: 3.0.0
- Device: Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by BastiaanVanGaalen** [comment]
<img width="592" alt="Capture d’écran 2021-06-29 à 18 07 37" src="https://user-images.githubusercontent.com/75843710/123822367-e4ffd480-d904-11eb-8af0-af312c2e31c7.png">

This pop-up with a limitation message
@tlle14

**Comment by RockinPaul** [comment]
Anyone is taking care of this? Otherwise, I've taken it on my own for now.

**Comment by tlle14** [comment]
Hi @RockinPaul sorry for this late. I will retest and inform you the result later. Please skip this for now.

**Comment by tlle14** [comment]
I updated the description, please check it again @RockinPaul @BastiaanVanGaalen

**Comment by bobs4462** [comment]
Yes, the issue exists, because mobile application doesn't have the information, regarding whether user has been verified or not. @RomaricMourgues can you please point us the direction where can we obtain that data?

**Comment by RomaricMourgues** [comment]
Yes, you get a "is_verified" field on the https://beta.twake.app/ajax/users/current/get endpoint, and also a "is_verified" on the node endpoint GET /internal/services/users/v1/users/:user_id (see this documentation for node: https://www.notion.so/twake/Rest-APIs-07c0294728794901b8c8a4518ad5852c)

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462 
https://images.zenhubusercontent.com/309637937/853b919b-7f0a-43b8-8d1e-b47814072cda/video76c60009_0f39_4328_af23_29530057c292video.mp4
