### ISSUE TITLE
Fixed text in the welcome message of a new channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#654]
# Actual Result
It always display channel name as `Test`
![image](https://user-images.githubusercontent.com/69950655/123761473-0e603680-d8ec-11eb-91ab-512f534efb4d.png)

# Expected Result
"Test" should be replaced by the channel name

# Environment

- Build version: 3.0.0
- Device: Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by bobs4462** [comment]
Should be fixed in the next build

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/3f2048cf-10c1-494a-b3bb-ea8dff7ca7ab)
