### ISSUE TITLE
The channel cannot load a full chat history

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#657]
# Precondition
A channel history contains a thread that has about 30 replies
The user is added to a channel after the long thread

# Actual Result
On Mobile, the new added user cannot see a chat history before the long thread

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/123775375-86345e00-d8f8-11eb-817c-eca1244c4f35.png)

On Web:
![image](https://user-images.githubusercontent.com/69950655/123780077-0230a500-d8fd-11eb-810b-addf166cf24d.png)

# Expected Result
The chat history should be loaded completely

# Environment
- Build version: 3.0.0
- Device: Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by tlle14** [comment]
On Production, it shows a gray screen for the unloaded history. The same issue but not the same reenactment way.
![image](https://user-images.githubusercontent.com/69950655/123912901-cc94c600-d9a7-11eb-9b2e-77a889005b99.png)

**Comment by bobs4462** [comment]
I will try to reproduce this one

**Comment by tlle14** [comment]
Did you fix anything? Or this issue came from the server-side? 
I don't think it happens anymore
