### ISSUE TITLE
Cannot load messages in the direct chat 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#658]
# Actual Result
 Mobile cannot retrieve message in the direct chat

# Expected Result
Messages in the direct chat should be displayed on mobile

# Environment

- Build version: 3.0.0
- Device: Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by bobs4462** [comment]
Please retest with the latest build

**Comment by tlle14** [comment]
Still get the problem @bobs4462 :(

**Comment by bobs4462** [comment]
Do you see a grey screen, or there's simply no messages in direct chat?

**Comment by tlle14** [comment]
Hi, please watch this video
https://user-images.githubusercontent.com/69950655/123922206-fc48cb80-d9b1-11eb-81a5-5bc928cd81fb.mp4

**Comment by bobs4462** [comment]
Should be fixed in the next build

**Comment by tlle14** [comment]
Thank @bobs4462 Retest pass!
Now we can load messages in a direct chat
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/565701bb-a472-4aeb-9478-66255bdd9d0f)
