### ISSUE TITLE
It keeps displaying splash screen even the user logged in successfully

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#661]
# Actual Result
When the user logged in successfully but the app still shows the splash screen instead of the channel list. 
The user needs to restart the app to access the app. 

# Expected Result
It should show the channel list after user logged in successfully.

# Environment
- Build version: 3.0.1
- Device: 
     Samsung Galaxy A51 - Android 11 - 6.5 inch
     iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
@tlle14 I was able to login to https://beta.twake.app without any issues, though it took 2 minutes to sync my data (if you have more channels and workspaces, it might take more time).

**Comment by bobs4462** [comment]
I also logged into https://web.qa.twake.app using your test account, no problems here either

**Comment by tlle14** [comment]
Hi @bobs4462 2 minutes is too long. Could you please find a way to improve this feature? It should take about 10s-20s to login.

**Comment by tlle14** [comment]
And hey, i have to wait 4 minutes >_<

**Comment by bobs4462** [comment]
Ok, working on that

**Comment by bobs4462** [comment]
reduced the time to 30 seconds + 5-10 seconds for the authentication to complete. We will show a different screen with progress bar when sync is in progress

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462 
It takes an average of 20 seconds to login. 
https://images.zenhubusercontent.com/309637937/d9d3bec3-55ab-4996-b78c-d921ca91fa15/video5e157957_b372_4cdd_a200_b26c778912ddvideo.mp4
