### ISSUE TITLE
Mixing up channel when switching between workspaces

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#662]
# Actual Result
When switching between workspaces, let's say workspaceA and workspaceB, channel list of workspaceA is shown on workspaceB

https://user-images.githubusercontent.com/69950655/123900847-09ef5880-d994-11eb-8e1e-12e21b0f211b.mp4

# Expected Result
It should show the channel list of the corresponding workspace even when the user switching workspaces fastly 

# Environment

- Build version: 3.0.1
- Device:
    iPhone 11 Promax - iOS 14.4 - 6.46 inch
- Production server

**Comment by bobs4462** [comment]
Hello @tlle14 , in provided video I haven't noticed, that the channels were mixed up, can you please describe which channels from which workspace are being show in a wrong place?

**Comment by tlle14** [comment]
Sorry @bobs4462 for the evidence. 
When switching from Software workspace to Vietnam Workspace, it shows Software channel list in VN workspace. 

 Software channel list:
![image](https://user-images.githubusercontent.com/69950655/123920661-652f4400-d9b0-11eb-8b97-88cb0abb62f3.png)


VN channel list:
![image](https://user-images.githubusercontent.com/69950655/123920559-49c43900-d9b0-11eb-9cc6-291910d5d74d.png)

Sometimes it re-update the channel list of the corresponding workspace, sometimes it doesn't

**Comment by bobs4462** [comment]
Should be fixed in the next build

**Comment by hantt12** [comment]
Fixed in Version 3.0.0 (22) 
Tested in iPhone 11 , using QA backend
