### ISSUE TITLE
Message > Some messages in the channel are duplicated

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#664]
# Actual Result
Some messages in the channel are duplicated and having an incorrect reply counter. 

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/123919545-395f8e80-d9af-11eb-8038-3305c495e9b5.png)

On Web
![image](https://user-images.githubusercontent.com/69950655/123919398-18973900-d9af-11eb-8eb9-c87b2954a6b6.png)

# Expected Result
The messages shouldn't be duplicated

# Environment

- Build version: 3.0.1
- Device:
     Samsung Galaxy A51 - Android 11 - 6.5 inch
     iPhone 11 Promax - iOS 14.4 - 6.46 inch
- Production

**Comment by bobs4462** [comment]
Core backend issue, I don't when they have time to fix it

**Comment by tlle14** [comment]
The issue is no longer happens

**Comment by tlle14** [comment]
Reopen for the issue with replies in a thread

**Comment by tlle14** [comment]
Retest pass!
I don't see the issue anymore
