### ISSUE TITLE
Create Direct Chat > It keeps loading Recent chat and People in New direct chat screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#666]
# Actual Result
When opening a New Direct chat screen, it keeps loading the Recent Chats and People 
https://user-images.githubusercontent.com/69950655/123932536-bee93b80-d9bb-11eb-9d16-9eb0db6c0df6.mp4

# Expected Result
It should be able to load the Recent Chats list and People list. 

# Environment
- Build version: 3.0.1
- Device:
     Samsung Galaxy A51 - Android 11 - 6.5 inch
     iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
Should be fixed in next build

**Comment by tlle14** [comment]
Hi @bobs4462 
Now we can load the People and Recent list but it's kinda slow for the first time or every time the workspace has updated. I don't think we need to display all people in the workspace. 
The loading icon looks quite annoying every time I want to create a new direct chat. 

https://images.zenhubusercontent.com/309637937/4a7d1566-e27c-4893-b339-8aedd0dc8c2d/videoa2f3d840_640a_4823_be62_a99545824a31video.mp4

**Comment by tlle14** [comment]
But it's an UX issue. I will create another ticket
