### ISSUE TITLE
Mention is sent as a normal text

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#668]
# Actual Result
On mobile, when sent a mention, it is displaying as normal text on both web and mobile. There also has no notification for the mention. 

**On Mobile:**
https://user-images.githubusercontent.com/69950655/123944924-d29a9f00-d9c7-11eb-810e-af3c63c2c3c3.mp4

**On Web:**
![image](https://user-images.githubusercontent.com/69950655/123945160-0d9cd280-d9c8-11eb-8ce6-b52f817ebffc.png)

# Expected Result
1. The mention should display as in the design
![image](https://user-images.githubusercontent.com/69950655/123945351-40df6180-d9c8-11eb-84c6-8f878d000fc4.png)

2. There should have a notification when the user is mentioned

# Environment

- Build version: 3.0.1
- Device:
 Samsung Galaxy A51 - Android 11 - 6.5 inch
 iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
Fixed, mentions are highlighted and should trigger notification

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed when mentioning multiple accounts at a time
![image](https://user-images.githubusercontent.com/69950655/124251002-a01bae00-db4f-11eb-975a-6598294a9218.png)

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed
On Mobile, it is displaying as a mention text, but on Web, some mentions are just a normal text

On mobile:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/4b463d44-3643-4388-94f4-9b2ce46600c3)

On Web:
![Peek 2021-07-15 10-13.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9f34e2ba-cc23-4925-bbfd-1cd503896cb7)

**Comment by bobs4462** [comment]
Are you sure that those user have first and last names?

**Comment by tlle14** [comment]
> Are you sure that those user have first and last names?

Hi @bobs4462 now the user has only one name 
![name](https://user-images.githubusercontent.com/69950655/126924875-e85e3ea9-8184-4364-868c-ea4421cc063c.png)

**Comment by bobs4462** [comment]
@tlle14, hi, I couldn't reproduce this issue, can you retest it again, maybe the backend changes affected it before.

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue still happens
![screenshot_72](https://user-images.githubusercontent.com/69950655/128121696-289d2224-bbf2-4bdf-874e-caa259b2236a.png)

**Comment by bobs4462** [comment]
Hmmm, can you please describe a way to reproduce it, or does it happen randomly?

**Comment by tlle14** [comment]
I did it normally with multiple users

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue persists in the app 
Please see how I reproduce it on App 
https://images.zenhubusercontent.com/309637937/1e3b247e-8a7a-41c5-bc66-b1004b1c1f6e/video6326293f_b1c3_4a22_88a3_33d5232a2ae1video.mp4

And how it displays on Web:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f1f205e3-6954-4909-8385-be62e7b7ba42)

**Comment by bobs4462** [comment]
@tlle14 can you share with me, the creds of your test user, along with the name of workspace/channel that you were testing it with?

**Comment by tlle14** [comment]
@bobs4462 Here you go:
cyan@yopmail.com / Secret1@
Channel: https://web.qa.twake.app/client/nENULS1vCws66wqzPUyU93/c/1VdBzyUKMYNuPHcsRXMxeW

**Comment by tlle14** [comment]
Blocked testing: cannot login to QA env on Web

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
Mention on Mobile:
![screenshot_18.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/140e809c-c45a-4acf-bce1-8280712f1b20)

Displaying on Web:
![screenshot_19.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/cf6b3c84-17a5-42e6-838d-b98c76a0a9aa)
