### ISSUE TITLE
Sometimes channel list is suddenly freezing

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#672]
# Precondition
- After creating a new channel 
- OR the app is unused for a long time about 30mins

# Actual Result
Sometimes the channel list is like freezing, I cannot tap to open any channel in the list

https://user-images.githubusercontent.com/69950655/124090684-45b31c80-da7f-11eb-962d-fe0d0224c92e.mp4

# Expected Result
Please investigate, it's like the session timeout or losing internet connection but unable to recover the app

# Environment

- Build version: 3.0.1
- Device:
     Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by bobs4462** [comment]
Was unable to reproduce it after fixed #678, please retest it in the next build

**Comment by tlle14** [comment]
It seems to no longer happen.
