### ISSUE TITLE
"See all answers" button is lost after back from the thread screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#674]
# Actual Result
After reply a message then back from the thread screen, the "see all answers" button disappears
https://user-images.githubusercontent.com/69950655/124097046-5ebecc00-da85-11eb-9f21-e980a6a19580.mp4

# Expected Result
After going back from the thread screen, the see all answers button should shown and be updated 

# Environment

- Build version: 3.0.1
- Device:
     Samsung Galaxy A51 - Android 11 - 6.5 inch
     iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
Yes, there's an issue with responses count on backend, the same issue is causing this bug #664 
I've informed Romaric, he's looking into this

**Comment by tlle14** [comment]
Hi @bobs4462 is this issue fixed on the backend or you just sent it back because it isn't from Twake Mobile? 
I still see the counter is not updated when the user goes back from the Thread screen.

**Comment by bobs4462** [comment]
Well, it should be updated, but there might be a time lag. If your real time message syncing works (even with time lags), then the counter update should also work, as it uses the same underlying mechanism

**Comment by tlle14** [comment]
At least the button "See all answers" is not lost. 
I can close this issue
