### ISSUE TITLE
Create direct chat > unable to search people to create a direct chat

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#676]
# Actual Result
Cannot find people by email or name to create a direct chat

https://user-images.githubusercontent.com/69950655/124100776-f1149f00-da88-11eb-8954-5c7687b212c1.mp4

# Expected Result
It should return the search result

# Environment

- Build version: 3.0.1
- Device:
     Samsung Galaxy A51 - Android 11 - 6.5 inch
     iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
Could only reproduce it with your test account. Fixed (next build)

**Comment by tlle14** [comment]
I can search by email, but how about searching by username? 
Do you have a plan to apply this feature? 
@bobs4462

**Comment by tlle14** [comment]
I can search the user now. Thank you 
https://images.zenhubusercontent.com/309637937/73ee2368-a625-4dc7-b926-524d0acdc890/rpreplay_final1625208188.mp4
