### ISSUE TITLE
Messages are displaying in a wrong channel when switching too fast between channels

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#678]
# Actual Result
When switching a bit fastly between channels, the messages of this channel will display in another channel.
https://user-images.githubusercontent.com/69950655/124103190-3a65ee00-da8b-11eb-892d-52b19f688aa7.mp4

# Expected Result
The messages should be displayed in the correct channel

# Environment
- Build version: 3.0.1
- Device:
     Samsung Galaxy A51 - Android 11 - 6.5 inch
     iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
yes, can confirm it, and happy to tell you that it's also fixed. It's related to #662, incorrect management of screen states

**Comment by tlle14** [comment]
Retest failed on 3.0.2 @bobs4462 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/59aef3fe-2222-477d-9364-681f58aefd63)

**Comment by bobs4462** [comment]
@tlle14 I'm unable to reproduce it in the latest build on android, both on emulator and a real device. And according to programmed logic it shouldn't be able to load the messages from wrong channel. But the issue definitely was present in the previous build, so can you make sure that you are running the latest build?

**Comment by tlle14** [comment]
You can follow these steps:
1. Open channelA
2. Scroll down to explore the chat history
3. While channelA chat history is loading, you give up and switch to the channelB.
4. Verify the issue: channelA message is shown on channelB

**Comment by bobs4462** [comment]
Oh, that makes sense, thanks for the hint, I'll fix it in the next build

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
