### ISSUE TITLE
Loading message in the channel at first is delaying a bit

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#681]
# Precondition
First time opening the app

# Actual Result
1. After workspaces and channel list is loaded, tap to open a channel, it took about 20s to show message history in the channel

2. When the channel is loading messages, it shows an inappropriate message 
![image](https://user-images.githubusercontent.com/69950655/124237845-2d580600-db42-11eb-9cdd-018bc495d8a4.png)

3. After finishing the loading task, it goes back to the default workspace of the default company.

# Expected Result
1. Please continue to find the best way to load messages data in the app. The faster is the better. 
2. When loading data, the channel should show a loading icon instead of the message for a new channel
3. After loading successfully, it should stay at the channel 

# Steps to reproduce
1. Install the app
2. Login to the app with a valid credential
3. Switch from the default workspaceA to the workspaceB
4. Open a channel in workspaceB
- the message in the channel is loading, showing as if the channel is empty.
- then it goes back to the WorkspaceA

# Environment
- Build version: 3.0.2
- Device:
     Samsung Galaxy A51 - Android 11 - 6.5 inch
     iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
Well, the issue here is the following:
1. We are not syncing messages to local storage, to reduce sync time
2. When you open a channel the first time it looks up the messages in local storage and finds none, and make a request to remote server
3. It takes time to fetch messages from remote server, because our proxy is slow

@BastiaanVanGaalen @romanesko any ideas on how we can improve this one?

**Comment by BastiaanVanGaalen** [comment]
Ok, i will prepare a design for this case!

**Comment by BastiaanVanGaalen** [comment]
@tlle14 I've prepared case handler, there will be animation of loading chat data.

@bobs4462 Hope, somebody from front-end comrades can take this task over

**Comment by BastiaanVanGaalen** [comment]
https://zpl.io/bPBz9zl

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen @EvGen94 
The loading screen appears when data in the channel is loading
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/0662fe06-79ac-4ddc-a5ec-bb1b53f7cf52)
