### ISSUE TITLE
Message > The messages/ reactions/ reply  cannot be auto-updated

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#688]
# Precondition
There has a channel 
UserA is on Twake Web
UserB is on Android
UserC is on iOS

# Actual Result
When UserA sends a message to the channel, UserB can receive the message instantly, but UserC cannot see the channel updated. 
The issue also happen when sending a message from android. 
![image](https://user-images.githubusercontent.com/69950655/124424153-bc5a5d80-dd90-11eb-9d1b-6611149d8ae4.png)

**On Android**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/5b1ad02a-2e61-4d93-ac1d-b9c7bb4ecae9)
**On iOS**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/44bda855-6033-4ecd-8e1f-523f4cd56be1)

# Expected Result
The messages on Mobile should be instantly updated. 

# Environment

- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed!
The realtime update doesn't happen when sending messages from Twake Web to Twake Mobile

**Comment by bobs4462** [comment]
@tlle14, does this happen randomly, or does it never work?

**Comment by tlle14** [comment]
It seems randomly happens. Now it works like a charm on my device, but wasn't in this morning.

**Comment by tlle14** [comment]
Retest pass!

**Comment by tlle14** [comment]
Retest pass!
