### ISSUE TITLE
Reactions in a thread screen doesn't update instantly

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#694]
# Actual Result
In a thread screen, when react or unreact the parent message/a reply, nothing happens.
User needs to reopen the thread to see the change

https://user-images.githubusercontent.com/69950655/124464328-45d45480-ddbe-11eb-8cb2-ae139d6a0ee6.mp4

# Expected Result
Reactions in a thread screen should be updated instantly

# Environment
- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
@tlle14, does the issue still happen

**Comment by tlle14** [comment]
Thanks,
The issue is no longer happens
https://images.zenhubusercontent.com/309637937/ed0be7d9-0808-44f7-b608-b58a365b46f4/rpreplay_final1631085198.mp4
