### ISSUE TITLE
On Login screen, Sign Up button doesn't work

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#695]
# Actual Result
On Login screen, Sign Up button doesn't work
https://user-images.githubusercontent.com/69950655/124466981-6d78ec00-ddc1-11eb-846a-1bfca8788bc5.mp4

# Expected Result
When tapping on Sign Up button, it should redirect to the Sign Up screen

# Environment

- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by gupta29470** [comment]
Did you implement **onPressed** parameter in created button.

```dart
TextButton(
    onPressed: () {
        Navigator.push(
        context, MaterialPageRoute(
             builder: (_) => SignupScreen(),
        ), 
      );
    }
    child: Text("Sign up"),
)
```

If you want to use Text then wrap Text Widget under Gesture Detector
```dart
GestureDetector(
    onTap: () {
        Navigator.push(
        context, MaterialPageRoute(
             builder: (_) => SignupScreen(),
        ), 
      );
    }
    child: Text("Sign up"),

)
```

**Comment by EvGen94** [comment]
Hi @tlle14 
This is not relevant now, sign up is working on web.qa, but while there is a problem with creating a default workspace on the backend side, this function is disabled in the newest build

**Comment by tlle14** [comment]
This issue is outdatd one. 
I should close it. Thanks for reminding.
