### ISSUE TITLE
[User story] Swipe to reply feature

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#696]
Based on user feedback we need to add additional feature on the messages screen (channel level). 

As a user, when I swipe the message I should be redirected to the corresponding thread screen.
After redirect, user input field should be activated immediately, so I can start typing the message right away.

This feature should only be available for the top level (channel level) messages, because you cannot create a thread within thread in Twake.

This feature should be complementary to the traditional long press to reply functionality. 

The feature design mockups can be found here:
https://zpl.io/agmoE0M

**Comment by tlle14** [comment]
Hi @EvGen94 
I don't think this feature conforms to the idea has been described.

# Actual Result
User has to Swipe and Press the reply button to open the corresponding thread
https://images.zenhubusercontent.com/309637937/ab7ce042-1a9e-4471-9170-2d6fe8dc9151/videocbb74fab_4fd0_47e4_bdd0_fa184d2cf925video.mp4

# Expected Result
```
As a user, when I swipe the message I should be redirected to the corresponding thread screen.
After redirect, user input field should be activated immediately, so I can start typing the message right away.
```
That means after swipe left:
- the corresponding thread screen should be opened automatically
- the keyboard should be opened, the chat textbox should be focused on
Everything should be ready for user to start typing a reply. As in this video:
https://images.zenhubusercontent.com/309637937/6254e75b-2f2e-4f35-9585-f47fa76b5b6c/rpreplay_final1626340968.mp4

**Comment by tlle14** [comment]
Hi @EvGen94 
**1. When swipe left to reply, the keyboard is not enabled.**
=> The keyboard should be enabled when swiping to reply

**2. The parent message in the reply displays incorrectly**
The maximum character in the reply quote is long. 
![screenshot_53](https://user-images.githubusercontent.com/69950655/127595468-4fab19a3-a326-4b22-bf2e-a06d4ac9763f.png)
=> We should define the maximum characters of the quote in the reply. As in the design, I saw the maximum is 2 lines displaying. 
@BastiaanVanGaalen what is your opinion? 
![screenshot_54](https://user-images.githubusercontent.com/69950655/127596139-a999af29-a58c-47af-8007-c819a9c0bd06.png)

**3. The font size is not the same as the design**
The text `Reply to <username>` is bigger than the quoted text and the message text
=> The font size should follow the design. 
Message text: 15px
Reply to <username>: 12px
Quoted message: 13px

**Comment by tlle14** [comment]
Thank @EvGen94 
1,2 are pass!
About 3, I'm not sure. The font size seems not to match the design, but I think it's okay. 
@BastiaanVanGaalen How do you think?
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2963d53b-6bb4-406e-a261-3b96632cbc48)

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Font size is ok, during app review i will point out all such inconsistencies, though

**Comment by BastiaanVanGaalen** [comment]
@EvGen94 Can you please arrange for our app to start using system-defined fonts, in particular, SF Pro display/text for iOS and Roboto for Android.

**Comment by bobs4462** [comment]
Will work on font update here https://app.zenhub.com/workspaces/twakemobile-5fa5101d98879700119ccea9/issues/linagora/twake-mobile/835. You can close this one if everything else is ok @tlle14

**Comment by tlle14** [comment]
Thank guys!
