### ISSUE TITLE
Displaying Account screen after logged out

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#714]
# Precondition
When the user want to logout, he taps multiple times on his name on the sidebar to open the Account page (he doubled taps as a habit or simply the app doesn't work - the internet issue again - after 1 tap makes him became impatient)

# Actual Result
When double taps on the sidebar, it calls many requests to return the Account screen. After logged out, the Account page is displaying for the user because of the latency

https://user-images.githubusercontent.com/69950655/124701896-93190900-df19-11eb-9e11-7fefd8fe7203.mp4

# Expected Result
When double taps on the sidebar, it should call 1 request and block the button 
Some screens is only displayed when it is authorized.

# Environment

- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
Fixed, account screen now should show instantly (next build)

**Comment by tlle14** [comment]
Does it seem to be fixed by caching the Account page? 
Thank @bobs4462 
Retest pass!

**Comment by tlle14** [comment]
Does it seem to be fixed by caching the Account page? 
Thank @bobs4462 
Retest pass!

**Comment by bobs4462** [comment]
> Does it seem to be fixed by caching the Account page? 
Yes the issue was with incorrect usage of local cache when fetching user account

**Comment by tlle14** [comment]
Hi @bobs4462 
This issue is randomly happening when I tapping on the Logout button many times
Do you think the logout button should be blocked after 1 tap?
https://images.zenhubusercontent.com/309637937/dc874933-ad53-4084-a13e-110da9183734/video46c24fe9_5c98_485f_a18e_3fb4af4f0379video.mp4

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed
Then it displays a Welcome screen 2 times. 
https://images.zenhubusercontent.com/309637937/1f5f958a-9448-4e24-9b62-e62bed909f0c/video2850406c_cfe7_48f7_b899_e0d85f4280c1video.mp4

**Comment by tlle14** [comment]
Thanks,
Retest pass!
https://images.zenhubusercontent.com/309637937/3784b26a-6464-4a71-8315-1d7dd35085a2/20211001_150614__1_.mp4
