### ISSUE TITLE
Deleted Workspace is still displaying on menu sidebar after it is removed on Web

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#717]
# Precondition
- The workspace is created on Mobile App by Company Admin
- Then the workspace is removed on Web by the same Admin account
- Verify the update on Mobile App

# Actual Result
On Mobile App, the deleted Workspace is displaying while the menu sidebar is pulling to refresh

**While pulling to refresh**
![1FA50AB4-FC8A-434A-A98E-E2DD38B079A7](https://user-images.githubusercontent.com/69950655/124719667-96b88a00-df31-11eb-8dd4-7358a6e59db0.jpg)

**After refreshed the sidebar**
![image](https://user-images.githubusercontent.com/69950655/124719650-928c6c80-df31-11eb-9fbd-43d536897e93.png)

# Expected Result
- The deleted workspace shouldn't display anymore
- About pulling to refresh the sidebar, I thought your solution will be fetching the update every time the user opens the sidebar, which means we don't have to pull to refresh. Could you please confirm? 

# Environment

- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@tlle14 hi, are you sure you can delete workspace on web? Because on QA server it seems, that workspace deletion is broken

**Comment by tlle14** [comment]
Hi @bobs4462 I don't see the workspace displaying on Web, so I think it is deleted successfully. 
But if you are using a member account to create a workspace, that workspace cannot be deleted

**Comment by bobs4462** [comment]
But it still allows me to go through the steps to delete the workspace, but the workspace doesn't go anywhere after deletion. But ok, I'll improve the sync of workspaces to account for removed workspaces

**Comment by tlle14** [comment]
Hi @bobs4462 
Is it relating to cache when the deleted workspace displays then disappears while refreshing the workspace list? 

https://images.zenhubusercontent.com/309637937/1bcc872b-b502-4904-bf3c-ac213b08492f/videob0891db5_48d3_4414_9274_1641f145736avideo.mp4

**Comment by bobs4462** [comment]
oh, yes, it seems the cache is not updated properly, let me check

**Comment by bobs4462** [comment]
Ok, so, it should only happen once, i.e. after workspace has been deleted, it will remain in cache until you open a side drawer, after that you should not see it happening again, as the local cache will be updated too

**Comment by tlle14** [comment]
Retest pass! Thank @bobs4462
