### ISSUE TITLE
Workspace list > It doesn't open the corresponding channel list when switching the workspace while opening Chats tab

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#718]
# Precondition
The user is in the Chats tab

# Actual Result
When switching to another workspace, it stays at the Chats tab
https://user-images.githubusercontent.com/69950655/124726230-c4083680-df37-11eb-8cfa-93d90a27afea.mp4

# Expected Result
It should open the corresponding Channel list 

# Environment

- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@tlle14, do you mean we should switch to channel tab when switching workspaces?

**Comment by tlle14** [comment]
Yes, I think we should focus on the channel list when switching the workspace

**Comment by bobs4462** [comment]
@BastiaanVanGaalen do you agree that we should implement this feature?

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462 
https://images.zenhubusercontent.com/309637937/3661efc9-9561-411e-8f9f-506c8637103f/videod81cc996_7434_4e1d_a769_b2b0a3be4a86video__1_.mp4
