### ISSUE TITLE
Create Channel > Frequently contacted doesn't show any accounts

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#719]
# Precondition
While creating a private channel

# Actual Result
When adding members to the new private channel, the Frequently contacted doesn't show anything.
![image](https://user-images.githubusercontent.com/69950655/124734931-c8d0e880-df3f-11eb-942a-f120ff27dff3.png)

# Expected Result
Please confirm:
What would the Frequently contacted show? Is it the same list as the direct list?

# Environment

- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by manhduc-nguyen** [comment]
@tlle14 Hi, Its not a bug because the feature is not implemeted yet.

**Comment by tlle14** [comment]
Okay thank @manhduc-nguyen for your confirmation. This is not an issue then,
