### ISSUE TITLE
Create Channel > Find and add member to the private channel issues

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#721]
# Precondition
Creating a private channel

# Actual Result
1. Search result is clear after adding a user to the list
=> The search result shouldn't disappear after adding a user to the list
https://user-images.githubusercontent.com/69950655/124740070-9ecdf500-df44-11eb-8a63-cadde856a727.mp4

2. The blue tick is in low resolution. It looks blur.
=> The blue tick should have a good quality
[image](https://user-images.githubusercontent.com/69950655/124742805-464c2700-df47-11eb-8be9-114f5ca46fdd.png)

3. It is able to add a user multiple times to the member list
After adding a member to the list then goes back to the search screen, the user can search and select the added member to add to the list again
=> It should show a blue tick for an already added member in the search result. 

https://user-images.githubusercontent.com/69950655/124746598-42220880-df4b-11eb-9543-3266f9252b3c.mp4

4. Sometimes when inputting a keyword, the search function returns nothing. 
After some tries, it will return the matched result. 
=> Please investigate the reason 
https://user-images.githubusercontent.com/69950655/124745719-4e599600-df4a-11eb-8744-9e7dea06937f.mp4

# Environment

- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by manhduc-nguyen** [comment]
@tlle14 Hi,
1. This UX is from our designer, basically its very much like when u create a group in signal and I think its actually a nice one 🤪 
2. Thanks, I will fix it
3 + 4. The reason is we have to load all the members from api to do a search (so delay thing happens) but @bobs4462 changed it to be loaded locally, so I think it should be ok in next build.

**Comment by tlle14** [comment]
Hi @manhduc-nguyen your hand doesn't fond of this way when you are going to add multiple users to the channel.
For example, you are going to add all emails that have the @linagora.com domain to a new channel. 
Let's consider this is an improvement, not an issue nhé!

**Comment by tlle14** [comment]
Retest pass!
https://images.zenhubusercontent.com/309637937/c3d448f7-a1aa-4f2c-bea6-8cd1f0517e45/videob0891db5_48d3_4414_9274_1641f145736avideo.mp4
