### ISSUE TITLE
Create workspace > After creating a workspace, it redirects to the black screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#745]
# Actual Result
After click on the create workspace button, it creates a new workspace and redirects to the black screen
https://images.zenhubusercontent.com/309637937/10df7e38-8ec2-4f81-9269-7aabf44e670b/rpreplay_final1626260449.mp4

# Expected Result
It should open the new worskpace

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by tlle14** [comment]
Hi @EvGen94 
**Actual Result:**
After being created, it doesn't show the black screen, but the channel list of the previous workspace. 

**Expected Result:**
After created:
1. it should show the corresponding channel list of the new workspace
2. the new workspace should be selected on the sidebar

https://images.zenhubusercontent.com/309637937/12cbb98d-97ef-442e-8e79-57a5367b45a7/video0ab19367_af11_4db9_b823_441826c69a31video__1_.mp4

**Comment by bobs4462** [comment]
@RomaricMourgues remember the bug with creator not being added to workspace, is it going to be fixed soon?

**Comment by RomaricMourgues** [comment]
Yes, and it should have been fixed already, the signup button is not working on my production ios app :/

**Comment by bobs4462** [comment]
1. Create workspace 
```
curl -X POST https://web.qa.twake.app/internal/services/workspaces/v1/companies/ab441952-8d3e-11eb-9f13-0242ac120005/workspaces \
    -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzE2MTQ3MjEsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2MzE2MTA1MjEsIm5iZiI6MTYzMTYxMDUyMSwic3ViIjoiNTMwMjg4MTgtMzIyNy0xMWViLThmOGItMDI0MmFjMTIwMDA0IiwiZW1haWwiOiJib2JzNDQ2MkBnbWFpbC5jb20iLCJ0cmFjayI6ZmFsc2V9.hmqJ3lT1SvaE4MkrKjeEm_iFbCze6M77jserebgt_To' \
    -H 'Content-Type: application/json' \
    -d '{
    "resource": {
        "name": "test #1",
        "logo": "",
        "default": false
    }
}'
```
2. Check whether it was created
```
curl https://web.qa.twake.app/internal/services/workspaces/v1/companies/ab441952-8d3e-11eb-9f13-0242ac120005/workspaces \
    -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzE2MTQ3MjEsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2MzE2MTA1MjEsIm5iZiI6MTYzMTYxMDUyMSwic3ViIjoiNTMwMjg4MTgtMzIyNy0xMWViLThmOGItMDI0MmFjMTIwMDA0IiwiZW1haWwiOiJib2JzNDQ2MkBnbWFpbC5jb20iLCJ0cmFjayI6ZmFsc2V9.hmqJ3lT1SvaE4MkrKjeEm_iFbCze6M77jserebgt_To'
```
3. No, it wasn't created

As for the signup button, it's disabled on purpose, to prevent further bug reports, after we will make sure that it works, it will become accessible

**Comment by bobs4462** [comment]
@RomaricMourgues can you confirm this? Or is the problem on our side?

**Comment by RomaricMourgues** [comment]
We found the issue, it will be merged on QA soon

**Comment by tlle14** [comment]
Thanks, Retest pass!
After creating a workspace, it displays a channel list o  the new workspace
https://images.zenhubusercontent.com/309637937/bf4da258-ff5d-4a5c-82aa-aec128822f29/video82c73cfb_46b5_49b6_8ff7_fe08b871a133video__1_.mp4
