### ISSUE TITLE
Message delivery status 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#752]
# Precondition
Message delivery status is partially implemented 

# Actual Result
The message status appears in all messages of the current user, and it looks quite big. That makes:
- The chat screen looks untidy with too many elements
- The status take up space
- The user may think all messages are sent but never delivered to the participant (because the status will never change as other apps)

![image](https://user-images.githubusercontent.com/69950655/125890014-eb70045e-7ab1-4847-919c-a48948ee0592.png)

# Expected Result
**- If the current status is kept, it should:**
+ The status should be less emphasized (change the color and size)
+ The status shouldn't show for all messages

**- If the current status is not kept,** you should refer to the way Instagram implies the sending message by a little gray dot on the right border, then it will disappear after the message is sent successfully

https://user-images.githubusercontent.com/69950655/125887076-cfec624f-1cf6-4b18-8da8-a0c161c686ae.mp4

# Environment

- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by BastiaanVanGaalen** [comment]
@tlle14 The funny things is, that nobody asked me about the design of this feature before implementation))
This one you need: https://zpl.io/bAKv1qo
There are 3 message statuses:
- sent but not delivered (stuck in delivery tube)
- delivered but not read
- read

There are 3 different icons for each case. 

Can we implement this? @EvGen94  Please, mind colours of each icon.

**Comment by bobs4462** [comment]
hi @BastiaanVanGaalen, I've already mentioned, that the only piece of information we can provide the user with is delivery status, i.e. whether the message has reached the backend (not the other users) or not. Alas that's the only thing that is supported for now.

**Comment by tlle14** [comment]
Could you please give the advice for this partial implementation, please?

**Comment by BastiaanVanGaalen** [comment]
@tlle14 In that case can only have two statuses as @bobs4462 mentioned. The first one "clock icon" that indicates the message hasn't still be delivered to backend and the send one "blue tick in a circle" when backend receives it.

**Comment by tlle14** [comment]
How about sending fails? @BastiaanVanGaalen

**Comment by BastiaanVanGaalen** [comment]
@tlle14 We should not show our users our "failed condition", message will eventually be delivered either when server is up or internet connection is re-established.

**Comment by bobs4462** [comment]
Well actually if there's no internet connection or backend issues, then the sending will fail once. And currently there's no mechanism to "try until successful" implemented in mobile app. So I'm afraid we have to tell the user about sending failure

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Ok, i got you, i will add sending failed.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Here you go: https://zpl.io/VQyORAk

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass!
