### ISSUE TITLE
Message > Mention and link have the text color quite similar to the background

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#753]
# Precondition
The current user's messages

# Actual Result
Mention and link have the text color similar to the background color. It makes the user hard to read the text

# Expected Result
The color of mention and link should be changed to be more contrasting

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
We should ask @BastiaanVanGaalen

**Comment by BastiaanVanGaalen** [comment]
The funny thing is that of course it should be 100% contrast with message bubble, so, we have to stick to the following rules:
1) If message bubble color is light-grey(ur usual color) then mention part such as **@username** should be displayed in blue (our main color)
2) in case message bubble is blue, so in that case mention part such as **@username** should be displayed in white.

And it should be exactly like that.

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen 
It's easy to recognize a mention which starts with @ 
How about the link? should it be white and underline to differentiate from a normal text?

**Comment by EvGen94** [comment]
@tlle14 After discussion with @BastiaanVanGaalen the following decision on the color was made.
1. Mention color is equal to the unique color of the user in the chat which was mentioned
2. The color of the link in case of blue bubble is white with underline, in case of grey bubble is blue with underline.
3. If there is an email in text in case of blue bubble the color is white with underline, in case of grey bubble the color is blue with underline.

**Comment by tlle14** [comment]
Hi @EvGen94 @BastiaanVanGaalen 

1. **The links** are okay on both 2 background colors.

2. **The mentions:**
+ On Gray background: Gray suits with most colors. So it's okay too.
+ On Blue background: Sometimes it's hard to see mention text with color on blue background. 

3. **The emails**: Email is displaying the same with link as on Twake Web. 
But when tapping on the email, should it open the available email app? 

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/b881b76e-3a0a-49af-89a0-7dd9e1d68a72)

**Comment by tlle14** [comment]
Thank @bobs4462 
The color problem is solved. But we have a little more problem with emails displaying. I will create a new ticket for easier tracking. 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/421da769-49ac-4f28-959c-dbedd0959b89)
