### ISSUE TITLE
Message > Mention text should display Name instead of username

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#755]
# Actual Result
When mentioning someone on Mobile, it always displays username instead of the displaying name as on Web version

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/125915527-e8ff9ad5-d1ae-4f8c-a58e-ea3e629d4de1.png)

On Web:
![image](https://user-images.githubusercontent.com/69950655/125915423-8c96b779-e37a-4d36-9dae-ca1a5697e142.png)

# Expected Result
Please consider displaying Name instead of username

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment
-

**Comment by bobs4462** [comment]
Done, but there's a catch, the message itself doesn't contain any information regarding the full names of users, only their ids and usernames, so we have to request those from local database (which is pretty fast), but you might see some weird glitches when scrolling. Will be available for test in the next build

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass! I don't see a scrolling issue. How is it? 
Anyway, is it possible if displaying the name in the textbox while composing a message?
https://images.zenhubusercontent.com/309637937/a62dbac3-6a0b-4abc-af51-33c7f8a0c801/rpreplay_final1630493790.mp4

**Comment by EvGen94** [comment]
hello ! @tlle14 
Now this feature cannot be implemented, perhaps later this year

**Comment by tlle14** [comment]
Thank @EvGen94
