### ISSUE TITLE
Edit Channel > Some buttons doesn't work

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#759]
# Precondition
1. Open the channel 
2. Tap on the Channel name

# Actual Result
On the channel editing screen, some buttons (Add members, Messages, Search, Mute, three dots on the top-right) don't work
![image](https://user-images.githubusercontent.com/69950655/126100400-2891a09f-e315-4e47-a275-bfd0112eed45.png)

# Expected Result
When tapping on the button, it should open the corresponding screen

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 
The buttons are hidden. Is it the newest updated design or just a temporary solution?
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/14c088d4-bd03-4f77-9ba0-e5037f6ae59a)

**Comment by bobs4462** [comment]
It's temporary, we will return them, once the functionality for them is ready

**Comment by tlle14** [comment]
Thank @bobs4462 Don't forget to take it back ;)
