### ISSUE TITLE
Create Channel > Empty channel always display loading message screen 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#762]
# Precondition
The new channel is already created
There is no message in the channel

# Actual Result
When opening the new channel, it displays a loading message screen for a while, which is illogical cause the channel doesn't have any messages to load
https://user-images.githubusercontent.com/69950655/126125140-e675d0ab-344e-4113-be6f-036acdd9a22d.mp4

# Expected Result
It should display the empty channel screen right after opened

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
Hmm, that's a tricky one, once the channel has been created, we still have to check backend for potential messages, hence the loader. But ok, i'll try to think of solution.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/4b868229-919b-4aef-b574-76b507e6135c/video7a590280_85fb_4705_9625_596f08703927video.mp4
