### ISSUE TITLE
Loading message screen doesn't follow the design

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#763]
# Actual Result
![image](https://user-images.githubusercontent.com/69950655/126127220-a4efea4c-8181-49af-bb2c-39e6c4265c5e.png)

# Expected Result
Should follow the design
![image](https://user-images.githubusercontent.com/69950655/126127268-65e2b506-4618-449d-89d2-653b0bed7f3f.png)

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Thank you dear, for noticing <3, icon has recently been updated. So, it's correct) Keep in touch.

**Comment by tlle14** [comment]
This is not an issue
