### ISSUE TITLE
Edit channel > Cannot update channel type from Public to Private successfully

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#765]
# Precondition
Channel type is Public

# Actual Result
Cannot update channel type from Public to Private successfully
https://user-images.githubusercontent.com/69950655/126138161-3a3b0be2-6727-4707-82b1-6a7db4577541.mp4

# Expected Result
The channel type should be updated successfully

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
https://www.notion.so/twake/REST-Api-Websockets-Api-458b153a6a6e46c2925dfc1db3859d3b
@RomaricMourgues We are trying to use the endpoints described in this documentation, but changing the channel visibility doesn't work, the request executes normally but it has no effect

**Comment by bobs4462** [comment]
@RomaricMourgues ping :)

**Comment by RomaricMourgues** [comment]
Could you give me more details about how you try to use this feature ?
Only "creator of the channel" and "workspace admin" can edit this part of the channel.

**Comment by RomaricMourgues** [comment]
Seems to be also a bug in web

**Comment by bobs4462** [comment]
We call this endpoint 
``` 
POST /internal/services/channels/v1/companies/%s/workspaces/%s/channels/<channel_id>
```
with channel object in `resource` field of the body of request, with `visibility` changed, and change doesn't apply.
Yes it doesn't work on web either

**Comment by tlle14** [comment]
Thanks,
Retest pass!
https://images.zenhubusercontent.com/309637937/e3d4b535-d8e1-4ce5-a52d-7fd682394404/rpreplay_final1631085617.mp4
