### ISSUE TITLE
Links rendering is broken for some link formats

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#766]
Links aren't rendered as highlighted and don't support click based navigation to browser.

WEB:

![image.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/77174ac4-540c-43e0-93bf-bde79c53ec39)

MOBILE:
![Screenshot_1626693598.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/393dd353-4bd3-40f3-af1f-43ec468394a2)

**Comment by tlle14** [comment]
Thanks! 
Retest pass! 
![screenshot_22.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/c20655e0-4200-4b34-bebc-9124d4c147b4)
