### ISSUE TITLE
Notification > Expose user ID of mentioned user in the push notification

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#770]
# Actual Result 
In the push notification, user ID of the mentioned user exposes
![image](https://user-images.githubusercontent.com/69950655/126260357-c6116196-f88c-46d5-a456-7234117f593a.png)

# Expected Result
It shouldn't expose userID in the push notification

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by bobs4462** [comment]
@RomaricMourgues can we remove it via some regex?

**Comment by RomaricMourgues** [comment]
Héhé we have it too :p https://github.com/linagora/Twake/issues/1405

Yes it is a simple regex to set-up. We will fix this soon.

**Comment by tlle14** [comment]
This issue has been fixed
