### ISSUE TITLE
Notification > Tapping on the push notification will redirect to a black loading screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#774]
# Actual Result
Tapping on the push notification when it arrived will open a black loading screen (always be able to reproduce on iOS)
https://user-images.githubusercontent.com/69950655/126295073-247871b0-c522-4803-846e-fd5190cc0f4e.mp4

# Expected Result
It should be able to open the message successfully

# Environment

- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 
Now the black screen becomes gray one 
https://images.zenhubusercontent.com/309637937/839b0222-6067-4513-9aa4-f3a0ac9ad625/rpreplay_final1631093688.mp4

**Comment by bobs4462** [comment]
What are the steps to reproduce it?

**Comment by tlle14** [comment]
# Precondition
The app is in the background running

# Steps
1. UserA mentions UserB in a channel
2. UserB see the push notification 
3. UserB taps on the push notification immediately
4. Verify issue: It opens the app with gray screen

@bobs4462

**Comment by tlle14** [comment]
Hi @bobs4462 I update the issue, it happens on iOS when the app is in background running

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/9c5e7348-95e9-4007-9ab8-b66092857bc8/rpreplay_final1632279827.mp4
