### ISSUE TITLE
Channel > Channel list  doesn't get the newest update

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#777]
# Precondition
The app is running in the background or in the foreground

# Actual Result
- In the background, after a long time unused, when reopening the app, the channel list is not updated. User needs to pull to refresh the app to see the newest state
https://user-images.githubusercontent.com/69950655/126423451-16cf5e19-6a04-447b-9536-e586849afe6b.mp4

- In the foreground, when having a new message, the channel doesn't jump to the top.
https://user-images.githubusercontent.com/69950655/126447333-4969094e-9d65-46a6-baa2-b4c89770ea55.mp4

# Expected Result
The app should regularly get the newest update 

# Environment
- Build version: 3.0.3
- Device:
iPhone 12 - iOS 14.6 - 6.1 inch
- Production

**Comment by tlle14** [comment]
duplicated

**Comment by bobs4462** [comment]
If the real time update is working (like when you get a message in real time) then the channel sorting also should work. But if it doesn't (for some reason, like bad connection or backend issues), then channel resorting will not work too. 
As for getting the latest update after coming from background, if the user has active internet connection during that moment, then it should work. Can you recheck it?

**Comment by tlle14** [comment]
I've retested but don't see it changed. Is it still working on your real device?

**Comment by tlle14** [comment]
Should be retest on Production

**Comment by tlle14** [comment]
Retest pass with a background running.
But foreground running, it doesn't update.

**Comment by bobs4462** [comment]
Do you mean channels list is not updating? Or directs list?

**Comment by tlle14** [comment]
> Do you mean channels list is not updating? Or directs list?

It's channel list

**Comment by bobs4462** [comment]
Hmmm, that's strange, do you always have the same behavior between app restarts?

**Comment by bobs4462** [comment]
I couldn't reproduce the issue, it updates the list of channel both when coming from background and when running in foreground (given you have stable connection).

**Comment by tlle14** [comment]
I guess it's a connection problem. Retest pass on both background and foreground.
