### ISSUE TITLE
Unread counter doesn't display on Chats tab name

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#780]
# Actual Result
The total unread counter doesn't display on the Chats tab name

# Expected Result
The total unread counter should display for the chat tab name

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@EvGen94 i've added unreadInDirects getter for badges cubit, so you can directly access that data to display the counter.

**Comment by tlle14** [comment]
Retest pass! Thank @EvGen94 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f5750ab3-2e75-468e-b9dc-659b746bede7)
