### ISSUE TITLE
Thread > Timestamp is hidden when username is long

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#782]
# Actual Result
User has a long username makes the timestamp be hidden when displaying in a thread
![image_2021_07_21T11_11_58_375Z](https://user-images.githubusercontent.com/69950655/126479806-5dad5909-b00e-4230-9394-8e233133496a.png)

# Expected Result
The username should display in a smaller size

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi, I know you have a plan to update the thread screen, but I think this kind of thread screen is convenient.

**Comment by bobs4462** [comment]
Threads are being completely redesigned, so I think there's no point to keep this issue around
