### ISSUE TITLE
Update logo for mobile app

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#787]
@BastiaanVanGaalen has redesigned the main logo of twake, so there's a need to update logo of mobile application as well.
The logo is in the attachment to this issue. 

[https://app.zenhub.com/files/309637937/e37abe4a-45a1-4bc3-b042-10e4efaaf1df/download](https://app.zenhub.com/files/309637937/e37abe4a-45a1-4bc3-b042-10e4efaaf1df/download)

**Comment by tlle14** [comment]
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f1fc6d05-092c-47ec-8b64-9d8f56966c0f)
