### ISSUE TITLE
Channel > The earliest message is duplicated each time scrolling down

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#790]
# Actual Result
When scrolling down to see chat history, the earliest message is duplicated 
https://images.zenhubusercontent.com/309637937/bd452143-8072-4d47-a5d8-77168cb7cc5c/video3a22637b_931b_4196_859d_d71ca41d1970video.mp4

# Expected Result
The earliest message shouldn't be duplicated 

# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- Prod

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed 
Even the first message is no longer duplicated, when scrolling down, the loading message screen flickers.
https://images.zenhubusercontent.com/309637937/a59e8a10-41d2-437c-9622-14207c0a6f29/videoea3037b1_7638_44cc_9ccf_ddbeea76788evideo__1_.mp4

**Comment by bobs4462** [comment]
@EvGen94 Remember I've asked you to fix this?

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass!
https://images.zenhubusercontent.com/309637937/2f0846b0-7576-45a2-8fd0-c1f45f6c3a31/video9288f1ca_8a3d_4d52_86fe_85ccc7f5e7aavideo.mp4
