### ISSUE TITLE
Unable to sync the new added user on Mobile App

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#796]
# Precondition
Added some new users to the workspace on Web 
![screenshot_49](https://user-images.githubusercontent.com/69950655/127504708-07aa4bff-2050-4167-924d-9855c6c59234.png)

# Actual Result
1. On the mobile app, it doesn't update the new users in the workspace. 
The new users cannot be mentioned in the channel
https://user-images.githubusercontent.com/69950655/127502789-eba4b1fd-e96e-4abe-90b6-ec573fe05070.mp4

2. After re-login, it always fails to sync new data
![screenshot_52](https://user-images.githubusercontent.com/69950655/127507158-9b226e7d-edca-4ec8-a2a7-fa011a91b02c.png)

# Expected Result
When new users are added to the workspace, the Mobile App should get the update. 
It should be able to mention the newly added users
# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
I've added users sync to pull to refresh feature, when the app starts and when you switch the workspace. Alas there's no way we can track users in workspace in a real time.

**Comment by tlle14** [comment]
Hi @bobs4462 
I've retested and didn't see it work. Could you please try?

https://user-images.githubusercontent.com/69950655/128681714-2a785344-bffb-4b05-bfbc-685abba782b0.mp4

**Comment by bobs4462** [comment]
Well, it's not released yet :)

**Comment by tlle14** [comment]
Retest pass! Thank @bobs4462
