### ISSUE TITLE
Thread messages screen redesign 

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#803]
We need to update the design for the screen that displays replies in a thread. 

Here the new design that needs to be implemented 
https://zpl.io/aRwdoZp

**Comment by tlle14** [comment]
The new thread screen is displaying well in the App. 
But the reply counter should have a fixed position before and after having reactions
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/63f14c41-37c6-4bde-97fe-6c902b9d3fbe)

**Comment by BastiaanVanGaalen** [comment]
1. Agreed
2. For me it's not that obvious, it's clear differentiation between main message and "reply-type" messages.

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen for your confirmation.
1. The reply counter will be placed on the right.
2. Will add the reply icon. 
@EvGen94 could you please help to work on this issue? Many thanks!

**Comment by EvGen94** [comment]
@tlle14 @BastiaanVanGaalen  So, the reply counter should be placed on the right in both cases, and add the reply icon. Well, I'll do it, but I don't quite agree with putting the reply icon, since we already see that this is the threads screen, it seems to me redundant, I agree here with @tlle14, but as you want ;)

**Comment by BastiaanVanGaalen** [comment]
Guys, your opinion is important to me! If both of you feel some sort of inconsistency here, let's jettison "reply icon". It won't affect anything anyway.
@EvGen94 @tlle14

**Comment by tlle14** [comment]
Thank you @BastiaanVanGaalen ;)

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass! 
![screenshot_12.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/3a4b836c-f02f-4bea-883e-49b4c825357d)
