### ISSUE TITLE
Member management > UI issues

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#808]
![screenshot_69](https://user-images.githubusercontent.com/69950655/127958262-ec52b1ed-9e3f-445b-8dbf-283b2c3c1986.png)

1. The font size
I have no way to check the font size, so please check your code if it follows the design

2. The button name "Add a member" should be "Add a new member"

3. The adding member button has a different style from the design. 
Please ask the Designer for the correct icon

4. Confirm with BA and Designer if we should display the user's role.
On Twake Web, it only displays the label `Guest` and `It's you` 

5. Confirm with BA and Designer what is the adjustment button used for?

**Comment by BastiaanVanGaalen** [comment]
1.I left some remarks related to font size inconsistencies, we have to ensure text is scaled correctly depending on the screen width. Increase the font-size when screen size is bigger - is the key to text readability and general look and feel. So scale factor must be applied.

2. Agreed, confirmed.

3. Attached[https://app.zenhub.com/files/309637937/d6f85c02-9b15-48f5-b12d-26abc224bea1/download](https://app.zenhub.com/files/309637937/d6f85c02-9b15-48f5-b12d-26abc224bea1/download)

4. The one created the channel is OWNER, owners can assign admins. This was a request from Alex to have such functionality where owners can transfer rights to another members when they leave the company. Admins are promoted members with special rights.

5. Admin permissions (this functionality is only available for channel owner): https://zpl.io/amROOev

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen for your confirmation. 
It seems the Team has not implemented 4 and 5 yet.

**Comment by bobs4462** [comment]
4. Not possible to implement as on backend there's no such thing as channel admin, only owner | member | guest.
5. Not possible to manage permissions, as there's no such thing as permissions on backend

It has to be implemented on backend first

**Comment by BastiaanVanGaalen** [comment]
Since we have no backend logic to support this part of UI, this task can be adjourned.
