### ISSUE TITLE
Send message button is faded

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#812]
# Actual Result
The send button is faded, it looks like not being enabled
![screenshot_73](https://user-images.githubusercontent.com/69950655/128124269-ca57d512-1ee0-4659-9b24-e34e10ab69fc.png)

# Expected Result
It should be no opacity

# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@BastiaanVanGaalen can you please give us a color code for active send button?

**Comment by tlle14** [comment]
Retest pass! Thank @bobs4462 
But could you please expand the tap area?

**Comment by bobs4462** [comment]
@EvGen94 can you do it?

**Comment by EvGen94** [comment]
@bobs4462 @tlle14 
Okay, I'll do it

**Comment by tlle14** [comment]
Thank @EvGen94 
Retest pass!
It's easier to hit the send button
