### ISSUE TITLE
Swipe to reply > The reply doesn't display after submitted

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#815]
# Precondition
Story: https://github.com/linagora/Twake-Mobile/issues/696

# Actual Result
On Android, when swiping left to reply then submit the message:
- The view reply button doesn't appear instantly
- (UX) User cannot see his/her replies right after it is submitted

https://user-images.githubusercontent.com/69950655/128173823-7f9fbee1-26ee-4453-afcd-768ec009feb0.mp4

# Expected Result
After swiping to reply:
- The reply counter should be updated
- The view reply button should display instantly on the parent message OR the reply should display for the user to know what he has already written. (Let's ask @BastiaanVanGaalen for his suggestion)

# Environment

- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 What is the solution for this ticket? I don't see it changed.

**Comment by bobs4462** [comment]
> The reply counter should be updated
The view reply button should display instantly on the parent message

Hi, if you have active internet connection, then reply counter should be updated, view replies button should appear in a few seconds. 
![untitled](https://user-images.githubusercontent.com/31780624/130024824-d9100e84-7966-44a2-9ff8-f560d6aaf4ce.gif)
Can you make sure that real time message syncing works at the moment when you are testing it?

**Comment by tlle14** [comment]
The first point relates to https://github.com/linagora/Twake-Mobile/issues/777
How about the second point: The user cannot see his/her replies right after it is submitted? I meant it should open the thread screen after the user submitted his reply, so he can see (re-check) his message. But I'm not sure about this behavior, we should ask @BastiaanVanGaalen for a better UX

**Comment by bobs4462** [comment]
Ok, so realtime sync stops working after resuming from background. Will fix it. 
As for opening the thread screen after swipe to reply, @BastiaanVanGaalen what's your opinion?

**Comment by BastiaanVanGaalen** [comment]
@tlle14  I can review the message before sending it, why would i need to review it inside the thread screen? To ensure it has been posted correctly?

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen 
1. The user may want to see how the message displaying in the app. For example, if he uses twacode, he needs to see how it displaying
2. By mistake, the user might reply in the wrong thread. How does he aware of which thread he posted a message to?

**Comment by BastiaanVanGaalen** [comment]
@DianaPotokina I need your help, please decide whether or not we have to redirect user to a threaded replies screen after replying to a thread message.
