### ISSUE TITLE
Syncing failed happens randomly and frequently

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#816]
# Actual Result
I've encountered syncing failed frequently when login, but I don't know why 

# Expected Result
Please confirm on your side and help investigate.
Maybe you should generate logs in the next build 

# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by tlle14** [comment]
This issue seems no longer happen

**Comment by tlle14** [comment]
Hello @bobs4462 
It seems the problem happens with @RomaricMourgues on the Production server. Could you please take a look?

**Comment by RomaricMourgues** [comment]
I can provide you with my prod credentials if needed

**Comment by bobs4462** [comment]
@RomaricMourgues it seems there's some incorrect data present within your account, which application fails to parse, which is why syncing might be interrupted, so I might need your credentials, if you can provide them, as it's not reproducible with other accounts

**Comment by tlle14** [comment]
Hi @bobs4462 I can reproduce the case.
# Precondition
- UserB registers Twake and creates a new company (CompanyB)
- In the existing company (CompanyA), UserA:
+ Invites UserB to a channel in a workspace of CompanyA

# Actual Result
When UserB login to the App, he got the syncing failed screen. After restart app, it is displaying a gray screen
I wonder is it because of being invited to the second company?
@bobs4462 can you confirm this case? Is it relates to an error in parsing data? Or it is a new issue about inviting a new user to the second company?

**Comment by bobs4462** [comment]
Hello, I can check your case if you give me the credentials, but most likely it's related to what Romaric's account has been experiencing, i.e. absent user role in company, which is assumed by application to be always present, so it's a backend bug

**Comment by tlle14** [comment]
Retest pass! Thank @bobs4462
