### ISSUE TITLE
Member Management > Incorrect label in "add members" screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#818]
# Actual Result
Displaying the label `FREQUENTLY CONTACTED` label while the suggestion feature doesn't appear in the screen
![screenshot_80](https://user-images.githubusercontent.com/69950655/128337121-87a0f2ae-3353-4535-b9fe-b55ac8ac7dd1.png)

Design: https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/60e70a496df65c77eaf8c679
![screenshot_2](https://user-images.githubusercontent.com/69950655/128683983-15b461ec-c436-4517-ba74-02f442b2df08.png)

# Expected Result
The label should be removed

# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
@BastiaanVanGaalen hi, could you please confirm which one we should apply in these two design?

https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/60a67481a3c38326eff4e665

or 

https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/60e70a4cff59ed6f4d5e049b

They have different labels `Frequently contact/ found people` and the way selected contact appears in the list.

**Comment by BastiaanVanGaalen** [comment]
@tlle14 If we are talking about Channel management which is not channel creation flow, these two screens are different.
These is section in Zeplin called "Channel editing" you have to lean on it when comparing between design and implementation.
Particularly, we use "found people": https://zpl.io/aMwzXoK

This is the link to the section in Zeplin:  https://zpl.io/VY5Ny0p

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen @EvGen94 
I apologize for my mistake. I've updated the description.

@BastiaanVanGaalen In the edit channel > add members, we don't have the feature Frequently contact, so  I ask the Developer to remove the label to follow the design. 
About Add Members screen when Create Channel and Edit Channel, I suppose they should be the same. Otherwise, it's alright.

**Comment by tlle14** [comment]
Retest pass! Thank @EvGen94 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/55a08653-eda4-49ae-965f-b76f9b0d8d74)
