### ISSUE TITLE
Member management > It doesn't display the member list in default channel of the newly created workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#819]
# Precondition
Create a new workspace 

# Actual Result
After the workspace is created, open the member list of the default channel, it doesn't display anyone on the list
https://user-images.githubusercontent.com/69950655/128449523-c211860c-b2db-4183-8198-b9223d5535b1.mp4

# Expected Result
It should display the list of added members in the workspace for the default channel's member list

# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by tlle14** [comment]
Blocked by https://github.com/linagora/Twake-Mobile/issues/837

**Comment by tlle14** [comment]
Still blocked testing

**Comment by tlle14** [comment]
Do you think this issue is from backend team? When creating a new workspace,the invited members (who are invited while creating the workspace) are not added to the General channel. 
https://images.zenhubusercontent.com/309637937/4f4dcff7-1fde-44fe-b2d1-51e9fc4cdf93/video6fa79a0d_142b_45b8_966d_824c7e43ffbbvideo.mp4

**Comment by tlle14** [comment]
This issue may relate to https://github.com/linagora/Twake-Mobile/issues/1005
It cannot add members while creating a workspace

**Comment by tlle14** [comment]
Thank @hoangdat 
Now I can add members while creating a workspace. But it seems able to add maximum 3 emails to the workspace. Could you please check? 


https://user-images.githubusercontent.com/69950655/143408064-6c0d91e9-afcc-414b-a28f-b3115fb16fd5.mp4

**Comment by huynguyennovem** [comment]
Related to #851. And this is already fixed by #1212

https://user-images.githubusercontent.com/29337364/155104681-f42c0790-d1a0-418f-b52b-eb5871f8455c.mp4

**Comment by hantt12** [comment]
Default channel is not created
https://github.com/linagora/Twake-Mobile/issues/1368
