### ISSUE TITLE
Create workspace > Able to add multiple member in a row 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#820]
# Actual Result
When creating a workspace, copy the list of users then paste it into a row, it is able to add all users into a new workspace
https://user-images.githubusercontent.com/69950655/128455749-0bb5ceb4-7a45-4fe0-ab2c-5c9918f50cef.mp4

This is also a good idea to add a group of users into a workspace/channel easily. We should make it becomes an official feature.
But it is able to over the limit when the user has not been verified
![screenshot_82](https://user-images.githubusercontent.com/69950655/128456483-9c467a3a-ffad-4873-b436-3e4ebf6538de.png)

# Expected Result
Please discuss with BA/PO and Designer about "this feature"

**New update:**
The app should not allow adding multiple emails in a column, which may lead to add user over the limitation.

# Environment

- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@BastiaanVanGaalen Please comment on this

**Comment by BastiaanVanGaalen** [comment]
On mobile, we have different UI architecture rather than on web, to keep things structured we use cells. I will consider supporting this group adding feature though, in future.

**Comment by bobs4462** [comment]
Please close this issue, if it's not going to be solved anytime soon

**Comment by tlle14** [comment]
>I will consider supporting this group adding feature though, in future.
This means we will have another way to add a bulk of users. 

The app should avoid performing this kind of trick adding users over the limitation. I

**Comment by tlle14** [comment]
@bobs4462 @EvGen94 I think this issue should be fixed for the release

**Comment by EvGen94** [comment]
@tlle14 @BastiaanVanGaalen  Now it is impossible to add a list of users in one field, if we need to make such thing we need a design and a new issue, I think

**Comment by tlle14** [comment]
Thank @EvGen94 
It is unable to add a list of users in one field. anymore.
I should close this issue
