### ISSUE TITLE
Member management > There is no way to remove user from the channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#823]
#  Actual Result
We can only add users to the channel, but there is no way to remove a user

# Expected Result
It should be able to remove a user from the channel

# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@BastiaanVanGaalen is there a design for this?

**Comment by BastiaanVanGaalen** [comment]
https://zpl.io/2vjzDEj

Yes we can remove members from channel

**Comment by bobs4462** [comment]
@BastiaanVanGaalen can you please update the design, removing the admin feature, because it's not supported on backend

**Comment by tlle14** [comment]
Hi @EvGen94 @bobs4462 
I don't see it works
https://images.zenhubusercontent.com/309637937/88a28eb2-7320-4a61-8adf-4e178b88729e/video0ca62e84_2d13_49ae_8435_038861ee8577video.mp4

**Comment by EvGen94** [comment]
@tlle14 Hello!
Go to the member management, use a long press on the member, delete it, done

**Comment by tlle14** [comment]
I'm sorry @EvGen94 I didn't know the correct behavior. 
Yes, I can remove a member from the channel successfully. 
But we should have 2 little improvements

1. The Remove button tappable area should be expanded. 
2. After deleting a member, there should have a toast displaying "Member is removed"

https://user-images.githubusercontent.com/69950655/131650018-a806455f-051a-44a8-83d8-8bf48be243ad.mp4

**Comment by EvGen94** [comment]
@tlle14 Hi!
I Added a toast displaying "Member is removed" and increase tappable area of the Remove button.
We may also need to add a gear icon or something like that to get into the modal menu, since a long press is not quite intuitive for the user

**Comment by tlle14** [comment]
> @tlle14 Hi!
> I Added a toast displaying "Member is removed" and increase tappable area of the Remove button.
> We may also need to add a gear icon or something like that to get into the modal menu, since a long press is not quite intuitive for the user

Yes, I think we should. But better we ask @BastiaanVanGaalen , he knows how to deal with it.

**Comment by EvGen94** [comment]
Hi! @tlle14 
@BastiaanVanGaalen updated the design and added an arrow icon, you can check out in the next build

**Comment by tlle14** [comment]
Thank guys!

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen please verify if this design is okay for you
![screenshot_66.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/501e6fa9-6366-4250-97c5-51d99e9fe6fc)

Thank @EvGen94
