### ISSUE TITLE
[User story] Ability to register a new account from mobile application

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#826]
As a user I want to be able to create a new account (in case if I don't have one) from the mobile application itself.

I should be able to navigate to new account registration screen from the first screen of the app
![image.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/b8746892-971c-4fcd-84b4-cac00005f1c2)

Account registration takes place on twake console side (https://account-twakeconsole.dev.lin-saas.dev/apidoc/static/index.html#/user/post_api_signup). 
User should only enter his/her email and submit it, after which the new account should be created on twake console side and a verification email with password should be sent to the user. 
![image.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/db6f50be-91cc-4ff0-acc9-819b0f3b2727)
![image.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/873007f8-1e4b-4fe4-a334-491549b52db0)
 
After successful registration, and after getting his generated password, user should be able to go to sign form (via webview) and attempt to sign in, as there's no way to automatically sign in user after account creation. 
![Screenshot_1628670841.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/3eeb69d5-0240-4bef-99b6-e9f14c03dd3a)

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 
Sign up flow screens: https://zpl.io/amRQYmQ

Some comments:
- when user enters this screen "Email" inout gets focus and "Number of users" input has pre-filled value of 5 (users can enter any value except for 0)
-  "Start using Twake" button always visible and is placed above the keyboard (when it's shown up)
- user can close the sign up 
- user can follow "terms and conditions" links that must be shown as UIWebView

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Are we done with this task? What should i do about it? =)

**Comment by bobs4462** [comment]
Leave it out for now, we don't have server side implementation yet?

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 https://zpl.io/amRQYmQ
