### ISSUE TITLE
Direct > After created on Web, user need to refresh to see the chat appears

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#827]
# Precondition
UserA creates a direct chat with UserB on the Web

# Actual Result
On Mobile, UserB cannot see the chat appears. He needs to pull to refresh to see it.
https://user-images.githubusercontent.com/69950655/128676125-22d3640c-a7a7-44f8-add5-16530ee6aa2d.mp4

# Expected Result
The chat should appear in a real-time when having a first message

# Environment
- Build version: 3.0.4
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@RomaricMourgues is there a sockeio Room to listen for such an event to occur, currently, we can listen for public and private channels in a given workspace to be created/changed, but it doesn't seem to apply for direct chats...

**Comment by RomaricMourgues** [comment]
Like for non direct channels, you should have a websocket room given in the response when you get the direct chats list (with websockets=1 query string)
https://www.notion.so/twake/REST-Api-Websockets-Api-458b153a6a6e46c2925dfc1db3859d3b

**Comment by bobs4462** [comment]
```/companies/ab441952-8d3e-11eb-9f13-0242ac120005/workspaces/direct/channels?type=direct&user=53028818-3227-11eb-8f8b-0242ac120004```
So I'm subscribing to the following room on web.qa server. 
And getting an event that I've successfully joined the room, and after that there's silence, no matter how many times I write to direct channels, or how many direct chats I create, still I'm not getting any resources from socket channel for directs. Public and private channel updates work fine though

**Comment by RomaricMourgues** [comment]
Ok that's a bug then, thanks for seeing this. On web I think we rely on an additional route "channel-members" or something that may have caused this issue to not be visible until now

**Comment by RomaricMourgues** [comment]
In the meanwhile why not just reloading all the channels with a HTTP get request ?
If you are subscribed to badges websockets you should have enough information no ?

**Comment by bobs4462** [comment]
Well, that's a hack, and will require to make some serious adjustments to the state management of the app, because the badges are handled separately. How long do you think it will take to fix this bug?

**Comment by RomaricMourgues** [comment]
I looked at this more carefully and here is how it work:
"/companies/ab441952-8d3e-11eb-9f13-0242ac120005/workspaces/direct/channels?type=direct&user=53028818-3227-11eb-8f8b-0242ac120004"
Can receive 3 events types:
- channel: when the channel is created / updated / removed etc
- channel_member: when a member is added or removed from a direct channel
- channel_activity: when a new message is sent into a channel (to update the "last_message" field)
Note that for direct chats when removing it we just remove the channel_member not the channel itself (by the way the button is called "hide channel").

Could it be that you need to implement all that ?
Mainly in the case a direct channel already existed but was hidden then you tried to re-open it but don't listen to the "channel_member" event ?

**Comment by bobs4462** [comment]
So, i've tested it on QA, I've successfully joined `/companies/ab441952-8d3e-11eb-9f13-0242ac120005/workspaces/direct/channels?type=direct&user=53028818-3227-11eb-8f8b-0242ac120004` (got confirmation event), then no matter what I do: write to direct channel, someone writes me in direct channel, I leave channel, I don't get any event on sockeio (non at all). For public and private channels it works though

**Comment by RomaricMourgues** [comment]
From QA this is what I got when sending a message on direct channel for info. I can't find what we are missing yet...

![Screenshot 2021-09-03 at 17 47 42](https://user-images.githubusercontent.com/14353924/132032904-b3ebe20b-faf2-4e41-b589-fc9131267383.png)

**Comment by tlle14** [comment]
Thanks,
Retest pass!
https://images.zenhubusercontent.com/309637937/61092b73-d1a6-4f4a-9f54-ba5686a4112d/20211001_121147.mp4
