### ISSUE TITLE
Direct > A new direct chat doesn't display for the receiver

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#834]
# Precondition
UserA creates a new direct chat with UserB
UserA send some first message to the direct chat with UserB

# Actual Result
The new direct chat doesn't display on UserB side 

# Expected Result
The direct chat should display on UserB's side in real time

# Environment
Build version: 3.0.5
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by tlle14** [comment]
Thanks,
Retest pass!
https://images.zenhubusercontent.com/309637937/be2509ea-ddf4-4138-817f-df0590acb5ae/20211001_135335.mp4

**Comment by tlle14** [comment]
Hi @EvGen94 
The issue happens when creating a direct from iOS App to Android App.
The new direct chat doesn't appear on Android.

https://user-images.githubusercontent.com/69950655/136139155-191a7292-a6e7-44c3-8855-af82a89e3adb.mp4

**Comment by tlle14** [comment]
Hi @EvGen94 
Retest failed.

**Actual Result**
When userA creates a direct chat with userB, and he has not sent a message yet, the chat is displayed on userB side.
https://images.zenhubusercontent.com/309637937/1a1e2c9c-e75f-4523-969f-604249e14b5b/20211109_171309__1_.mp4

**Expected Result**
When the userA has not sent a message yet, the chat shouldn't display.

**Comment by hoangdat** [comment]
> When userA creates a direct chat with userB, and he has not sent a message yet, the chat is displayed on userB side.

the same problem in web, please check in the back-end side. 

Close it
