### ISSUE TITLE
Update APP-wide fonts for mobile application

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#835]
We have to update the fonts used by the App to start using system-defined fonts, in particular, SF Pro display/text for iOS and Roboto for Android.

**Comment by tlle14** [comment]
Cannot check iOS version

**Comment by tlle14** [comment]
Hi @EvGen94 
Can you check again the font on iOS. 
In some places, I see texts are strange. But I'm not so sure.
 
On Syncing data screen:
![screenshot_24.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/b0e192fc-ca50-4aba-844e-6784ad105005)

On My Account screen
![screenshot_25.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f8dbbe33-d83f-4b7a-b8ed-726fdf1074f4)

**Comment by EvGen94** [comment]
There was a problem with the font for plain text inside the bubble, but now this bug is fixed, so everything looks fine

**Comment by tlle14** [comment]
I should close this one. It's fine now
