### ISSUE TITLE
Create Workspace > Unable to create a workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#837]
# Actual Result
After created, then refreshing the workspace list, the new workspace disappears
https://user-images.githubusercontent.com/69950655/129867898-465286d3-e738-4c0a-84fe-c0f832fe71f2.mp4

# Expected Result
The newly created workspace should be shown in the sidebar

# Environment
Build version: 3.0.5
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 I can create a workspace but the new workspace doesn't have a default channel "General"

**Comment by bobs4462** [comment]
@RomaricMourgues Is it possible that default channel is not created?

**Comment by RomaricMourgues** [comment]
I will check

**Comment by RomaricMourgues** [comment]
You were right we didn't generate the default channels with the node api, it will be fixed on next QA deployment (later today)

**Comment by tlle14** [comment]
Hi @RomaricMourgues 
We have the issue:
The invited members (who were invited when creating workspace) are not added in General channel. 
https://user-images.githubusercontent.com/69950655/134149262-ffa894ba-b177-44d2-badf-0ddde8c5f1e7.mp4

**Comment by RomaricMourgues** [comment]
They are not invited until they join the workspace currently.

**Comment by tlle14** [comment]
@RomaricMourgues sorry, I don't get the explanation.

**Comment by RomaricMourgues** [comment]
1. you invite people in workspace
2. people open the workspace and try to load the channels
3. they are invited to the default channels
Before the third step, users are not yet in the channel.

**Comment by tlle14** [comment]
@RomaricMourgues you might misunderstand the bug

1. UserA (Admin) is creating a workspace on Mobile App. He invites UserB, UserC and press "Create Workspace"
2. After the workspace is created, UserA checks on Web version. There's only him in the newly created workspace.

The issue is cannot invite members while creating workspace

**Comment by tlle14** [comment]
@RomaricMourgues @bobs4462 this issue should fixed for the release

**Comment by bobs4462** [comment]
@tlle14 as Romaric mentioned already, invited users should at least once open the workspace for confirmation, before that they are not members of that workspace

**Comment by tlle14** [comment]
How can invited users open the workspace for confirmation when they are not invited successfully?

**Comment by tlle14** [comment]
I will close this issue and open another to describe more specific the issue.
