### ISSUE TITLE
A long user's name breaks the UI

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#838]
# Precondition 
The user has a long name
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a9f21ea5-5a2a-42fb-a293-4c07c2f9b46d)

# Actual Result
When the user has a long name, it breaks the UI on:
1. Menu sidebar
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/eefccc3b-ad2b-4291-a995-27687fb52ea8)

2. Thread screen
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/597441be-68e0-4c91-9b51-ed96715810da)

# Expected Result
For a long user name, the app should display a part of it. 
Or we should ask Console team to apply the restriction.

# Environment
Build version: 3.0.5
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by tlle14** [comment]
Hi @EvGen94 
Retest failed!

Because it only displays in shape in above screens, but in some other screens/places that I didn't point out, it is still broken. 
Do you have solution for "one fix apply all"? OR should we ask Console team about their limitation?
1. [screenshot_8.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2c493091-9b5d-4fbb-ba86-50064a0e94db)
2. [screenshot_9.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6ba35fdd-0336-40e9-9ad2-d28fb35e87c9)
3. [screenshot_10.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2721811f-29d8-452b-ba3e-0a1d7e4447f5)
4. [screenshot_11.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/cce85c1c-b253-4ca4-a9d6-601ab379ec72)

**Comment by EvGen94** [comment]
The maximum size of the name on the screen depends on the size of the screen, and this depends on the device itself and it will not work to make one restriction since there are different screens. I will fix it in the remaining screens/places

**Comment by tlle14** [comment]
Hi @EvGen94 
1. Failed. This screen should be fixed
2. Pass
3. Not fix. It's okay
4. Pass
5. Please fix
![screenshot_31.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/cae39b91-74e6-482a-99b6-11510222cf9c)

**Comment by EvGen94** [comment]
@tlle14 Hi!
5 - is fixed, I did not get what is wring with first, I checked one more time - looks fine

**Comment by tlle14** [comment]
Thanks, 
Retest pass!
