### ISSUE TITLE
Login/Logout > The webview in App displays address bar

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#840]
# Actual Result
It displays the address bar
- on the login screen
![screenshot_2](https://user-images.githubusercontent.com/69950655/130174430-ea069591-1f6a-42ae-b6bc-c144325d6692.png)

- when log out, on the redirected screen
https://user-images.githubusercontent.com/69950655/130175712-1d766866-74db-43c3-a39e-bb2975bb524c.mp4

# Expected Result
The address bar should be hidden in the app, to make the user feels like they are using the native app all the time 

# Environment
Build version: 3.0.5
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by bobs4462** [comment]
I'm sorry but that's not possible, because it's not a webview, it's an external browser, and we have no control over it

**Comment by tlle14** [comment]
okay i got it. Thank @bobs4462

**Comment by tlle14** [comment]
Sorry @bobs4462 Could you please consider the solution in this document https://developer.chrome.com/docs/android/trusted-web-activity/integration-guide/#remove-url-bar

If we can apply, it could be great for UX. But not urgent.

**Comment by bobs4462** [comment]
@tuanlc can we host a file on twake console servers as per this instruction?
https://developer.chrome.com/docs/android/trusted-web-activity/integration-guide/#remove-url-bar

**Comment by tuanlc** [comment]
Hi,
1. Which file do you want to host?
2. Are you sure all of the client devices use chrome as the default browser? What happens if they don't have chrome on their devices? Then you need to find the solution for other browser too.

**Comment by bobs4462** [comment]
1. I'll provide you with json file a little later, now I'm just interested in how hard it is to host it
2. By default all the android devices (except for the very old ones) will use chrome tabs as default, which is what we need, in case they manually open other browser, then it's alright to show the address bar
