### ISSUE TITLE
Sign In > Keyboard allows the first character in the email field to be capitalized by default

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#842]
# Actual Result
When starting to type on the email field, the keyboard enables the capitalization mode.

https://user-images.githubusercontent.com/69950655/130209358-7ff9c239-0adb-4a1d-ad30-f2d774191e0a.mp4

# Expected Result
The keyboard shouldn't enable the capitalization mode by default when inputting the email

# Environment
Build version: 3.0.5
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by bobs4462** [comment]
@tuanlc Hello, can you guys take a look at that, cause we have no control over the keyboard on web

**Comment by tuanlc** [comment]
> @tuanlc Hello, can you guys take a look at that, cause we have no control over the keyboard on web

Hello,
Let's me check.

**Comment by tuanlc** [comment]
The fix is deploying to pre-prod and prod platforms. I will keep you informed.

**Comment by tuanlc** [comment]
The issue was fixed and deployed to QA and PROD platforms.

*Note: if it does not work for you, please clear the browser cache*

**Comment by tlle14** [comment]
Retest pass!
Thank @tuanlc 

https://user-images.githubusercontent.com/69950655/130433222-6dc20200-01a9-4b9d-a0fb-c9b351c577cf.mp4
