### ISSUE TITLE
Cannot add member in the public channel 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#849]
# Actual Result
It is not allowed to add members while creating a new public channel.
![screenshot_15](https://user-images.githubusercontent.com/69950655/130575097-c96980dd-1b7e-4b41-a90f-0485c099dd94.png)

# Expected Result
Comparing to the Web version, it should be able to add members while creating a new public channel

# Environment
Build version: 3.0.5
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Could you please, ask developers to enable this option in the app. I have no influence over it. Design is just layout that serves as a guidance for developers.

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen 
Hi @bobs4462 could you please take a look?

**Comment by tlle14** [comment]
Retest pass! 
I can add members to a public channel. 
By the way, could you please add the label "INVITED MEMBERS" like the one in creating a private channel?
https://images.zenhubusercontent.com/309637937/b636022a-f4d9-40b1-bfd7-dc6cc6014313/videoe4669ff7_587b_47f4_aef3_c1aa00b74587video.mp4

**Comment by EvGen94** [comment]
@tlle14 
Done

**Comment by tlle14** [comment]
Thanks @EvGen94 
![screenshot_73.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e8226968-0521-4399-b25d-2d54b4122b15)

@BastiaanVanGaalen please take a quick look at the position of the INVITED MEMBERS label. I still have a little concerning about this. Should it be under the toggle? If you think it's okay, we can close this issue

**Comment by tlle14** [comment]
I saw the design already. It matches with the design. 
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/60a5106dfac5792b56c6d95b
