### ISSUE TITLE
Channel > Always displays "No members" in a channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#851]
# Precondition
A channel has more than one members

# Actual Result
It always displays No member in the channel

# Expected Result
It should display the correct number of members in the channel

# Environment
- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
It's backend issue, which @RomaricMourgues and his team are working on, alas I don't know when it's going to be fixed

**Comment by tlle14** [comment]
Thank @bobs4462 I created a new label "backend" for the backend issues. We will keep tracking those.

**Comment by tlle14** [comment]
Thanks, retest pass! 

https://user-images.githubusercontent.com/69950655/151125537-ec600823-1339-41a3-93b2-211b9d6d9232.mp4


By the way, it relates to this issue:
https://github.com/linagora/Twake-Mobile/issues/1210
