### ISSUE TITLE
Thread > Loading replies in the first time quite slow

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#853]
# Actual Result
When opening a thread, it takes time to load replies 
https://user-images.githubusercontent.com/69950655/130606482-b48010a7-0022-4428-916d-063adca6b1e6.mp4

# Expected Result
Please increase the loading speed of the replies. 

# Environment

- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by bobs4462** [comment]
@tlle14 I'm afraid nothing we can do here, the only option is sync all reply messages beforehand when syncing data, but that might take 10-20 minutes on avarage, so this is not an option at all.

**Comment by tlle14** [comment]
Okay, thank @bobs4462
