### ISSUE TITLE
Login > Login on the browser will lead to login on the App

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#854]
# Precondition
Story: https://github.com/linagora/Twake-Mobile/issues/744
The user has not been logged in on Browser and App

# Actual Result
When login on the browser successfully, then open the app, the app is automatically logged in. 
https://user-images.githubusercontent.com/69950655/130727089-d9f395d1-5194-4279-99b0-8f6722c20259.mp4

#Expected Result
Please confirm if this is expected behavior.

# Environment

**Comment by bobs4462** [comment]
Yes that's expected behavior, that's whole point of OIDC, that if you login from browser, then all the apps can use the stored session if the need, for example in future you might need to login once, and will automatically will be logged in linshare, calendar and twake

**Comment by tlle14** [comment]
What if I switch to another account on the browser? Does the app also switch?

**Comment by bobs4462** [comment]
Nope, the app will continue using current account, until you logout (in which case the session is going to be cleared).

**Comment by tlle14** [comment]
Thank @bobs4462
