### ISSUE TITLE
Direct > direct chat only jumps to the top and display preview when posting a reply

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#855]
# Actual Result
When posting a message (not a reply) to a direct, the chat doesn't jump to the top and also doesn't display the newest message as a preview
https://user-images.githubusercontent.com/69950655/130774650-ec6fa149-6458-4d09-a715-70c9874c7991.mp4

# Expected Result
Any new message is posted in the direct chat should make the chat jumping on top and display in a preview on the direct list

# Environment

- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
It's related to direct chat synchronization #834 #827

**Comment by bobs4462** [comment]
Once it's fixed on backend, it'll start working on it's own

**Comment by tlle14** [comment]
Thanks,
Retest pass!

https://user-images.githubusercontent.com/69950655/135567416-bce9befb-5fe0-4640-bcbe-a3b568e502ef.mp4
