### ISSUE TITLE
Using different words to describe the same things between Web version and Mobile version

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#858]
# Actual Result

There are some different words to describe the same things between Web and Mobile versions.

Screen | Mobile | Web
-- | -- | --
Sidebar | Switch Organisation | Change Company
  | Add a new workspace | Create a workspace
Main screen | Chats | Direct messages
Channel screen | 18 Aug 2021 | August 18, 2021
  | View 4 replies | View all answers (4)
Chat textbox | New reply... | Write new message. Use @ to quote a user
Edit channel | Member management | UserUser in <channel_name>
  | Add a memberSearch for members | Add or search user
  | Channel type | Confidentially
  | Edit channel infoChannel setting | Edit channel
  | Channel description | Describe a channel
Create direct chat | New direct chat | New private discussion
  | Create a new channel | Create a channel
  | Invited members | User in <channel_name>

# Expected Result
Using consistent words between screens and 3 versions Mobile/Web/Console. 
Please discuss with other teams

**Comment by bobs4462** [comment]
@BastiaanVanGaalen any news?
