### ISSUE TITLE
Cannot load chat history 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#861]
# Actual result
It keeps displaying the loading screen when opening a channel/ direct has chat history
![screenshot_4](https://user-images.githubusercontent.com/69950655/131269071-4cc7d108-5c03-4936-b433-11e935954011.png)

# Expected Result
Chat history should be shown 

# Environment
Build version: 3.0.6
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by bobs4462** [comment]
https://drive.google.com/file/d/1OEulQXKLJNVSNvxJvQGA2GUSWvXF8_iF/view?usp=sharing I wasn't able to reproduce this issue with one of your test accounts...

**Comment by tlle14** [comment]
Test environment issue
