### ISSUE TITLE
Create new direct chat > sometimes it doesn't display user's avatar

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#862]
# Precondition
Create a new direct chat screen

# Actual Result
For some users, it displays the default avatar instead of user's avatar
![screenshot_6](https://user-images.githubusercontent.com/69950655/131270078-51a3f717-7733-4e8c-b9c9-e322a1edd4ed.png)

On Console
![screenshot_7](https://user-images.githubusercontent.com/69950655/131270092-c11a61f2-ec1e-4c80-a701-8e86c0503d03.png)

# Expected Result
It should display the avatar that the user has set

# Environment
 Build version: 3.0.6
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment and Prod

**Comment by bobs4462** [comment]
@tlle14 does it happen randomly?

**Comment by tlle14** [comment]
> @tlle14 does it happen randomly?

Nope, for all channel

**Comment by bobs4462** [comment]
I mean user avatars, do they sometimes load and sometimes not?

**Comment by tlle14** [comment]
> I mean user avatars, do they sometimes load and sometimes not?

Yes, it's different for each logged-in account. 
Such as: when Cyan logged in, Cyan's avatar doesn't display
When Red logged in, Cyan's avatar display

Sorry, I read the wrong issue.

**Comment by bobs4462** [comment]
@tlle14 Sorry, nothing I can do here, I've checked it with Cyan and other accounts, I couldn't reproduce your case, but sometimes there's broken links set to user images in Twake backend cache (the only way to solve the issue is to reupload the same image to twake console and relogin). I'm afraid nothing we can do about the way the backend works... And the bug seems to be inconsistent

**Comment by tlle14** [comment]
>but sometimes there's broken links set to user images in Twake backend cache (the only way to solve the issue is to reupload the same image to twake console and relogin)

Hi @bobs4462 there must be something cause the broken link. Is it from backend?

**Comment by bobs4462** [comment]
Yes, for now the images can only be set from web, and I presume backend is might be saving them in wrong format (or it may have happened in the past, and no longer is the issue now for newly saved images)

**Comment by tlle14** [comment]
Hello @RomaricMourgues @tuanlc does your team aware of this issue? 
Something on the backend affects the way the avatar displaying on Mobile App. Could you please take a look?

**Comment by RomaricMourgues** [comment]
No reason for backend not to send you the correct image. We can have an issue between console / twake sync but it would affect the visibility of the avatar for all users not only some of them.
Let's try this again when we deploy our next version end of week.

**Comment by tlle14** [comment]
Seems okay now. 
Thanks
