### ISSUE TITLE
Code snippets formatting redesign in Twacode renderer

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#863]
We have to update the way code snippets are rendered in Twacode as per new design 
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/6089efad2284bd2dd02877c9
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/6089efad862fe732851ea5b6

**Comment by tlle14** [comment]
Hi @EvGen94 
We have issues:
1. The new format is not applied on Android. 
It seems alright on iOS.
**iOS**
[screenshot_28.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/c699bc05-5ddf-4d62-ad3d-f62ad7d576e7)

**Android**
[screenshot_29.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a3a2f28f-1cf1-496f-b819-feb35f8299c5)

2. The paragraph border is more narrow than in the design
=> Expect: the paragraph border should be in the center of bubble speech. 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/904520e3-499c-4d15-8e60-ebcfe6c0ab1c)

**Comment by tlle14** [comment]
Thanks, retest pass!
![screenshot_70.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/28452a27-60df-4c0d-824e-578165c18917)
