### ISSUE TITLE
Channel list screen > It focus on Search bar as a default state

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#868]
# Actual Result
When opening a channel list/direct list, it always focuses on the Search bar and opens the keyboard. 
https://user-images.githubusercontent.com/69950655/131488813-bd8cc46e-eee7-4cb9-b0a7-bfb3e4363d8c.mp4

# Expected Result
When opening a channel list, it shouldn't focus on the search bar. That will open the keyboard and hide a half of the screen

# Environment

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment and Prod

**Comment by EvGen94** [comment]
@tlle14 Hello!
I can't reproduce this bug, probably it has already been fixed

**Comment by tlle14** [comment]
> @tlle14 Hello!
> I can't reproduce this bug, probably it has already been fixed

Hi @EvGen94 first you have to tap on search textbox then open a channel. When you are back from the channel to the channel list, you will see the keyboard displays

**Comment by tlle14** [comment]
Sorry, this is not a valid bug. We can consider as an improvement or not. 
I should close this ticket.
