### ISSUE TITLE
Channel > When reaching to the first message in the channel, it should display the channel info

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#869]
# Actual Result
When scrolling down to the first message in the channel, it continues refreshing the channel but nothing more. 

https://user-images.githubusercontent.com/69950655/131611257-e9690d4c-dfd8-4c57-9743-cce57cd36f4e.mp4

# Expected Result
When reaching the first message in the channel, it should display the channel info as in the Web version.
There shouldn't have a swipe-to-refresh
![screenshot_17](https://user-images.githubusercontent.com/69950655/131611364-f4001fde-e9fd-42ef-8043-90b736d916d7.png)

# Environment

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 https://zpl.io/bAwALBp

**Comment by tlle14** [comment]
Hi @EvGen94 Thanks for the fixing. But we need to resolve some small issues:

1. The date should display under the channel info
2. Icon background is white, not gray. 
3. The distance between the channel icon/ channel name and the welcome message should be 12px and 8px as in the design.

**Comment by EvGen94** [comment]
@tlle14 Hi! 2 and 3 are ready, 1 cannot be done now, as it takes a lot of time to replace the main chat widget, maybe we need to make a new issue for that

**Comment by tlle14** [comment]
It's okay. I will do. Thank @EvGen94 
#1 is posted here https://github.com/linagora/Twake-Mobile/issues/987

**Comment by tlle14** [comment]
Thanks,
Retest pass!
![screenshot_101.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/7c3fcfd8-df3b-4e71-9f06-aafb9ab45a92)
