### ISSUE TITLE
[Story] Message history limitation

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#871]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a free user of Twake,
When I want to scroll in the history of the channel
Then I am blocked after 1000 messages
And I can see a message saying that I have to upgrade to see more history
```

## Criteria
- [ ] As a free user, I can't go back in the history more than 1000 messages
- [ ] As a free user, when I reach 1000 messages in the history, I can see a message saying I have to upgrade
- [ ] Link of "learn more" redirects to the pricing page if I am not the company owner
- [ ] Link of "learn more" redirects to the plan page of the console if I am the company owner

## UI UX Design
![messageLimit.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/4f31f972-aa87-46ff-a477-9e971d2d29a2)
## Related
Epic : #872
Web PR related : https://github.com/linagora/Twake/pull/1339

**Comment by bobs4462** [comment]
Hmmmm, I think that this kind of behavior should be handled by backend, it should only return last 10000 messages (per channel???) and then return some kind of flag indicating that there's more, but the upgrade is needed

**Comment by BenoitTallandier** [comment]
You're right, we will build it in backend
