### ISSUE TITLE
Message > It is open the browser inside Twake App when clicking a link

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#875]
# Precondition
A message contains a link

# Actual Result
When tapping on the link, the app will open a browser inside. 
https://user-images.githubusercontent.com/69950655/131662399-3e7bee98-a309-4da6-81e4-97d726dac014.mp4

# Expected Result
When tapping on a link, it should open the link on the browser app, not inside Twake app
If it is able to open a link inside the app, it should allow the user to choose to open the link on the browser app. 

# Environment
- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- Production

**Comment by bobs4462** [comment]
I've update the code, so that all the links are opened in browser for security reasons (not webview). And if the user has no default browser, is should ask which browser to use. Available in next build.

**Comment by tlle14** [comment]
Thanks,
Retest pass!
https://images.zenhubusercontent.com/309637937/2d7a69ef-2c67-400b-bd5c-c20411d11c6e/video0312a947_7439_4007_a22e_0a9814ec2d05video.mp4
