### ISSUE TITLE
Create channel > Missing option  "Automatically invite all workspace users to this channel" when creating a public channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#880]
# Precondition
Creating public channel

# Actual Result
When creating a public channel, there is missing the option "Automatically invite all workspace users to this channel" as on the Web version
**Mobile:**
![screenshot_20](https://user-images.githubusercontent.com/69950655/132157937-0d9c5806-46ff-4653-9c97-7905c70078ca.png)

**Web:**
![screenshot_21](https://user-images.githubusercontent.com/69950655/132158804-44824ea2-68c7-44ab-b2d9-0530f3309ae1.png)

# Expected Result
There should have an option  "Automatically invite all workspace users to this channel" as on the web version

# Environment
Build version: 3.0.6
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by tlle14** [comment]
@shivam9593 Hi, you can track the issue here

**Comment by BastiaanVanGaalen** [comment]
@tlle14 https://zpl.io/aX7dnDl

**Comment by bobs4462** [comment]
@RomaricMourgues hello, what is the flag in the following API request to include all members of workspace in the newly created channel?
https://www.notion.so/twake/REST-Api-Websockets-Api-458b153a6a6e46c2925dfc1db3859d3b

**Comment by RomaricMourgues** [comment]
This is the "default" flag

**Comment by bobs4462** [comment]
@RomaricMourgues, I've created a channel with default flag set to true, and no existing user in the current workspace was added to this channel, so I suppose that default flag is set only for the new users joining the workspace not for already existing ones

**Comment by bobs4462** [comment]
@RomaricMourgues any ideas?

**Comment by RomaricMourgues** [comment]
Of course this is a bug then, I'll check

**Comment by RomaricMourgues** [comment]
Could you give me the environment you tried on ? I just tested now and it was working (both when editing channel and when creating channel with default parameter).
Maybe we fixed it in the last days but not sure.

**Comment by bobs4462** [comment]
It's QA environment, a workspace has a 5 members, when creating a new channel the default flag is set, and all 5 members supposed to automatically to be added to channel, but the channel has only 1 member as a result

**Comment by hoangdat** [comment]
@tlle14 please verify it, it is available in latest version.

**Comment by tlle14** [comment]
Hi @hoangdat the option is displayed in the latest version, but it doesn't work. 
Please fix. 

https://user-images.githubusercontent.com/69950655/140272398-9f6c023a-df89-4ae0-96aa-78e47ebfdc13.mp4

**Comment by hoangdat** [comment]
@tlle14 why you reopen this, please comment when you take any action like close/reopen

**Comment by tlle14** [comment]
Hi @hoangdat this issue is not retested before it was closed.
Please move it to the QA testing column for retesting in the next build (if it is ready)

**Comment by tlle14** [comment]
Thanks, 
Retest pass!

https://user-images.githubusercontent.com/69950655/143417424-ab02f42d-5684-40e9-8126-426d7197e9d5.mp4
