### ISSUE TITLE
iOS > Using the old logo when swipe up to see the running app list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#884]
# Precondition
Swipe up to see the currently running app list

# Actual Result
Twake app is using the old logo when displaying in the running app list
![screenshot_26](https://user-images.githubusercontent.com/69950655/132336564-4130546a-3b71-46f1-af82-4663aa8a5e0a.png)

# Expected Result
The logo should be updated

# Environment
Build version: 3.0.5
Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
QA environment and Prod

**Comment by EvGen94** [comment]
@tlle14 Hi!
You just need to restart your device this is due to the some cache of the old version of the application, after restarting this issue should go away

**Comment by tlle14** [comment]
Thank @EvGen94 
You're right. It works
![screenshot_46](https://user-images.githubusercontent.com/69950655/133716624-362d81a0-c210-4d7a-ac34-1391951f3459.png)
