### ISSUE TITLE
Sign Out > When logging out, it always displays the popup asking to continue sign in

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#886]
# Precondition
Twake App on iOS

# Actual Result
When logging out, it always displays the popup asking to continue sign in. User needs to choose to continue to sign out successfully
https://user-images.githubusercontent.com/69950655/132488324-6f078899-dfdd-420d-921b-11fb1354d94c.mp4

# Expected result
The pop-up is not appropriate. 
Please consider removing it.

# Environment

- Build version: 3.0.5
- Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 @EvGen94 
Retest failed!
https://images.zenhubusercontent.com/309637937/3d0fc07e-ef1a-42af-8b2e-445af29da8b5/rpreplay_final1632280864__1_.mp4

**Comment by EvGen94** [comment]
Hi! @tlle14 Can't fix this until this issue is open https://github.com/openid/AppAuth-iOS/issues/643

**Comment by tlle14** [comment]
Thank @EvGen94 for your information.
I should change this ticket to icebox since it is out of our capability.
