### ISSUE TITLE
Create Channel > The newly created channel doesn't display for invited members

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#897]
# Precondition
Create a new channel
Invite some members while creating a channel

# Actual Result
The newly created channel doesn't display for the members
Creator screen:
![screenshot_33](https://user-images.githubusercontent.com/69950655/132624327-fd9a1884-6d51-4715-a2f4-ae1b4ff9c7b3.png)

Member screen
![screenshot_34](https://user-images.githubusercontent.com/69950655/132624344-c19e998d-60a9-449b-a11c-a82247751caa.png)

# Expected Result
The newly created channel should display on the member's channel list

# Environment

- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed! 
Could you please check?

**Comment by tlle14** [comment]
@bobs4462 @EvGen94 this bug should be fixed. Could you please check?

**Comment by tlle14** [comment]
Hi @bobs4462 
It only displays public channel for invited user.
The private channel doesn't display. 

Could you please check?

**Comment by hoangdat** [comment]
Current:
Fetch channels by:
```
@GET /internal/services/channels/v1/companies/{companyId}/workspaces/{workspaceId}/channels?mine=1
```
Response not return any private channel.

@RomaricMourgues please share us the documentation for API or swagger for the API.

**Comment by hoangdat** [comment]
@BenoitTallandier one question, I checked on the web, only public channel is showed. It is requirements or bug?

**Comment by tlle14** [comment]
Hi @hoangdat it's an issue when you created a private channel on mobile but the channel doesn't display on the Web.

**Comment by hoangdat** [comment]
> ```
> @GET /internal/services/channels/v1/companies/{companyId}/workspaces/{workspaceId}/channels?mine=1
> ```

Hi @RomaricMourgues please help me check the API

**Comment by tlle14** [comment]
Hi @RomaricMourgues do you have any update on this? 
CC: @huynguyennovem @EvGen94

**Comment by EvGen94** [comment]
Checked, sent all the information to Romaric 
We need  to wait till next release

**Comment by RomaricMourgues** [comment]
Hi, on web it was a realtime room we forgot to listen to, make sure to listen to the two websocket rooms, the first one is for public and the second one for private channels

**Comment by EvGen94** [comment]
@RomaricMourgues Hi!
I checked this issue one more time, same behavior on web and mobile, user can see only public channels, not created private (web.qa)

**Comment by RomaricMourgues** [comment]
I don't have the issue on web.qa, could you confirm on web that it still doesn't appear after reloading the page either ?

**Comment by EvGen94** [comment]
Yes, I can't see it
The problem is that while you create a private channel from mobile and add members to it, then they will not see it, but if you just create a private channel without members and then start adding users after creating, then the channel will be displayed to them

**Comment by EvGen94** [comment]
As result - now we just need to wait till the api will be updated to support this action

**Comment by EvGen94** [comment]
@RomaricMourgues 
Checked, looks fine now, thanks.
