### ISSUE TITLE
Create channel > It doesn't display the Creator in the member list

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#898]
# Actual result
UserA creates a channel and invites UserB, UserC
But in the member list, it only displays UserB and UserC

# Expected Result
The member list should display the Creator 

# Environment

- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
Hello, is it after creation or during creation?

**Comment by tlle14** [comment]
@bobs4462 it's after creation

**Comment by tlle14** [comment]
Retest failed!
Sorry @bobs4462 for lacking the evidence
 https://images.zenhubusercontent.com/309637937/f942c512-2153-4a81-92b4-e2721c29bd06/video7b4dec18_2d68_4350_8eac_ae55c8a0aa13video__1_.mp4

**Comment by bobs4462** [comment]
@RomaricMourgues When using the nodejs endpoints to create a new channel

![image.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/8f82a274-a03d-4581-aed3-304e3b1eaca5)

We attach members (including the current user's id) via options field. Then when requesting channel members (nodejs) we get those members back. All is good, but the the other members are not really invited to channel, when you check via web the only channel member there is the creator (presumably different endpoints). But the fact is the invited members do not see the newly created channel

**Comment by RomaricMourgues** [comment]
And are the users invited when calling the channel members route and invite them one by one ?

**Comment by bobs4462** [comment]
Yes, if you add them manually (different endpoint), then yes, they are added just fine. The issue is only when creating a new channel

**Comment by RomaricMourgues** [comment]
Fixed here: https://github.com/linagora/Twake/pull/1671 (soon in QA)
