### ISSUE TITLE
Timestamp is too long when displaying in a speech bubble

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#901]
# Actual Result
In a thread screen, a long timestamp makes more narrow space for text.
![screenshot_35](https://user-images.githubusercontent.com/69950655/132680135-18f5295b-5087-4ae1-8b8e-7ad525cf05e9.png)

# Expected Result
The timestamp should display in a line break
I know it's different with the design, so I'm asking for the opinion of @BastiaanVanGaalen ? How do you think?

# Environment

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Text behaviour is totally wrong. It wasn't supposed to work like that. For timestamp we have to reserve the last string of the message bubble, but the text should span across the whole bubble, it mustn't be somehow dependent on timestamp.

If we take a look at the implementation of timestamp and textual content placement we will see that they don't interfere with each  other in any way. I'm attaching the screenshot of Signal where we can see THAT THE LAST STRING IS RESERVED FOR TIMESTAMP AND MESSAGE BODY SPANS ACROSS THE BUBBLE WIDTH. We have to implement it exactly like that. 

Thank you for raising such important topic, <3

![IMAGE 2021-09-10 01:09:37](https://user-images.githubusercontent.com/75843710/132769082-899a96dc-b394-4b5c-82f7-fd8bdab9e4d1.jpg)

**Comment by tlle14** [comment]
@bobs4462 @EvGen94 please take a look at this ticket. We should fix it as the Designer suggests. Thank you.

**Comment by BastiaanVanGaalen** [comment]
@tlle14 It was decided after a discussion that we display timestamp on screen with threaded replies in the following format: "Date/Time" inside a message bubble on a separate line.

As for general message feed of the channel only "Time" is displayed inside a message bubble on a separate line. @EvGen94

**Comment by tlle14** [comment]
> @tlle14 It was decided after a discussion that we display timestamp on screen with threaded replies in the following format: "Date/Time" inside a message bubble on a separate line.
> 
> As for general message feed of the channel only "Time" is displayed inside a message bubble on a separate line. @EvGen94

Thank @BastiaanVanGaalen 
But in the thread design, I see we have date line. Do we need displaying the date inside a message bubble? 
![screenshot_38](https://user-images.githubusercontent.com/69950655/133077750-3a051f39-30a7-4e2b-9895-52a51b76e217.png)

**Comment by EvGen94** [comment]
@tlle14 Hi!
For threads we will not display this date line, we will write the date in the bubble on a separate line

**Comment by tlle14** [comment]
Thank @EvGen94 
This is noted.

**Comment by tlle14** [comment]
Hi @EvGen94 Thanks for the fix. It's great!
But could you please place the timestamp a little lower? It seems too near the last line (Please check on the real device, you will see how close it is)

**Actual:** 
![screenshot_69.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f6679d2a-1728-4ce3-9138-0b7d9aaa93f4)


**Expected:** It should be this far
![screenshot_68.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6bfcbb89-b556-4f50-9f1b-29107c5df70a)

**Comment by tlle14** [comment]
Hi @EvGen94 
I think the timestamp is till displaying incorrectly. 
But it's not urgent right now. 
Please fix it when you have time. 
![screenshot_103.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/4f080c1c-aaf6-4160-86ba-ff1698ff5347)

Should be:
![screenshot_104.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d294cc29-54cd-4889-bc8c-7421fe441e4e)

**Comment by sherlockvn** [comment]
#1337
