### ISSUE TITLE
A giant loading icon displays on a sidebar menu

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#908]
# Actual Result
On the sidebar menu, sometimes, the giant loading icon (which is a vertical stretching icon) displays when loading a workspace list
I encounter this issue sometimes, not always can reproduce (when the connection speed is slow).

# Expected Result
The loading icon shouldn't be stretched vertically. 
It should display a normal loading icon

# Environment

- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi @bobs4462 
Do you know how to reproduce this case? I cannot retest

**Comment by bobs4462** [comment]
Yes, just login and open the side drawer immediately

**Comment by tlle14** [comment]
It's flat-out, I cannot see the giant loading icon. 
Should close this one. 
Thank @bobs4462
