### ISSUE TITLE
Create Direct > When creating a direct, people in the list are displaying depend on the workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#909]
# Precondition
WorkspaceA has 7 people
WorkspaceB has 5 people

# Actual Result
When creating a direct chat:
- When the user is in WorkspaceA, it displays 7 people in the PEOPLE list 
- When the user is in WorkspaceB, it displays only 5 people in the PEOPLE list

https://user-images.githubusercontent.com/69950655/133076798-64274437-c214-4db2-8f4e-f03610b0dc10.mp4

# Expected Result
It should display a whole company in the PEOPLE list, shouldn't depend on the workspace.
But with the Guest user, it only displays people in the channel that the Guest is in. 

# Environment
- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hello @BenoitTallandier could you please confirm the behavior with the guest user in Expected Result? I cannot find the related requirement in Twake.

**Comment by BenoitTallandier** [comment]
It is right. 
Guest shouldn't be able to see people outside members present in the channels where they are invited.

For internal, they shouldn't see all company user. The list is only active discussion. Of course, internal user can start a discussion with every user in the company. But if the discussion is not started, or if the user hide (~archive) the discussion, it shouldn't be in the list.

**Comment by tlle14** [comment]
> For internal, they shouldn't see all company user. The list is only active discussion. Of course, internal user can start a discussion with every user in the company. But if the discussion is not started, or if the user hide (~archive) the discussion, it shouldn't be in the list.

The list you mentioned is RECENT CHATS. It won't display archive chats or the not-yet-started discussion. 
PEOPLE list is a kind of list which the user can scroll and select somebody to start the discussion.
![screenshot_39](https://user-images.githubusercontent.com/69950655/133097421-79a0ce94-6684-450a-af6c-a42d8eb02fee.png)

**Comment by BenoitTallandier** [comment]
My bad, I didn't get the point. 
You're totally right, an internal user is able to see everyone in this list :)

**Comment by tlle14** [comment]
Thank @BenoitTallandier for your confirmation

**Comment by bobs4462** [comment]
@RomaricMourgues is there a way to map users to company?

**Comment by RomaricMourgues** [comment]
No, the only thing you can do is search users in the whole company but not list them all.
Until now it was on purpose. Could we put in this "people" list:
- The people we recently talked to (got from chats)
- Then the people from the workspaces
As soon as you start to "search" you can also complete with other peoples in the company from the search endpoint: 
<img width="803" alt="Screenshot 2021-09-14 at 10 46 29" src="https://user-images.githubusercontent.com/14353924/133226202-5c743991-6d0e-4a17-8e26-b99d22077b7d.png">

**Comment by bobs4462** [comment]
Well, that's not exactly convenient, as currently search happens on local storage, which is why it's super fast. But if there's no other way around it, we will implement that

**Comment by RomaricMourgues** [comment]
It is about what we do in the future, it seems now we are open to allow chats between any user in the world…
The company users list will be implemented too in the near future.

**Comment by bobs4462** [comment]
Oh.....

**Comment by tlle14** [comment]
Retest pass!
It displays all company accounts for creating direct chats. But, it does not work for the Guest 
https://images.zenhubusercontent.com/309637937/b3004735-3862-41fe-af05-fd88b8b23d76/video5410fdca_9605_4fe3_9ef6_4cd956d89f81video.mp4
Retest after this issue is fixed https://github.com/linagora/Twake-Mobile/issues/958

**Comment by bobs4462** [comment]
I think you can close this one, as it's not really related to #958
After we will allow guests to create direct chats, there will be a totally separate logic for fetching the list of available users

**Comment by tlle14** [comment]
Okay, I will remark the logic for Guest on #958 and close this one
