### ISSUE TITLE
Message > A hashtag doesn't display correctly on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#91]
# Actual Result
A hashtag displaying as a mentioned text on a mobile

On Web:
![image](https://user-images.githubusercontent.com/69950655/101901818-3902d000-3be4-11eb-9c60-8017d5f909e9.png)

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/101901918-6780ab00-3be4-11eb-8885-6d95481595c2.png)

# Expected result
The hashtag should display as a hashtag on mobile
`#hashtag `

**Comment by bobs4462** [comment]
@romanesko  Seems to be twacode issue

**Comment by tlle14** [comment]
Hi @bobs4462 
It is temporarily fixed by displaying # before the text. 
But the hashtag channel which is clickable exposes the channel_ID. 

On web:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/186c15bd-1069-4532-b943-ce106c8f2469)

On Mobile:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/07b160a2-31ea-4c6f-bb75-a99fc544d340)

Expected result:
- Let @RomaricMourgues confirm if the hashtag channel should be always clickable
- The hashtag channel shouldn't show its ID

**Comment by bobs4462** [comment]
I've removed channel IDs when rendering real channels. As for the click-ability of the channel names in channel mentions, we don't yet implement mention based navigation (for users, channels or message links). In order to do that we need a stable API, and as far as I know, the message format is undergoing a heavy development phase right now.

**Comment by tlle14** [comment]
Okay, thank @bobs4462 
Let remove the IDs first ;)

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/3ec83120-296e-406e-8bb5-29a607fad553)
