### ISSUE TITLE
Message > The sending time is incorrect when having a fail-delivery message

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#914]
# Precondition
Posting a message in a channel but sending fails

# Actual Result
After that, posting another message. 
Even the new message is sent successfully, but its time is in the past, before the failed-sending message

https://user-images.githubusercontent.com/69950655/133222466-95e39d51-41c2-4efe-a966-795e5732a995.mp4

# Expected Result
The posted message should have the correct sending time

# Environment

- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
- QA environment

**Comment by bobs4462** [comment]
https://images.zenhubusercontent.com/309637937/547b6ed6-55a2-42ab-9fd0-aaefea911c07/bug.mp4
not sure how to reproduce your bug...

**Comment by tlle14** [comment]
I cannot reproduce the issue on iPhone, but on Samsung A51 Android phone, it seems to happen regularly
Also, the connection on Samsung is not good.

https://user-images.githubusercontent.com/69950655/133227957-4752f10b-76da-4560-9a99-da89c5c6c34e.mp4

**Comment by tlle14** [comment]
Hi @bobs4462 @EvGen94 
I have a clue on this issue. 
2 of my phones have a different timezone. 
----
For example:
Phone1 clock is faster than Phone2 clock about 2 or 3 mins.

On the phone1, I sent messages: 1 -> 2
On the phone2, after that, I sent messages: 3 -> 4 -> 5
But 3,4,5 is placed between 1 and 2  (1,3,4,5,2)
https://user-images.githubusercontent.com/69950655/135443107-cb9b94ab-5602-41bd-9df3-9e8ee22709ea.mp4

After I refresh the channel list, messages are sorted in the correct order (1,2,3,4,5)
https://user-images.githubusercontent.com/69950655/135443547-bf67a908-603d-49d9-aa26-26882dd57c72.mp4

**Comment by EvGen94** [comment]
@tlle14 hello! fixed that pls take a look 
how it was https://images.zenhubusercontent.com/309637937/dd271ab2-6004-44a6-8d60-1c06d4a96342/was.mp4 
how it is now https://images.zenhubusercontent.com/309637937/4639ecd5-bd17-44dd-8b3c-479d4ffb74be/is.mp4

**Comment by tlle14** [comment]
Thanks, 
Retest pass

https://user-images.githubusercontent.com/69950655/146872479-67d5cec9-51dd-4051-a3a3-c530813e657c.mp4
