### ISSUE TITLE
Direct > Hide the direct chat then open it again, the chat history doesn't display at first

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#927]
# Precondition
UserA hides a direct chat with UserB

# Actual Result
When UserA creates a direct chat with UserB, the direct chat is displayed but doesn't show the chat history.
The User needs to back to the Direct chats list, refresh the screen to see the chat history again

https://user-images.githubusercontent.com/69950655/133419407-64f35076-7821-492a-8de0-58674de54a30.mp4

# Expected Result
When the user reopens a direct chat, the chat history should be shown instantly

# Environment

- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@RomaricMourgues is it possible for the request like the following one to return last_message field as well? Because we are relying on it for some features
```
curl -X POST https://web.qa.twake.app/internal/services/channels/v1/companies/ab441952-8d3e-11eb-9f13-0242ac120005/workspaces/direct/channels \
    -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzE3Nzg0NjUsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2MzE3NzQyNjUsIm5iZiI6MTYzMTc3NDI2NSwic3ViIjoiNTMwMjg4MTgtMzIyNy0xMWViLThmOGItMDI0MmFjMTIwMDA0IiwiZW1haWwiOiJib2JzNDQ2MkBnbWFpbC5jb20iLCJ0cmFjayI6ZmFsc2V9.oJJnmRtq1o1o_SmON1_EoBNtNkqrsljSK5LfV8z3AVg' \
    -H 'Content-Type: application/json' \
    -d '{
    "options": {
        "members": ["c977ab70-cf40-11eb-8633-0242ac120006"]

    }, 
    "resource": {
        "name": "",
        "icon": "",
        "description": "",
        "visibility": "direct"
    }
    
}'
```

**Comment by RomaricMourgues** [comment]
Soon on QA: https://github.com/linagora/Twake/pull/1663

**Comment by tlle14** [comment]
Thanks, 
Retest pass!

https://user-images.githubusercontent.com/69950655/143415810-0cb3e7b5-cc48-4a55-a245-12aacc5f4e63.mp4
