### ISSUE TITLE
Sign In > When the user already logged in on App, he isn't logged in on the Browser

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#930]
# Precondition
Set the default app is Chrome

# Actual Result
The user login on Twake Mobile App.
Then he opens the Chrome browser, navigates to the Console page, it displays the login screen

https://user-images.githubusercontent.com/69950655/133552798-4a05791d-c49e-4b59-9bd1-f6247a0287dc.mp4

# Expected Result
When the user opens the corresponding browser, he should see his account is logged in already

# Environment
- Build version: 3.0.5
- Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Why is won't fix @bobs4462 ?

**Comment by bobs4462** [comment]
Sorry, it seems my explanation wasn't posted the last time, here's it again:

When you press sign in button, what is opened is Safari View Controller, which is not a browser, it's just a "webview" like application which runs on top of Safari engine, it's impossible to open chrome or firefox, SafariVC is what you get, no matter how many other browsers you have installed. And this SafariVC doesn't share it's state with anyone (including other browsers), so all actions you perform on it, remains with it. Consider it being sort of enforced incognito mode

**Comment by tlle14** [comment]
So there is a difference in how the app works on  Android and iOS. Thank you.
