### ISSUE TITLE
Message > The counter on View reply button is not updated after deleting messages in the thread screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#933]
# Precondition
A parent message with 3 replies.
It displays "View 3 replies" on the main screen

# Actual Result
When deleting 2 messages in the thread screen, then back to the main screen, the View Reply button still displays 3 replies in total

https://user-images.githubusercontent.com/69950655/133583826-f034e825-ea56-4911-a622-8859fae225e9.mp4

 # Expected Result
The reply counter on the View Reply button should be updated consequently.
In this case, it should display 1 reply instead of 3 on the View Reply button

# Environment
- Build version: 3.0.5
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
![image](https://user-images.githubusercontent.com/31780624/133591522-250fd67d-a06c-4f52-aed9-eaec1da12ee7.png)
It seems on web when you delete a message, the reply counter doesn't change either

**Comment by bobs4462** [comment]
So what we get from API is basically wrong reply count, or we should render deleted messages, but then again, what is the point?
@BastiaanVanGaalen

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 For me, we have to display the actual number of replies that exists, so counter must be updated each time threaded message has been deleted.

**Comment by bobs4462** [comment]
I'm asking about whether we should render deleted messages, analogous to web. The counter is set on backend, and it counts all the messages, including the deleted ones.

**Comment by BastiaanVanGaalen** [comment]
Of course we should, as Whatsapp does, for instance. I will design the appearance in a while, thank you

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 @EvGen94  rendering of deleted messages: https://zpl.io/25m94Mj

**Comment by bobs4462** [comment]
@tlle14 we've added support for showing deleted messages, the counter will stay the same however, no matter how many messages you delete, because that's the way the backend works, if you think that's not the behavior that user wants, then open an issue on for Twake project where this behavior can be further discussed with others

**Comment by tlle14** [comment]
No, I totally agree with your solution.

**Comment by tlle14** [comment]
Please create a ticket for this task @bobs4462 . I will close this issue
