### ISSUE TITLE
Animation and vibration when interacting with the app

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#935]
# Actual Result
- On a thread screen:
When selecting a message, it highlights the background. 

https://user-images.githubusercontent.com/69950655/133598371-e703f3ce-be02-4c43-83e0-5e60dd1a9d94.mp4

- On other screens:
When tapping on buttons/ links or tabs, there is no corresponding animation or vibration 

# Expected Result
Please consider appropriate animation and vibration when interacting with the app

**Comment by bobs4462** [comment]
@BastiaanVanGaalen
