### ISSUE TITLE
Threaded replies preview  counter inside a message bubble

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [linagora/Twake-Mobile#942]
Update the design of threaded replies counter inside the 
message bubble

Design: https://zpl.io/2G5wM14!

[Capture d’écran 2021-09-17 à 18.23.25.png](https://images.zenhubusercontent.com/5ffec051b78a0364c9757c86/450a5405-1756-4480-8b5e-7092fbc14277)

**Comment by bobs4462** [comment]
@BastiaanVanGaalen I'm afraid messages do not contain information about the users who replied to them...
@RomaricMourgues How hard will it be to implement this feature?

**Comment by RomaricMourgues** [comment]
I can totally add this in the messages object. @BastiaanVanGaalen could you somehow plan to show the latest answer under the message in the UI ?
