### ISSUE TITLE
Sign Up > UI verification

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#943]
### 1. The elements on the Sign Up screen is too far from each others on a big screensize
The text "Already have account..." and Sign In button should shift to above
![screenshot_54](https://user-images.githubusercontent.com/69950655/133817250-0e72713c-ce8d-4412-9a16-512e788e2e05.png)

**Design:**
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/61113861be680b1644e20692
=> Need Designer verify how it displays

### 2.  The sign up success screen has "Sign In" button
It has "Sign In" button which does not appear in the design. But I think it is convenient.
By the way, the Sign In button is not symmetric with other elements on the screen.
![screenshot_53](https://user-images.githubusercontent.com/69950655/133817046-9e7a1ebe-e1e6-4920-a2f5-b88cfb01f93e.png)

**Design:** 
https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/612f6e2efe0ec71708a5422a
=> Need Designer to review if it is appropriate.

### 3. The sign-up success screen > A message has an inappropriate line break
![screenshot_55](https://user-images.githubusercontent.com/69950655/133957362-a84a41b0-d975-4768-933b-99e38ac1d506.png)

=> Please follow the design https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/612f6e2efe0ec71708a5422a

**Comment by tlle14** [comment]
Thank @EvGen94 
1. Retest pass!
2. Need @BastiaanVanGaalen 's confirmation
3. Retest pass!


---
**New issue:**

4. Sign Up screen > the Email placeholder: email => Email
5. Sign Up screen > When typing an email, the Email placeholder should transform to the Email textbox label. See the design

https://images.zenhubusercontent.com/309637937/1e0e3fc7-cf64-4243-87a7-a9c149d700d8/video61c0a562_0b58_4c60_9a0c_8c0a6528c04fvideo.mp4

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Let's keep "Sign in" button for now. 

There is some confusion around sign in flow on mobile. We have to investigate further into it.

**Comment by BastiaanVanGaalen** [comment]
@tlle14 As for "5) Sign Up screen > When typing an email, the Email placeholder should transform to the Email textbox label. See the design"

Let's keep it as it was implemented by Evgeny. We have lots of high-priority tasks at the moment and we just put this task with input behaviour on hold.

**Comment by tlle14** [comment]
Okay, as @BastiaanVanGaalen 's confirmation, i will close this issue.
