### ISSUE TITLE
Signup > Can't signup on IOS

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#950]
I can't signup on IOS.

### Step to reproduce
1. Open Twake mobile
2. Click on "signup"
3. Nothing append

### Screenshot

https://user-images.githubusercontent.com/22451567/134007825-5e04fa0c-e5cb-4fa6-aaa1-8467a2dbdc4f.mov

**Comment by bobs4462** [comment]
@BenoitTallandier On production the button is disabled on purpose, as the API on console side is not ready yet

**Comment by tlle14** [comment]
I got the same issue but it's okay after I reinstall the app.
