### ISSUE TITLE
Sign Up > It submits the email when user tapping on "Done" on the keyboard

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#956]
# Actual Result
Inputting the valid email address, then tapping the Done button on the keyboard, it submits the email.

https://user-images.githubusercontent.com/69950655/134110769-c957a098-0690-4f37-8a22-1d29332ed077.mp4

# Expected Result
Let's consider this. The Done button on the keyboard is only for closing the keyboard. 

# Environment
- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by BastiaanVanGaalen** [comment]
@tlle14 You mean "Done" stands for "Done typing and hide keyboard"? I'm ok with hiding keyboard upon tapping "Done", especially when we have "Start using Twake" button just above the keyboard.

**Comment by BastiaanVanGaalen** [comment]
@EvGen94 On the other side, do you have any reference apps in which "Done" equals "Submit"? We just need a common practice to be used to which users are used to, that's it.

**Comment by EvGen94** [comment]
@tlle14 @BastiaanVanGaalen I don't know I think it is convenient  - use done for submit in that case, but I will remove that

**Comment by tlle14** [comment]
Hi @EvGen94 @BastiaanVanGaalen 
I saw Facebook app do the same behavior with the Done button. 
I agree with @EvGen94, so this is no longer being an issue.
