### ISSUE TITLE
The sidebar menu is lost when the user switch to the new company he has just added

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#968]
# Precondition
The user has already been added to another company. 
But hasn't been added to any Workspace yet

# Actual Result
The Menu  sidebar is lost after the user switches to the new invited company
![screenshot_78](https://user-images.githubusercontent.com/69950655/134331767-d4d1c54f-986d-41af-a4ee-e67fa65b0f3b.png)

# Expected Result
The menu sidebar should always display even there is no workspace

# Environment

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@tlle14 what happens in web version? 
@BenoitTallandier I think we should avoid such confusing states when user is added to company, but cannot do anything with it. I suggest that user is always added to some default workspace/channel when added to company

**Comment by tlle14** [comment]
@bobs4462 They hide that company in the Company list. 
![screenshot_85](https://user-images.githubusercontent.com/69950655/134465509-11940509-f3a5-4b41-b483-d7d88baab0b8.png)

**Comment by BenoitTallandier** [comment]
I agree, we should be added in a default workspace.

**Comment by tlle14** [comment]
> I agree, we should be added in a default workspace.

Not with the new added Guest @BenoitTallandier 
It's only okay with the new added member.

**Comment by BenoitTallandier** [comment]
Yes, Guest are not added in the default workspace when they signup 👍

**Comment by bobs4462** [comment]
But guest shouldn't be added to company without being added to channel, so he should be guaranteed to have some company/workspace/channel

**Comment by EvGen94** [comment]
@tlle14 Done

**Comment by tlle14** [comment]
Hi @EvGen94 
The issue still be able to reproduce
