### ISSUE TITLE
Edit channel > Edit channel screen becomes empty after a long time unused

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#969]
# Precondition
Leave the phone about an hour

# Actual Result
When open the app, tap on the channel name to open edit channel screen, the screen is null

https://user-images.githubusercontent.com/69950655/134333119-f15e24b2-dd79-48e8-a9c1-c7e4fed14925.mp4

# Expected Result
The screen should be ready by the time user opening the app

# Environment

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
The issue is still happens
https://images.zenhubusercontent.com/309637937/367e6c2f-07d8-4616-94ea-a155cf7bc792/video26733c55_3e34_42f1_9705_78ecc71b36davideo.mp4

**Comment by bobs4462** [comment]
@tlle14 Are you sure you are using the latest build of the application, released on 23rd of september?

**Comment by tlle14** [comment]
It seems I tested on the previous build. 
I cannot reproduce the bug today.
