### ISSUE TITLE
Message > Cannot read the message 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#971]
# Actual Result
The user cannot see the message displaying in the channel, even he saw it in the message preview

Preview:
![screenshot_79](https://user-images.githubusercontent.com/69950655/134449716-dc060063-7ccf-44f5-9fa3-fc0dc451efa7.png)

In the channel:
![screenshot_80](https://user-images.githubusercontent.com/69950655/134449727-7a8bb187-6f1f-4b79-9260-29d86035c260.png)

# Expected Result
The message should display after received

# Environment

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Production

**Comment by tlle14** [comment]
Hi @bobs4462 
When I send a text after not using a device for a while, the message is not displayed to other people in the channel. 
I need to restart the app, then it works. 
Please investigate.

**Comment by bobs4462** [comment]
Do you have an indication that message was successfully delivered?

**Comment by tlle14** [comment]
> Do you have an indication that message was successfully delivered?

Yes. The indicator was displayed.

**Comment by bobs4462** [comment]
Actually I don't understand the issue, 
You send a message from mobile, then you cannot see the same message on web?

**Comment by tlle14** [comment]
My bad. Let's be describe it in details

# Precondition
The app on iOS is in the background running for a quite long time (about an hour or more)
UserA and UserB are in the same channel 

# Actual Result
UserA sends a message to the channel on Android App - a highlighted paragraph without mention. 
UserB doesn't see the message in the channel on iOS App

# Expected Result
UserB should be able to receive the message when he opens the app after a long time no using

**Comment by bobs4462** [comment]
Again, can you make sure that you are using the latest build (no update options on Play Market?)

**Comment by tlle14** [comment]
It seems my mistake when testing in a previous build. 
I cannot reproduce the bug today.
