### ISSUE TITLE
Channel list > Header and search bar takes up space on iOS

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#972]
# Actual Result
On iOS:
- The header (Twake name) is far from the status bar
- The Channels/Chats tab is far from the search bar
They take up space when comparing to Android version
![screenshot_82](https://user-images.githubusercontent.com/69950655/134455729-10d8340a-91e4-477d-b99d-e5cee5cc9e08.png)

Android version
![screenshot_83](https://user-images.githubusercontent.com/69950655/134455863-60e5ca80-8b39-45e0-a34b-49e568eaa0e6.png)

# Expected Result 
Please fix the UI on iOS.

# Environment

- Build version: 3.0.6
- Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by tlle14** [comment]
Hi @EvGen94 
Retest failed!
I don't see the change on iOS

**Comment by EvGen94** [comment]
@Hi! it's fine! 
Right before the build, we removed this fix as there could be problems on HD screens

**Comment by tlle14** [comment]
Thanks for the explaination @EvGen94 
Please put the ticket to the QA column after the fix is ready for retest (in the next build, maybe?)

**Comment by tlle14** [comment]
Thanks, retest pass!
![image](https://user-images.githubusercontent.com/69950655/143422821-cc9b11bb-e644-4aaf-ba70-7a7865397846.png)
