### ISSUE TITLE
Feedback > Misunderstanding the usage of a channel filter

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#974]
# Actual Result
User feedback: 
```
I just installed the app, the experience is fluid and for now it looks functional, I think you could improve the search experience because is not clear where is doing the search. In my test I wrote the word "Linux" and I got nothing, I tried with other words and at least in my first usage the search is not useful.
```
![screenshot_87](https://user-images.githubusercontent.com/69950655/134473247-184471cc-c0e1-4efd-863c-27210fb727f3.png)

# Expected Result
The search is a filter for channel/direct chats list.
How about putting a different placeholder to clarify?
Need to ask Designer

**Comment by BastiaanVanGaalen** [comment]
@tlle14 The placeholder can be versatile: Search for channels, messages and users

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen that search bar cannot search messages. 
But with user search, I think it's a good idea. How about merging the direct chat creation screen with the search bar? 
CC: @bobs4462 @EvGen94 @BenoitTallandier I'm not sure if the search can behave like that.

**Comment by BenoitTallandier** [comment]
Let me write a US for that. If we can search users, channel, messages, we need to think how to show result and in which order

**Comment by tlle14** [comment]
Retest pass! 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/fa11bfbf-f930-4ed2-9b00-a66257c0e702)
