### ISSUE TITLE
Workspace > There is no timeout when loading a workspace list on the sidebar

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#975]
# Actual Result
When refreshing the workspace list on the sidebar, it seems to load forever

https://user-images.githubusercontent.com/69950655/134481945-9f8d9e96-36b1-403c-9d08-75e00db5d838.mp4

# Expected Result
The workspace list loading should have a time-out

# Enviornment

- Build version: 3.0.6
- Device:
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by tlle14** [comment]
Hi @bobs4462 I cannot reproduce the issue after reinstalling the app. (because I cannot reopen the app)
I guess that time there was something happens with  QA server 
OR token is expired on iOS device.

**Comment by bobs4462** [comment]
Ok, anyway I'll add a timeout, just in case something happens on server side

**Comment by tlle14** [comment]
Thanks, retest pass!
