### ISSUE TITLE
Message > Multiquote, underline, italic cannot display on Mobile

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#98]
# Precondition
Multiquote is composed on the Web version
![image](https://user-images.githubusercontent.com/69950655/102322647-f3fae700-3fb1-11eb-8e3b-c0ba286576e1.png)

Underline and italic on Web:
![image](https://user-images.githubusercontent.com/69950655/102324569-987e2880-3fb4-11eb-93e5-48f406cc8860.png)

# Actual Result
The multiquote, underline and italic cannot display on mobile
![image](https://user-images.githubusercontent.com/69950655/102323055-931fde80-3fb2-11eb-89f2-c89bca11ba41.png)
![image](https://user-images.githubusercontent.com/69950655/102324871-0165a080-3fb5-11eb-9286-76a1e15ecdf2.png)

# Expected Result
The multiquote, underline and italic should  be able to display on Mobile

# Environment
app-release[2020-12-15]

**Comment by bobs4462** [comment]
@romanesko I think we should add support for these types of objects, because they are pretty common ones

**Comment by tlle14** [comment]
Thank @bobs4462 
**Retest pass with a single quote, italic, and underline.** 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/c16bdc7f-2c5f-4e7a-a269-cb1b71d2606d)

**It fails with a multiline quote.**
On Mobile:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/575d76db-ccdb-4413-9151-e0fe737e0715)

On Web:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/5b97d0f7-986e-433b-8925-26ab05fb84cd)

**Comment by bobs4462** [comment]
How do you make multiline quote on web?

**Comment by tlle14** [comment]
> How do you make multiline quote on web?
@bobs4462 hi, here you go

![image](https://user-images.githubusercontent.com/69950655/114853353-e6455900-9e0d-11eb-8a55-0a10ac9cd938.png)

**Comment by tlle14** [comment]
Hi @bobs4462 by mistake, I closed this issue. Now I have to reopen, please continue your work.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/64e7dfec-251f-4694-aeb4-a03c4da1d851)
