### ISSUE TITLE
Data is mixed up when logging in by the different account in a different server

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#985]
# Precondition
The app is logged in the Production account

# Actual result
When logging out to the current account then logging in to the app using a test account on the Test Server, it displays the company and workspaces of the previous account with the current account's

https://user-images.githubusercontent.com/69950655/135061967-6c6a9167-03df-4a8b-920b-a5905c84b955.mp4

# Expected Result
It should only display the data of the currently logged in account

# Environment
- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by bobs4462** [comment]
Is it 100% reproducible? Because according to app logic, after explicit logout all the data is purged, so it's impossible to have data from multiple accounts at the same time...

**Comment by tlle14** [comment]
It seems able to reproduce on iOS 100%. 
I'm not sure about the Android app. 
Better you try with the iOS first.
