### ISSUE TITLE
Message > The message indicator "sending" has no timeout

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#986]
# Precondition
In the unstable connection (not sure this condition)
OR the app is abandoned in a long time 

# Actual Result
When sending a message in a thread screen, it displays the sending indicator and doesn't change. 
When the user reopens the thread, the message is disappeared

https://user-images.githubusercontent.com/69950655/135082568-62407790-801d-4f03-ab9c-820413bcbe15.mp4

# Expected Result
The sending indicator should have a timeout and change to the fail indicator when the message is not successfully sent

# Environment 

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by EvGen94** [comment]
@tlle14

**Comment by tlle14** [comment]
Hi @EvGen94 
This issue is hard to reproduce since the internet connection is stable right now. 
I changed the label from medium -> low.
