### ISSUE TITLE
Channel > Displaying the timestamp of the first message as if the created channel time

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#987]
# Actual Result
The date of the first message is displaying above the channel info. It looks like the created channel time.
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566373661316538613136393865336431616532643936392f64313061303466342d366566332d343830312d613130362d643937333838633835636166](https://user-images.githubusercontent.com/69950655/135194620-f84e6fc3-942a-4c76-ad5a-6db2ff63008a.png)

# Expected Result
The date should display under the channel info. It displays for the first message, not the channel created time.

# Environment
- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment and Prod

**Comment by huynguyennovem** [comment]
It seems same as #1027 so that there is no first message anymore.
Pls help to confirm!

![Screenshot_1637293384](https://user-images.githubusercontent.com/29337364/142561390-c8cf2cce-dc0e-4d7a-a40b-82e8af1b2ff0.png)

**Comment by tlle14** [comment]
Hi @huynguyennovem 
The issue happens when you scroll to the first message of a channel (which has the chat history).
The screenshot you sent is from a new channel that doesn't have a chat history.
