### ISSUE TITLE
Edit channel > Unable to add member to the channel

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#997]
# Precondition
The channel is existing

# Actual Result
The user can perform adding a member to a channel. 
But after reopening the channel member list, there is no new added user

https://user-images.githubusercontent.com/69950655/135440075-691a9425-7396-497d-aa7a-bf78bfb7c7a1.mp4

# Expected result
It should be able to add a member to a channel

# Environment
Build version: 3.0.6
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by bobs4462** [comment]
@RomaricMourgues it seems the problem happens with private channels
1. You add a member via `POST /internal/services/channels/v1/companies/%s/workspaces/%s/channels/%s/members` endpoint
2. You check the web version, the member is there
3. You check the member with `GET /internal/services/channels/v1/companies/%s/workspaces/%s/channels/%s/members` again to see if it's really there, and it's not. So it seems the web uses different endpoints 

Tried it on QA enviroment. 

@tlle14 I couldn't reproduce the issue with public channels, can you confirm?

**Comment by tlle14** [comment]
Hi @bobs4462 
I can reproduce with a public channel I used to change its privacy (Or maybe there has a problem with the internet connection while adding members?)

https://user-images.githubusercontent.com/69950655/135465748-efa318ce-1e5a-4165-88eb-807d364e1314.mp4

**Comment by bobs4462** [comment]
I've checked the web version, the user was added. So it seems that only happens with certain users, despite of the channel

**Comment by EvGen94** [comment]
@tlle14 Hello!
I checked this with different channels, works fine, could you please check one more tine, and if this is still relevant, I need to check it using your login, because I can not reproduce it

**Comment by tlle14** [comment]
Thank @EvGen94 
I cannot reproduce it either on the current version.
I will close this issue.
