### ISSUE TITLE
Account  page > Notification toggle button doesn't work

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#999]
# Actual Result
We cannot control the notification toggle button
https://user-images.githubusercontent.com/69950655/135444037-4fa34042-a1aa-4018-a1e8-9d2788d16577.mp4

# Expected Result
Please hiding it

# Environment
Build version: 3.0.8 APK
Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by EvGen94** [comment]
Hello! the problem is that we cannot control this, it is always on, but if we remove this functionality from this screen, the screen will be too empty, so I made this parameter always on, I don’t know what is better to do in such a situation, I can remove it altogether

**Comment by bobs4462** [comment]
Hello @EvGen94 I've added method to register and unregister device on authentication cubit, so you can attach these binary operation on tumbler

**Comment by tlle14** [comment]
Thank guys, and I have to test one more feature :)

**Comment by tlle14** [comment]
Hi @bobs4462 @EvGen94 
Retest failed!
https://images.zenhubusercontent.com/309637937/1ab5426c-44a2-44f6-889d-ec7805012f7b/20211001_111229.mp4

**Comment by huynguyennovem** [comment]
Hided it on the latest build version. Pls confirm!

https://user-images.githubusercontent.com/29337364/142558748-3aa6cfbf-c921-4d97-9ad2-f5b3d28ec5a9.mov

**Comment by tlle14** [comment]
I agree, this issue is no longer valid. Thanks!
